# Generated by Django 5.2.17 on 2026-09-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market", "0041_simulation_evidence_admission"),
        ("research", "0023_phase7_source_grammar"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("version", models.CharField(max_length=40)),
                ("payload", models.JSONField()),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("key", "version"), name="p6a_method_version")
                ],
            },
        ),
        migrations.CreateModel(
            name="CapacityAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("assessed_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("recorded_at", models.DateTimeField(editable=False)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CostEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("known_at", models.DateTimeField()),
                ("stale_after", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("recorded_at", models.DateTimeField(editable=False)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EligibilitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("valid_from", models.DateTimeField(editable=False)),
                ("valid_until", models.DateTimeField(null=True)),
                ("decision_known_at", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("recorded_at", models.DateTimeField(editable=False)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MultiTimeframeAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("information_cutoff", models.DateTimeField()),
                ("input_manifest", models.JSONField()),
                ("input_digest", models.CharField(max_length=64, unique=True)),
                ("output", models.JSONField()),
                ("output_digest", models.CharField(max_length=64)),
                ("recorded_at", models.DateTimeField(editable=False)),
                (
                    "capacity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.capacityassessment",
                    ),
                ),
                (
                    "cost",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.costevidence",
                    ),
                ),
                (
                    "eligibility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.eligibilitysnapshot",
                    ),
                ),
                (
                    "evidence_packet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research.frozenevidencepacket",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.assessmentmethod",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.marketstatesnapshot"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EligibleTradeIntentCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("semantic_identity", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("recorded_at", models.DateTimeField(editable=False)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.strategyevaluation"
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.eligibletradeintentcandidate",
                    ),
                ),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assessments.multitimeframeassessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntentSupersession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payload", models.JSONField()),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("recorded_at", models.DateTimeField(editable=False)),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="assessments.eligibletradeintentcandidate",
                    ),
                ),
                (
                    "successor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes_observation",
                        to="assessments.eligibletradeintentcandidate",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("predecessor", models.F("successor")), _negated=True),
                        name="p6a_distinct_successor",
                    )
                ],
            },
        ),
    ]
