# Generated by Django 5.2.17 on 2026-08-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=80)),
                ("actor", models.CharField(max_length=120)),
                ("subject_type", models.CharField(max_length=80)),
                ("subject_id", models.CharField(max_length=120)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("USD_CAD", "USD/CAD"),
                            ("GBP_USD", "GBP/USD"),
                            ("EUR_GBP", "EUR/GBP"),
                            ("EUR_USD", "EUR/USD"),
                        ],
                        max_length=7,
                        unique=True,
                    ),
                ),
                ("base_currency", models.CharField(max_length=3)),
                ("quote_currency", models.CharField(max_length=3)),
                ("display_order", models.PositiveSmallIntegerField(unique=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("display_order",),
            },
        ),
        migrations.CreateModel(
            name="SourceRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("established", "Established"),
                            ("contextual", "Contextual"),
                            ("quarantine", "Quarantine"),
                        ],
                        max_length=16,
                    ),
                ),
                ("base_url", models.URLField()),
                ("terms_url", models.URLField(blank=True)),
                ("terms_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("acquisition_method", models.CharField(max_length=80)),
                ("retention_policy", models.TextField()),
                ("llm_processing_allowed", models.BooleanField(default=False)),
                ("attribution_required", models.BooleanField(default=True)),
                ("deletion_policy", models.TextField(blank=True)),
                ("export_policy", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "granularity",
                    models.CharField(choices=[("D", "Daily"), ("H4", "Four-hour")], max_length=3),
                ),
                ("requested_from", models.DateTimeField()),
                ("requested_to", models.DateTimeField()),
                ("parameters", models.JSONField()),
                ("request_manifest_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=12,
                    ),
                ),
                ("fetched_count", models.PositiveIntegerField(default=0)),
                ("stored_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("failure_reason", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.sourceregistry"
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "granularity",
                    models.CharField(choices=[("D", "Daily"), ("H4", "Four-hour")], max_length=3),
                ),
                ("timestamp", models.DateTimeField(help_text="UTC interval-start timestamp")),
                ("complete", models.BooleanField()),
                ("volume", models.PositiveIntegerField()),
                ("bid_open", models.DecimalField(decimal_places=6, max_digits=12)),
                ("bid_high", models.DecimalField(decimal_places=6, max_digits=12)),
                ("bid_low", models.DecimalField(decimal_places=6, max_digits=12)),
                ("bid_close", models.DecimalField(decimal_places=6, max_digits=12)),
                ("ask_open", models.DecimalField(decimal_places=6, max_digits=12)),
                ("ask_high", models.DecimalField(decimal_places=6, max_digits=12)),
                ("ask_low", models.DecimalField(decimal_places=6, max_digits=12)),
                ("ask_close", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candles",
                        to="market.ingestionrun",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
            ],
            options={
                "ordering": ("timestamp",),
                "indexes": [
                    models.Index(
                        fields=["instrument", "granularity", "-timestamp"],
                        name="market_cand_instrum_4eec40_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "granularity", "timestamp"),
                        name="unique_market_candle",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("complete", True)), name="stored_candles_complete"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("volume__gte", 0)), name="candle_volume_nonnegative"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TechnicalSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "granularity",
                    models.CharField(choices=[("D", "Daily"), ("H4", "Four-hour")], max_length=3),
                ),
                ("as_of", models.DateTimeField()),
                ("candle_count", models.PositiveIntegerField()),
                ("atr_14", models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ("ewma_20", models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ("prior_high", models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ("prior_low", models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ("support", models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ("resistance", models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
            ],
            options={
                "ordering": ("-as_of",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "granularity", "as_of"),
                        name="unique_technical_snapshot",
                    )
                ],
            },
        ),
    ]
