# Generated by Django 5.2.17 on 2026-08-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_audit_event_append_only"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="candle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("bid_low__lte", models.F("bid_open")),
                    ("bid_low__lte", models.F("bid_close")),
                    ("bid_high__gte", models.F("bid_open")),
                    ("bid_high__gte", models.F("bid_close")),
                ),
                name="candle_bid_ohlc_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="candle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ask_low__lte", models.F("ask_open")),
                    ("ask_low__lte", models.F("ask_close")),
                    ("ask_high__gte", models.F("ask_open")),
                    ("ask_high__gte", models.F("ask_close")),
                ),
                name="candle_ask_ohlc_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="candle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("bid_close__lte", models.F("ask_close")),
                    ("bid_high__lte", models.F("ask_high")),
                    ("bid_low__lte", models.F("ask_low")),
                    ("bid_open__lte", models.F("ask_open")),
                ),
                name="candle_bid_not_above_ask",
            ),
        ),
    ]
