# Generated by Django 5.2.17 on 2026-08-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_candle_candle_bid_ohlc_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candle",
            name="granularity",
            field=models.CharField(
                choices=[("D", "Daily"), ("H4", "Four-hour"), ("H1", "Hourly")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="ingestionrun",
            name="granularity",
            field=models.CharField(
                choices=[("D", "Daily"), ("H4", "Four-hour"), ("H1", "Hourly")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="technicalsnapshot",
            name="granularity",
            field=models.CharField(
                choices=[("D", "Daily"), ("H4", "Four-hour"), ("H1", "Hourly")], max_length=3
            ),
        ),
    ]
