# Generated by Django 5.2.17 on 2026-08-20 19:55

import django.db.models.deletion
from django.db import migrations, models

CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION reject_mutation_market_oandainstrumenttermssnapshot()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'market_oandainstrumenttermssnapshot is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER market_oandainstrumenttermssnapshot_immutable
BEFORE UPDATE OR DELETE ON market_oandainstrumenttermssnapshot
FOR EACH ROW EXECUTE FUNCTION reject_mutation_market_oandainstrumenttermssnapshot();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS market_oandainstrumenttermssnapshot_immutable
ON market_oandainstrumenttermssnapshot;
DROP FUNCTION IF EXISTS reject_mutation_market_oandainstrumenttermssnapshot();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0004_alter_candle_granularity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OandaInstrumentTermsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("environment", models.CharField(max_length=12)),
                ("account_fingerprint", models.CharField(max_length=64)),
                ("account_currency", models.CharField(max_length=3)),
                ("long_financing_rate", models.DecimalField(decimal_places=10, max_digits=15)),
                ("short_financing_rate", models.DecimalField(decimal_places=10, max_digits=15)),
                ("financing_days", models.JSONField()),
                ("commission", models.JSONField(default=dict)),
                ("commission_supplied", models.BooleanField(default=False)),
                ("margin_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("pip_location", models.SmallIntegerField()),
                ("response_sha256", models.CharField(max_length=64)),
                ("captured_at", models.DateTimeField()),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at", "instrument__display_order"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "environment", "account_fingerprint", "captured_at"),
                        name="unique_oanda_terms_snapshot",
                    )
                ],
            },
        ),
        migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER),
    ]
