# Generated by Django 5.2.17 on 2026-08-27 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0005_oandainstrumenttermssnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandleConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("existing_payload_sha256", models.CharField(max_length=64)),
                ("incoming_payload_sha256", models.CharField(max_length=64)),
                ("differing_fields", models.JSONField()),
                ("incoming_payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataQualityIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("details", models.JSONField(default=dict)),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DatasetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("version", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("manifest", models.JSONField(default=dict)),
                ("manifest_sha256", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IngestionManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payload", models.JSONField()),
                ("sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="candle",
            name="unique_market_candle",
        ),
        migrations.AlterField(
            model_name="candle",
            name="granularity",
            field=models.CharField(
                choices=[("W", "Weekly"), ("D", "Daily"), ("H4", "Four-hour"), ("H1", "Hourly")],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="ingestionrun",
            name="granularity",
            field=models.CharField(
                choices=[("W", "Weekly"), ("D", "Daily"), ("H4", "Four-hour"), ("H1", "Hourly")],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="ingestionrun",
            name="request_manifest_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="ingestionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("quarantined", "Quarantined"),
                ],
                default="running",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="code",
            field=models.CharField(
                choices=[
                    ("AUD_USD", "AUD/USD"),
                    ("USD_CAD", "USD/CAD"),
                    ("GBP_USD", "GBP/USD"),
                    ("EUR_GBP", "EUR/GBP"),
                    ("EUR_USD", "EUR/USD"),
                    ("USD_JPY", "USD/JPY"),
                ],
                max_length=7,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="technicalsnapshot",
            name="granularity",
            field=models.CharField(
                choices=[("W", "Weekly"), ("D", "Daily"), ("H4", "Four-hour"), ("H1", "Hourly")],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="candleconflict",
            name="existing_candle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conflicts",
                to="market.candle",
            ),
        ),
        migrations.AddField(
            model_name="dataqualityincident",
            name="ingestion_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quality_incidents",
                to="market.ingestionrun",
            ),
        ),
        migrations.AddField(
            model_name="datasetversion",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="market.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="datasetversion",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="market.sourceregistry",
            ),
        ),
        migrations.AddField(
            model_name="dataqualityincident",
            name="dataset_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incidents",
                to="market.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="candleconflict",
            name="dataset_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conflicts",
                to="market.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="candle",
            name="dataset_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candles",
                to="market.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="ingestionrun",
            name="dataset_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingestion_runs",
                to="market.datasetversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="candle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dataset_version__isnull", False)),
                fields=("dataset_version", "instrument", "granularity", "timestamp"),
                name="unique_dataset_market_candle",
            ),
        ),
        migrations.AddConstraint(
            model_name="candle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dataset_version__isnull", True)),
                fields=("instrument", "granularity", "timestamp"),
                name="unique_legacy_market_candle",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dataset_version__isnull", False)),
                fields=("dataset_version", "request_manifest_hash"),
                name="unique_dataset_ingestion_manifest_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dataset_version__isnull", True)),
                fields=("request_manifest_hash",),
                name="unique_legacy_ingestion_manifest_hash",
            ),
        ),
        migrations.AddField(
            model_name="ingestionmanifest",
            name="dataset_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manifests",
                to="market.datasetversion",
            ),
        ),
        migrations.AddField(
            model_name="ingestionmanifest",
            name="ingestion_run",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingestion_manifest",
                to="market.ingestionrun",
            ),
        ),
        migrations.AddField(
            model_name="candleconflict",
            name="ingestion_manifest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conflicts",
                to="market.ingestionmanifest",
            ),
        ),
        migrations.AddConstraint(
            model_name="datasetversion",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="unique_dataset_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="dataqualityincident",
            constraint=models.UniqueConstraint(
                fields=("dataset_version", "code", "evidence_sha256"),
                name="unique_dataset_quality_incident",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionmanifest",
            constraint=models.UniqueConstraint(
                fields=("dataset_version", "sha256"), name="unique_dataset_manifest_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="candleconflict",
            constraint=models.UniqueConstraint(
                fields=("ingestion_manifest", "existing_candle", "incoming_payload_sha256"),
                name="unique_candle_conflict_payload",
            ),
        ),
    ]
