# Generated by Django 5.2.17 on 2026-08-30 00:26

import django.db.models.deletion
from django.db import migrations, models

PREFLIGHT_TABLES = (
    "market_historicaldiscoveryplan",
    "market_historicaldiscoverychunk",
    "market_historicaldiscoveryattempt",
    "market_historicaldiscoveryproviderevidence",
    "market_historicaldiscoveryapproval",
    "market_historicaldiscoveryregistration",
    "market_historicaltimestampinventory",
    "market_historicaltimestampobservation",
    "market_auditevent",
    "market_ingestionrun",
    "market_instrument",
    "market_sourceregistry",
)
# Portable fingerprints of every 0013 governance object migration 0014
# depends on, captured from a catalog migrated exactly through 0013.
# Functions are fingerprinted over schema, name, identity arguments, return
# type, language, volatility, strictness, security-definer, leakproof,
# parallel safety, configuration (e.g. search_path), and the verbatim
# dollar-quoted body; triggers over schema, table, name, enabled state,
# timing/events/level (tgtype), called function schema, name and identity
# arguments, trigger arguments, constraint/deferrable/initially-deferred
# properties, any WHEN expression, and the reconstructed definition. Both
# representations are catalog-derived and OID/primary-key independent.
FUNCTION_FINGERPRINT_SQL = """
    SELECT p.proname,
           pg_get_function_identity_arguments(p.oid),
           md5(jsonb_build_object(
             'schema', n.nspname,
             'name', p.proname,
             'identity_arguments', pg_get_function_identity_arguments(p.oid),
             'return_type', pg_catalog.format_type(p.prorettype, NULL),
             'language', l.lanname,
             'volatility', p.provolatile::text,
             'strict', p.proisstrict,
             'security_definer', p.prosecdef,
             'leakproof', p.proleakproof,
             'parallel', p.proparallel::text,
             'config', to_jsonb(p.proconfig),
             'source', p.prosrc,
             'bin', p.probin)::text)
      FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
      JOIN pg_language l ON l.oid = p.prolang
     WHERE n.nspname = current_schema() AND p.proname = ANY(%s)
"""
TRIGGER_FINGERPRINT_SQL = """
    SELECT c.relname,
           t.tgname,
           md5(jsonb_build_object(
             'schema', n.nspname,
             'table', c.relname,
             'name', t.tgname,
             'enabled', t.tgenabled::text,
             'type', t.tgtype::int,
             'function_schema', pn.nspname,
             'function_name', p.proname,
             'function_identity_arguments', pg_get_function_identity_arguments(t.tgfoid),
             'arguments', encode(t.tgargs, 'hex'),
             'is_constraint', t.tgconstraint <> 0,
             'deferrable', t.tgdeferrable,
             'initially_deferred', t.tginitdeferred,
             'when', pg_get_expr(t.tgqual, t.tgrelid),
             'definition', pg_get_triggerdef(t.oid))::text)
      FROM pg_trigger t
      JOIN pg_class c ON c.oid = t.tgrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      JOIN pg_proc p ON p.oid = t.tgfoid
      JOIN pg_namespace pn ON pn.oid = p.pronamespace
     WHERE NOT t.tgisinternal AND n.nspname = current_schema()
"""
PREFLIGHT_FUNCTIONS = {
    "market_canonical_json": ("value jsonb", "aa43ea03a68b240dfcda6e2404c500a6"),
    "market_discovery_audit_reject_mutation": ("", "d91bbb0f631c2f39f8bcb229e16cd656"),
    "market_discovery_audit_reject_truncate": ("", "b5b0de2bd49976d91725d85295861ad3"),
    "market_discovery_operational_timestamp": (
        "value timestamp with time zone",
        "0ade13a9b0800de89465ec203f3a6f45",
    ),
    "market_discovery_reject_mutation": ("", "92d96335c5a444cfdb531c1423310a80"),
    "market_discovery_reject_sealed_insert": ("", "1c07d17226742eb2e6822f3d37052d47"),
    "market_discovery_reject_truncate": ("", "967b6921befcaf664b08f7456f5dc27d"),
    "market_discovery_timestamp": (
        "value timestamp with time zone",
        "b7dafb1af452f2c208f4b0c2c2ef4dc3",
    ),
    "market_sha256": ("value jsonb", "96fd2a64d0e7a49328292c13b3708d98"),
    "market_validate_discovery_attempt": ("", "a885693dcb97e6346ce49f9d909440fe"),
    "market_validate_discovery_audit_insert": ("", "5639f8ad20d97c0623649dc2fd7d2f51"),
    "market_validate_discovery_chunk": ("", "c52d97167722c8845958b7b2169638f1"),
    "market_validate_discovery_inventory_deferred": ("", "cbabdd794c4287fbe37d9562bd201ded"),
    "market_validate_discovery_observation": ("", "6a15143e3819769cce91d0bfcc2e8842"),
    "market_validate_discovery_plan": ("", "a27d41213e8b79e8d42c298561df8baf"),
    "market_validate_discovery_provider_evidence": ("", "3ada738511255b66c867407858155038"),
    "market_validate_discovery_seal_deferred": ("", "c06d697d25a9884c226938876708d2fe"),
    "market_validate_discovery_terminal_run": ("", "ebbd7291f5f12c7f01f98fe29d01e5f3"),
}
PREFLIGHT_TRIGGERS = {
    ("market_auditevent", "market_discovery_audit_immutable"): "9e04e08b33ba7fdba47075343422c7f6",
    ("market_auditevent", "market_discovery_audit_no_truncate"): "77f26dd2ac3edc1df5eac1117ec9c4b8",
    ("market_auditevent", "market_discovery_audit_validate"): "40a061306928fdc23f5018034229acd1",
    (
        "market_historicaldiscoveryapproval",
        "market_discovery_approval_atomic",
    ): "aa290706f7435a1c60abc57b355b24d2",
    (
        "market_historicaldiscoveryapproval",
        "market_historicaldiscoveryapproval_append_only",
    ): "c844ea8660aaed503566ac1066d27451",
    (
        "market_historicaldiscoveryapproval",
        "market_historicaldiscoveryapproval_reject_truncate",
    ): "cbce844045cd2e796a1d3c535d169db3",
    (
        "market_historicaldiscoveryattempt",
        "market_discovery_attempt_validate",
    ): "b39fdfb53ad1ac0e994277bfd87babae",
    (
        "market_historicaldiscoveryattempt",
        "market_historicaldiscoveryattempt_append_only",
    ): "6d93c191daa3ecf9f79a881bc0e6006f",
    (
        "market_historicaldiscoveryattempt",
        "market_historicaldiscoveryattempt_reject_truncate",
    ): "60c90b63ad51933c70e16503fbc32fac",
    (
        "market_historicaldiscoverychunk",
        "market_discovery_chunk_validate",
    ): "cd35f1ca6dd08175600f9cd8c5f6777c",
    (
        "market_historicaldiscoverychunk",
        "market_historicaldiscoverychunk_append_only",
    ): "4264f1f4413d8487d8c596f6d3b0bb3a",
    (
        "market_historicaldiscoverychunk",
        "market_historicaldiscoverychunk_reject_truncate",
    ): "20ee8e7b7426b227457766e6f6e7f421",
    (
        "market_historicaldiscoveryplan",
        "market_discovery_plan_seal_atomic",
    ): "c0d17766fdbcfc98a1c31858dd2df34f",
    (
        "market_historicaldiscoveryplan",
        "market_discovery_plan_validate",
    ): "142452d82dba67fa68c732da48bd8550",
    (
        "market_historicaldiscoveryplan",
        "market_historicaldiscoveryplan_reject_truncate",
    ): "fad12baa827374a0a994e58afa04bc9c",
    (
        "market_historicaldiscoveryproviderevidence",
        "market_discovery_provider_unsealed",
    ): "d088edbcea3a3308aec0af84ff7ae080",
    (
        "market_historicaldiscoveryproviderevidence",
        "market_discovery_provider_validate",
    ): "4feaf0411d227ac5cb3bd5215fbd4135",
    (
        "market_historicaldiscoveryproviderevidence",
        "market_historicaldiscoveryproviderevidence_append_only",
    ): "91f3aa96d07ec0f7c7f45034c190d506",
    (
        "market_historicaldiscoveryproviderevidence",
        "market_historicaldiscoveryproviderevidence_reject_truncate",
    ): "c545e154ea88a46e9600cb2e2cd733c7",
    (
        "market_historicaldiscoveryregistration",
        "market_discovery_registration_atomic",
    ): "3d6b0ab734c4b8a716fd9a55b909d5ff",
    (
        "market_historicaldiscoveryregistration",
        "market_historicaldiscoveryregistration_append_only",
    ): "1b9c446f62b746f9e929a0d8be33c8a2",
    (
        "market_historicaldiscoveryregistration",
        "market_historicaldiscoveryregistration_reject_truncate",
    ): "c339f3d78175624df4a00895883ab9d9",
    (
        "market_historicaltimestampinventory",
        "market_discovery_inventory_reconstruct",
    ): "f15462f1f8ece8355c6699322eb09597",
    (
        "market_historicaltimestampinventory",
        "market_discovery_inventory_unsealed",
    ): "4f61e6b1ea7fc23a424477274bdf3f22",
    (
        "market_historicaltimestampinventory",
        "market_historicaltimestampinventory_append_only",
    ): "bacde001af1e6692466b8e1973ea9a2c",
    (
        "market_historicaltimestampinventory",
        "market_historicaltimestampinventory_reject_truncate",
    ): "5c2ff39e5ecac7cdae01ac48d0575314",
    (
        "market_historicaltimestampobservation",
        "market_discovery_observation_validate",
    ): "ab51c3031892cd203d5220471d9ee406",
    (
        "market_historicaltimestampobservation",
        "market_historicaltimestampobservation_append_only",
    ): "ec5596e660660931a76ba1a196a5541f",
    (
        "market_historicaltimestampobservation",
        "market_historicaltimestampobservation_reject_truncate",
    ): "b03d451c0a747265dbde35ca70f9d959",
    ("market_ingestionrun", "market_discovery_run_terminal"): "f7fac0b7a1b393de30461d5dfc89c978",
}
SUPERSESSION_TABLE = "market_historicaldiscoverysupersession"
SUPERSESSION_FUNCTIONS = (
    "market_discovery_plan_xact_lock",
    "market_validate_discovery_supersession",
    "market_reject_superseded_discovery_write",
    "market_discovery_supersession_reject_mutation",
    "market_discovery_supersession_reject_truncate",
)
SUPERSESSION_TRIGGERS = (
    "market_discovery_supersession_validate",
    "market_discovery_supersession_immutable",
    "market_discovery_supersession_no_truncate",
    "market_discovery_00_superseded_plan",
    "market_discovery_00_superseded_chunk",
    "market_discovery_00_superseded_attempt",
    "market_discovery_00_superseded_approval",
    "market_discovery_00_superseded_registration",
)


def preflight_supersession_governance(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    problems = []
    with schema_editor.connection.cursor() as cursor:
        for table in PREFLIGHT_TABLES:
            cursor.execute("SELECT to_regclass(%s)", [table])
            if cursor.fetchone()[0] is None:
                problems.append(f"required table {table} is missing")
        cursor.execute(FUNCTION_FINGERPRINT_SQL, [list(PREFLIGHT_FUNCTIONS)])
        found_functions = {}
        for name, identity_arguments, fingerprint in cursor.fetchall():
            found_functions.setdefault(name, []).append((identity_arguments, fingerprint))
        for name, expected in sorted(PREFLIGHT_FUNCTIONS.items()):
            candidates = found_functions.get(name, [])
            if not candidates:
                problems.append(f"required function {name} is missing")
            elif len(candidates) > 1:
                problems.append(f"required function {name} has ambiguous overloads")
            elif candidates[0] != tuple(expected):
                problems.append(f"required function {name} does not match its 0013 definition")
        cursor.execute(TRIGGER_FINGERPRINT_SQL)
        found_triggers = {}
        for table, name, fingerprint in cursor.fetchall():
            found_triggers.setdefault((table, name), []).append(fingerprint)
        trigger_names = {name for _, name in found_triggers}
        for (table, name), expected in sorted(PREFLIGHT_TRIGGERS.items()):
            candidates = found_triggers.get((table, name), [])
            if not candidates:
                problems.append(f"required trigger {name} on {table} is missing")
            elif len(candidates) > 1:
                problems.append(f"required trigger {name} on {table} is ambiguous")
            elif candidates[0] != expected:
                problems.append(
                    f"required trigger {name} on {table} does not match its 0013 definition"
                )
        cursor.execute("SELECT to_regclass(%s)", [SUPERSESSION_TABLE])
        if cursor.fetchone()[0] is not None:
            problems.append(f"unexpected pre-existing table {SUPERSESSION_TABLE}")
        cursor.execute(
            """SELECT p.proname FROM pg_proc p
               JOIN pg_namespace n ON n.oid = p.pronamespace
               WHERE n.nspname = current_schema() AND p.proname = ANY(%s)""",
            [list(SUPERSESSION_FUNCTIONS)],
        )
        for (name,) in cursor.fetchall():
            problems.append(f"unexpected pre-existing supersession function {name}")
        for name in SUPERSESSION_TRIGGERS:
            if name in trigger_names:
                problems.append(f"unexpected pre-existing supersession trigger {name}")
    if problems:
        raise RuntimeError(
            "migration 0014 preflight rejected the current catalog: " + "; ".join(problems)
        )


def install_supersession_governance(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        r"""
        CREATE FUNCTION market_discovery_plan_xact_lock(plan_key bigint) RETURNS void AS $$
          SELECT pg_advisory_xact_lock(
            hashtextextended('market-discovery-plan-governance:'||plan_key::text, 4225531));
        $$ LANGUAGE sql;

        CREATE FUNCTION market_validate_discovery_supersession() RETURNS trigger AS $$
        DECLARE superseded record; replacement record; lineage record;
                superseded_version integer; replacement_version integer;
                audit_count integer; audit_hash text; expected_payload jsonb;
                cycle_exists boolean; invalid_v2_layout boolean;
        BEGIN
          PERFORM market_discovery_plan_xact_lock(
            LEAST(NEW.superseded_plan_id, NEW.replacement_plan_id));
          PERFORM market_discovery_plan_xact_lock(
            GREATEST(NEW.superseded_plan_id, NEW.replacement_plan_id));
          SELECT * INTO STRICT superseded FROM market_historicaldiscoveryplan
            WHERE id=NEW.superseded_plan_id;
          SELECT * INTO STRICT replacement FROM market_historicaldiscoveryplan
            WHERE id=NEW.replacement_plan_id;
          SELECT a.id,a.attempt_number,a.idempotency_key,c.plan_id,c.logical_key,
                 c.canonical_request_sha256,r.request_manifest_hash,r.status,
                 r.failure_reason,e.terminal_event_sha256,e.operational_evidence_sha256
            INTO STRICT lineage FROM market_historicaldiscoveryattempt a
            JOIN market_historicaldiscoverychunk c ON c.id=a.chunk_id
            JOIN market_ingestionrun r ON r.id=a.ingestion_run_id
            JOIN market_historicaldiscoveryproviderevidence e ON e.attempt_id=a.id
            WHERE a.id=NEW.governing_attempt_id;
          SELECT count(*),min(audit.payload->>'event_sha256') INTO audit_count,audit_hash
            FROM market_auditevent audit
            WHERE audit.subject_type='HistoricalDiscoveryAttempt'
              AND audit.subject_id=NEW.governing_attempt_id::text
              AND audit.event_type='market.historical_discovery_failed';
          superseded_version := substring(superseded.version from 'v([1-9][0-9]*)$')::integer;
          replacement_version := substring(replacement.version from 'v([1-9][0-9]*)$')::integer;
          WITH RECURSIVE lineage_path(plan_id) AS (
            SELECT NEW.replacement_plan_id
            UNION
            SELECT s.replacement_plan_id
              FROM market_historicaldiscoverysupersession s
              JOIN lineage_path path ON s.superseded_plan_id=path.plan_id
          ) SELECT EXISTS(SELECT 1 FROM lineage_path
                           WHERE plan_id=NEW.superseded_plan_id) INTO cycle_exists;
          expected_payload := jsonb_build_object(
            'identity','historical-discovery-supersession-v1',
            'reason_code','PROVIDER_REQUEST_BOUND_UNSAFE',
            'superseded_plan_sha256',superseded.sha256,
            'superseded_request_manifest_sha256',
              superseded.canonical_request_manifest_sha256,
            'replacement_plan_sha256',replacement.sha256,
            'replacement_request_manifest_sha256',
              replacement.canonical_request_manifest_sha256,
            'governing_attempt_idempotency_key',lineage.idempotency_key,
            'governing_run_request_manifest_hash',lineage.request_manifest_hash,
            'governing_failure_code',lineage.failure_reason,
            'governing_terminal_event_sha256',lineage.terminal_event_sha256,
            'governing_operational_evidence_sha256',lineage.operational_evidence_sha256,
            'governing_audit_event_sha256',audit_hash);

          invalid_v2_layout := false;
          IF replacement.version='phase-2b1r-discovery-v2' THEN
            invalid_v2_layout :=
              replacement.identity<>'failed-break-phase-2b1r-discovery-plan-v2'
              OR replacement.declared_chunk_count<>132
              OR (SELECT count(*) FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='D')<>6
              OR (SELECT count(*) FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='H1')<>120
              OR (SELECT count(*) FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='W')<>6
              OR EXISTS(SELECT 1 FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='H1'
                    AND c.requested_to-c.requested_from>interval '4000 hours')
              OR EXISTS(
                SELECT 1 FROM (
                  SELECT c.instrument_id,c.requested_from,c.requested_to,
                         lag(c.requested_to) OVER (
                           PARTITION BY c.instrument_id ORDER BY c.requested_from) AS prior_to,
                         row_number() OVER (
                           PARTITION BY c.instrument_id ORDER BY c.requested_from) AS position,
                         count(*) OVER (PARTITION BY c.instrument_id) AS series_count
                    FROM market_historicaldiscoverychunk c
                    WHERE c.plan_id=replacement.id AND c.granularity='H1'
                ) ordered
                WHERE ordered.series_count<>20
                   OR (ordered.position=1 AND ordered.requested_from<>
                       timestamptz '2009-12-31 15:00:00+00')
                   OR (ordered.position>1 AND ordered.requested_from<>ordered.prior_to)
                   OR (ordered.position=ordered.series_count AND ordered.requested_to<>
                       timestamptz '2019-01-01 04:00:00+00'))
              OR EXISTS(
                SELECT 1 FROM market_instrument i
                WHERE i.code IN ('AUD_USD','EUR_GBP','EUR_USD','GBP_USD','USD_CAD','USD_JPY')
                  AND (SELECT count(*) FROM market_historicaldiscoverychunk c
                       WHERE c.plan_id=replacement.id AND c.instrument_id=i.id
                         AND c.granularity='D'
                         AND c.requested_from=timestamptz '2009-02-26 22:00:00+00'
                         AND c.requested_to=timestamptz '2018-12-31 22:00:00+00')<>1)
              OR EXISTS(
                SELECT 1 FROM market_instrument i
                WHERE i.code IN ('AUD_USD','EUR_GBP','EUR_USD','GBP_USD','USD_CAD','USD_JPY')
                  AND (SELECT count(*) FROM market_historicaldiscoverychunk c
                       WHERE c.plan_id=replacement.id AND c.instrument_id=i.id
                         AND c.granularity='W'
                         AND c.requested_from=timestamptz '2009-12-18 22:00:00+00'
                         AND c.requested_to=timestamptz '2018-12-28 22:00:00+00')<>1);
          END IF;

          IF NEW.superseded_plan_id=NEW.replacement_plan_id OR cycle_exists
             OR superseded_version IS NULL OR replacement_version IS NULL
             OR replacement_version<=superseded_version
             OR superseded.sealed_at IS NOT NULL OR replacement.sealed_at IS NOT NULL
             OR superseded.version<>'phase-2b1r-discovery-v1'
             OR superseded.identity<>'failed-break-phase-2b1r-discovery-plan-v1'
             OR superseded.sha256<>
                '292556a591024876c7051212d1c6886cd026a097e141295e9b60257fc5402b33'
             OR market_sha256(superseded.payload)<>
                '292556a591024876c7051212d1c6886cd026a097e141295e9b60257fc5402b33'
             OR superseded.canonical_request_manifest_sha256<>
                'a3cf7ef1f484d2379bfd1ef94769216b2ed9b41635cad7cadbd71a8de251bb2e'
             OR market_sha256(superseded.payload->'requests')<>
                'a3cf7ef1f484d2379bfd1ef94769216b2ed9b41635cad7cadbd71a8de251bb2e'
             OR market_sha256(superseded.canonical_request_manifest)<>
                'a3cf7ef1f484d2379bfd1ef94769216b2ed9b41635cad7cadbd71a8de251bb2e'
             OR replacement.version<>'phase-2b1r-discovery-v2'
             OR replacement.identity<>'failed-break-phase-2b1r-discovery-plan-v2'
             OR replacement.sha256<>
                '2a25bbc28fca5d596b26d3d2921fa881e374174fb08cc1dbfb51e47c8b138e3a'
             OR market_sha256(replacement.payload)<>
                '2a25bbc28fca5d596b26d3d2921fa881e374174fb08cc1dbfb51e47c8b138e3a'
             OR replacement.canonical_request_manifest_sha256<>
                '04835164d5c2abe633efd1a8ddc58edcc7c9d5e8347c01425df5049d9b74b427'
             OR market_sha256(replacement.payload->'requests')<>
                '04835164d5c2abe633efd1a8ddc58edcc7c9d5e8347c01425df5049d9b74b427'
             OR market_sha256(replacement.canonical_request_manifest)<>
                '04835164d5c2abe633efd1a8ddc58edcc7c9d5e8347c01425df5049d9b74b427'
             OR superseded.payload->>'discovery_contract' IS DISTINCT FROM
                replacement.payload->>'discovery_contract'
             OR superseded.source_id<>replacement.source_id
             OR superseded.purpose<>replacement.purpose
             OR superseded.environment<>replacement.environment
             OR superseded.phase1_spec_hash<>replacement.phase1_spec_hash
             OR superseded.phase1_manifest_hash<>replacement.phase1_manifest_hash
             OR superseded.superseded_data_identity<>replacement.superseded_data_identity
             OR lineage.plan_id<>superseded.id OR lineage.status<>'failed'
             OR lineage.logical_key<>
                'c8e22e7d02432f7022094152182d39eec6571cdf98700f9272735e52fdf8b827'
             OR lineage.canonical_request_sha256<>
                'beb847b0404bb9facf37ec5354b7bbdfa22335a17d7f9abdcb4178bdf0e8494d'
             OR lineage.attempt_number<>1
             OR lineage.idempotency_key<>'historical-discovery-attempt:'
                ||'c8e22e7d02432f7022094152182d39eec6571cdf98700f9272735e52fdf8b827:1'
             OR lineage.failure_reason<>'DISCOVERY_PROVIDER_HTTP_ERROR'
             OR audit_count<>1 OR audit_hash<>lineage.terminal_event_sha256
             OR EXISTS(SELECT 1 FROM market_historicaldiscoveryattempt a
                JOIN market_historicaldiscoverychunk c ON c.id=a.chunk_id
                JOIN market_ingestionrun r ON r.id=a.ingestion_run_id
                WHERE c.plan_id=superseded.id AND r.status='running')
             OR EXISTS(SELECT 1 FROM market_historicaldiscoveryattempt a
                JOIN market_historicaldiscoverychunk c ON c.id=a.chunk_id
                WHERE c.plan_id=replacement.id)
             OR replacement.version='phase-2b1r-discovery-v2' AND invalid_v2_layout
             OR NEW.reason_code<>'PROVIDER_REQUEST_BOUND_UNSAFE'
             OR NEW.superseded_plan_sha256<>superseded.sha256
             OR NEW.replacement_plan_sha256<>replacement.sha256
             OR NEW.governing_terminal_event_sha256<>lineage.terminal_event_sha256
             OR NEW.governing_operational_evidence_sha256<>
                lineage.operational_evidence_sha256
             OR NEW.payload IS DISTINCT FROM expected_payload
             OR NEW.sha256<>market_sha256(expected_payload)
          THEN RAISE EXCEPTION 'discovery supersession lineage is invalid'; END IF;
          RETURN NEW;
        END $$ LANGUAGE plpgsql;

        CREATE FUNCTION market_reject_superseded_discovery_write() RETURNS trigger AS $$
        DECLARE plan_key bigint;
        BEGIN
          IF TG_TABLE_NAME='market_historicaldiscoveryplan' THEN
            plan_key:=NEW.id;
          ELSIF TG_TABLE_NAME='market_historicaldiscoverychunk' THEN
            plan_key:=NEW.plan_id;
          ELSIF TG_TABLE_NAME='market_historicaldiscoveryattempt' THEN
            SELECT plan_id INTO STRICT plan_key FROM market_historicaldiscoverychunk
              WHERE id=NEW.chunk_id;
          ELSE
            plan_key:=NEW.plan_id;
          END IF;
          PERFORM market_discovery_plan_xact_lock(plan_key);
          IF EXISTS(SELECT 1 FROM market_historicaldiscoverysupersession
                    WHERE superseded_plan_id=plan_key)
          THEN RAISE EXCEPTION 'superseded discovery plans reject new writes'; END IF;
          IF TG_TABLE_NAME='market_historicaldiscoveryattempt'
             AND EXISTS(SELECT 1 FROM market_historicaldiscoverysupersession
                        WHERE replacement_plan_id=plan_key)
          THEN RAISE EXCEPTION
            'supersession replacement plans reject attempts until governed activation';
          END IF;
          RETURN NEW;
        END $$ LANGUAGE plpgsql;

        CREATE FUNCTION market_discovery_supersession_reject_mutation() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'historical discovery supersession is append-only';
        END $$ LANGUAGE plpgsql;

        CREATE FUNCTION market_discovery_supersession_reject_truncate() RETURNS trigger AS $$
        BEGIN
          IF current_database() LIKE 'test\_%%' ESCAPE '\'
             AND EXISTS(SELECT 1 FROM pg_locks locks
               WHERE locks.pid=pg_backend_pid() AND locks.granted
                 AND locks.mode='AccessExclusiveLock'
                 AND locks.relation='auth_permission'::regclass)
          THEN RETURN NULL; END IF;
          RAISE EXCEPTION 'historical discovery supersession cannot be truncated';
        END $$ LANGUAGE plpgsql;

        CREATE TRIGGER market_discovery_supersession_validate BEFORE INSERT
          ON market_historicaldiscoverysupersession FOR EACH ROW
          EXECUTE FUNCTION market_validate_discovery_supersession();
        CREATE TRIGGER market_discovery_supersession_immutable BEFORE UPDATE OR DELETE
          ON market_historicaldiscoverysupersession FOR EACH ROW
          EXECUTE FUNCTION market_discovery_supersession_reject_mutation();
        CREATE TRIGGER market_discovery_supersession_no_truncate BEFORE TRUNCATE
          ON market_historicaldiscoverysupersession FOR EACH STATEMENT
          EXECUTE FUNCTION market_discovery_supersession_reject_truncate();
        CREATE TRIGGER market_discovery_00_superseded_plan BEFORE UPDATE
          ON market_historicaldiscoveryplan FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_chunk BEFORE INSERT
          ON market_historicaldiscoverychunk FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_attempt BEFORE INSERT
          ON market_historicaldiscoveryattempt FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_approval BEFORE INSERT
          ON market_historicaldiscoveryapproval FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_registration BEFORE INSERT
          ON market_historicaldiscoveryregistration FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        """
    )


def remove_supersession_governance(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    Supersession = apps.get_model("market", "HistoricalDiscoverySupersession")
    if Supersession.objects.exists():
        raise RuntimeError(
            "historical discovery supersession evidence prohibits migration reversal"
        )
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_registration "
        "ON market_historicaldiscoveryregistration;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_approval "
        "ON market_historicaldiscoveryapproval;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_attempt "
        "ON market_historicaldiscoveryattempt;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_chunk "
        "ON market_historicaldiscoverychunk;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_plan "
        "ON market_historicaldiscoveryplan;"
        "DROP TRIGGER IF EXISTS market_discovery_supersession_no_truncate "
        "ON market_historicaldiscoverysupersession;"
        "DROP TRIGGER IF EXISTS market_discovery_supersession_immutable "
        "ON market_historicaldiscoverysupersession;"
        "DROP TRIGGER IF EXISTS market_discovery_supersession_validate "
        "ON market_historicaldiscoverysupersession;"
        "DROP FUNCTION IF EXISTS market_discovery_supersession_reject_truncate();"
        "DROP FUNCTION IF EXISTS market_discovery_supersession_reject_mutation();"
        "DROP FUNCTION IF EXISTS market_reject_superseded_discovery_write();"
        "DROP FUNCTION IF EXISTS market_validate_discovery_supersession();"
        "DROP FUNCTION IF EXISTS market_discovery_plan_xact_lock(bigint);"
    )


class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ("market", "0013_provider_observed_inventory"),
    ]

    operations = [
        migrations.RunPython(preflight_supersession_governance, migrations.RunPython.noop),
        migrations.CreateModel(
            name="HistoricalDiscoverySupersession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason_code", models.CharField(max_length=80)),
                ("superseded_plan_sha256", models.CharField(max_length=64)),
                ("replacement_plan_sha256", models.CharField(max_length=64)),
                ("governing_terminal_event_sha256", models.CharField(max_length=64)),
                ("governing_operational_evidence_sha256", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "governing_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governing_supersession",
                        to="market.historicaldiscoveryattempt",
                    ),
                ),
                (
                    "replacement_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_for",
                        to="market.historicaldiscoveryplan",
                    ),
                ),
                (
                    "superseded_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersession",
                        to="market.historicaldiscoveryplan",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("superseded_plan", models.F("replacement_plan")), _negated=True
                        ),
                        name="historical_discovery_supersession_distinct_plans",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason_code", "PROVIDER_REQUEST_BOUND_UNSAFE")),
                        name="historical_discovery_supersession_reason",
                    ),
                ],
            },
        ),
        migrations.RunPython(install_supersession_governance, remove_supersession_governance),
    ]
