# Generated by Django 5.2.17 on 2026-08-30 00:26

import django.db.models.deletion
from django.db import migrations, models


def install_supersession_governance(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        r"""
        CREATE FUNCTION market_validate_discovery_supersession() RETURNS trigger AS $$
        DECLARE superseded record; replacement record; lineage record;
                superseded_version integer; replacement_version integer;
                audit_count integer; audit_hash text; expected_payload jsonb;
                cycle_exists boolean; invalid_v2_layout boolean;
        BEGIN
          SELECT * INTO STRICT superseded FROM market_historicaldiscoveryplan
            WHERE id=NEW.superseded_plan_id;
          SELECT * INTO STRICT replacement FROM market_historicaldiscoveryplan
            WHERE id=NEW.replacement_plan_id;
          SELECT a.id,a.idempotency_key,c.plan_id,r.request_manifest_hash,r.status,
                 r.failure_reason,e.terminal_event_sha256,e.operational_evidence_sha256
            INTO STRICT lineage FROM market_historicaldiscoveryattempt a
            JOIN market_historicaldiscoverychunk c ON c.id=a.chunk_id
            JOIN market_ingestionrun r ON r.id=a.ingestion_run_id
            JOIN market_historicaldiscoveryproviderevidence e ON e.attempt_id=a.id
            WHERE a.id=NEW.governing_attempt_id;
          SELECT count(*),min(audit.payload->>'event_sha256') INTO audit_count,audit_hash
            FROM market_auditevent audit
            WHERE audit.subject_type='HistoricalDiscoveryAttempt'
              AND audit.subject_id=NEW.governing_attempt_id::text
              AND audit.event_type='market.historical_discovery_failed';
          superseded_version := substring(superseded.version from 'v([1-9][0-9]*)$')::integer;
          replacement_version := substring(replacement.version from 'v([1-9][0-9]*)$')::integer;
          WITH RECURSIVE lineage_path(plan_id) AS (
            SELECT NEW.replacement_plan_id
            UNION
            SELECT s.replacement_plan_id
              FROM market_historicaldiscoverysupersession s
              JOIN lineage_path path ON s.superseded_plan_id=path.plan_id
          ) SELECT EXISTS(SELECT 1 FROM lineage_path
                           WHERE plan_id=NEW.superseded_plan_id) INTO cycle_exists;
          expected_payload := jsonb_build_object(
            'identity','historical-discovery-supersession-v1',
            'reason_code','PROVIDER_REQUEST_BOUND_UNSAFE',
            'superseded_plan_sha256',superseded.sha256,
            'superseded_request_manifest_sha256',
              superseded.canonical_request_manifest_sha256,
            'replacement_plan_sha256',replacement.sha256,
            'replacement_request_manifest_sha256',
              replacement.canonical_request_manifest_sha256,
            'governing_attempt_idempotency_key',lineage.idempotency_key,
            'governing_run_request_manifest_hash',lineage.request_manifest_hash,
            'governing_failure_code',lineage.failure_reason,
            'governing_terminal_event_sha256',lineage.terminal_event_sha256,
            'governing_operational_evidence_sha256',lineage.operational_evidence_sha256,
            'governing_audit_event_sha256',audit_hash);

          invalid_v2_layout := false;
          IF replacement.version='phase-2b1r-discovery-v2' THEN
            invalid_v2_layout :=
              replacement.identity<>'failed-break-phase-2b1r-discovery-plan-v2'
              OR replacement.declared_chunk_count<>132
              OR (SELECT count(*) FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='D')<>6
              OR (SELECT count(*) FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='H1')<>120
              OR (SELECT count(*) FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='W')<>6
              OR EXISTS(SELECT 1 FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='H1'
                    AND c.requested_to-c.requested_from>interval '4000 hours')
              OR EXISTS(
                SELECT 1 FROM (
                  SELECT c.instrument_id,c.requested_from,c.requested_to,
                         lag(c.requested_to) OVER (
                           PARTITION BY c.instrument_id ORDER BY c.requested_from) AS prior_to,
                         row_number() OVER (
                           PARTITION BY c.instrument_id ORDER BY c.requested_from) AS position,
                         count(*) OVER (PARTITION BY c.instrument_id) AS series_count
                    FROM market_historicaldiscoverychunk c
                    WHERE c.plan_id=replacement.id AND c.granularity='H1'
                ) ordered
                WHERE ordered.series_count<>20
                   OR (ordered.position=1 AND ordered.requested_from<>
                       timestamptz '2009-12-31 15:00:00+00')
                   OR (ordered.position>1 AND ordered.requested_from<>ordered.prior_to)
                   OR (ordered.position=ordered.series_count AND ordered.requested_to<>
                       timestamptz '2019-01-01 04:00:00+00'))
              OR EXISTS(
                SELECT 1 FROM market_instrument i
                WHERE i.code IN ('AUD_USD','EUR_GBP','EUR_USD','GBP_USD','USD_CAD','USD_JPY')
                  AND (SELECT count(*) FROM market_historicaldiscoverychunk c
                       WHERE c.plan_id=replacement.id AND c.instrument_id=i.id
                         AND c.granularity='D'
                         AND c.requested_from=timestamptz '2009-02-26 22:00:00+00'
                         AND c.requested_to=timestamptz '2018-12-31 22:00:00+00')<>1)
              OR EXISTS(
                SELECT 1 FROM market_instrument i
                WHERE i.code IN ('AUD_USD','EUR_GBP','EUR_USD','GBP_USD','USD_CAD','USD_JPY')
                  AND (SELECT count(*) FROM market_historicaldiscoverychunk c
                       WHERE c.plan_id=replacement.id AND c.instrument_id=i.id
                         AND c.granularity='W'
                         AND c.requested_from=timestamptz '2009-12-18 22:00:00+00'
                         AND c.requested_to=timestamptz '2018-12-28 22:00:00+00')<>1);
          END IF;

          IF NEW.superseded_plan_id=NEW.replacement_plan_id OR cycle_exists
             OR superseded_version IS NULL OR replacement_version IS NULL
             OR replacement_version<=superseded_version
             OR superseded.sealed_at IS NOT NULL OR replacement.sealed_at IS NOT NULL
             OR superseded.payload->>'discovery_contract' IS DISTINCT FROM
                replacement.payload->>'discovery_contract'
             OR superseded.source_id<>replacement.source_id
             OR superseded.purpose<>replacement.purpose
             OR superseded.environment<>replacement.environment
             OR superseded.phase1_spec_hash<>replacement.phase1_spec_hash
             OR superseded.phase1_manifest_hash<>replacement.phase1_manifest_hash
             OR superseded.superseded_data_identity<>replacement.superseded_data_identity
             OR lineage.plan_id<>superseded.id OR lineage.status<>'failed'
             OR lineage.failure_reason NOT IN
                ('DISCOVERY_PROVIDER_HTTP_ERROR','DISCOVERY_PROVIDER_LIMIT_SUSPECTED')
             OR audit_count<>1 OR audit_hash<>lineage.terminal_event_sha256
             OR EXISTS(SELECT 1 FROM market_historicaldiscoveryattempt a
                JOIN market_historicaldiscoverychunk c ON c.id=a.chunk_id
                JOIN market_ingestionrun r ON r.id=a.ingestion_run_id
                WHERE c.plan_id=superseded.id AND r.status='running')
             OR EXISTS(SELECT 1 FROM market_historicaldiscoveryattempt a
                JOIN market_historicaldiscoverychunk c ON c.id=a.chunk_id
                WHERE c.plan_id=replacement.id)
             OR replacement.version='phase-2b1r-discovery-v2' AND invalid_v2_layout
             OR NEW.reason_code<>'PROVIDER_REQUEST_BOUND_UNSAFE'
             OR NEW.superseded_plan_sha256<>superseded.sha256
             OR NEW.replacement_plan_sha256<>replacement.sha256
             OR NEW.governing_terminal_event_sha256<>lineage.terminal_event_sha256
             OR NEW.governing_operational_evidence_sha256<>
                lineage.operational_evidence_sha256
             OR NEW.payload IS DISTINCT FROM expected_payload
             OR NEW.sha256<>market_sha256(expected_payload)
          THEN RAISE EXCEPTION 'discovery supersession lineage is invalid'; END IF;
          RETURN NEW;
        END $$ LANGUAGE plpgsql;

        CREATE FUNCTION market_reject_superseded_discovery_write() RETURNS trigger AS $$
        DECLARE plan_key bigint;
        BEGIN
          IF TG_TABLE_NAME='market_historicaldiscoveryplan' THEN
            plan_key:=NEW.id;
          ELSIF TG_TABLE_NAME='market_historicaldiscoverychunk' THEN
            plan_key:=NEW.plan_id;
          ELSIF TG_TABLE_NAME='market_historicaldiscoveryattempt' THEN
            SELECT plan_id INTO STRICT plan_key FROM market_historicaldiscoverychunk
              WHERE id=NEW.chunk_id;
          ELSE
            plan_key:=NEW.plan_id;
          END IF;
          IF EXISTS(SELECT 1 FROM market_historicaldiscoverysupersession
                    WHERE superseded_plan_id=plan_key)
          THEN RAISE EXCEPTION 'superseded discovery plans reject new writes'; END IF;
          RETURN NEW;
        END $$ LANGUAGE plpgsql;

        CREATE FUNCTION market_discovery_supersession_reject_mutation() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'historical discovery supersession is append-only';
        END $$ LANGUAGE plpgsql;

        CREATE FUNCTION market_discovery_supersession_reject_truncate() RETURNS trigger AS $$
        BEGIN
          IF current_database() LIKE 'test\_%%' ESCAPE '\'
             AND EXISTS(SELECT 1 FROM pg_locks locks
               WHERE locks.pid=pg_backend_pid() AND locks.granted
                 AND locks.mode='AccessExclusiveLock'
                 AND locks.relation='auth_permission'::regclass)
          THEN RETURN NULL; END IF;
          RAISE EXCEPTION 'historical discovery supersession cannot be truncated';
        END $$ LANGUAGE plpgsql;

        CREATE TRIGGER market_discovery_supersession_validate BEFORE INSERT
          ON market_historicaldiscoverysupersession FOR EACH ROW
          EXECUTE FUNCTION market_validate_discovery_supersession();
        CREATE TRIGGER market_discovery_supersession_immutable BEFORE UPDATE OR DELETE
          ON market_historicaldiscoverysupersession FOR EACH ROW
          EXECUTE FUNCTION market_discovery_supersession_reject_mutation();
        CREATE TRIGGER market_discovery_supersession_no_truncate BEFORE TRUNCATE
          ON market_historicaldiscoverysupersession FOR EACH STATEMENT
          EXECUTE FUNCTION market_discovery_supersession_reject_truncate();
        CREATE TRIGGER market_discovery_00_superseded_plan BEFORE UPDATE
          ON market_historicaldiscoveryplan FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_chunk BEFORE INSERT
          ON market_historicaldiscoverychunk FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_attempt BEFORE INSERT
          ON market_historicaldiscoveryattempt FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_approval BEFORE INSERT
          ON market_historicaldiscoveryapproval FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_registration BEFORE INSERT
          ON market_historicaldiscoveryregistration FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        """
    )


def remove_supersession_governance(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    Supersession = apps.get_model("market", "HistoricalDiscoverySupersession")
    if Supersession.objects.exists():
        raise RuntimeError(
            "historical discovery supersession evidence prohibits migration reversal"
        )
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_registration "
        "ON market_historicaldiscoveryregistration;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_approval "
        "ON market_historicaldiscoveryapproval;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_attempt "
        "ON market_historicaldiscoveryattempt;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_chunk "
        "ON market_historicaldiscoverychunk;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_plan "
        "ON market_historicaldiscoveryplan;"
        "DROP TRIGGER IF EXISTS market_discovery_supersession_no_truncate "
        "ON market_historicaldiscoverysupersession;"
        "DROP TRIGGER IF EXISTS market_discovery_supersession_immutable "
        "ON market_historicaldiscoverysupersession;"
        "DROP TRIGGER IF EXISTS market_discovery_supersession_validate "
        "ON market_historicaldiscoverysupersession;"
        "DROP FUNCTION IF EXISTS market_discovery_supersession_reject_truncate();"
        "DROP FUNCTION IF EXISTS market_discovery_supersession_reject_mutation();"
        "DROP FUNCTION IF EXISTS market_reject_superseded_discovery_write();"
        "DROP FUNCTION IF EXISTS market_validate_discovery_supersession();"
    )


class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ("market", "0013_provider_observed_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDiscoverySupersession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason_code", models.CharField(max_length=80)),
                ("superseded_plan_sha256", models.CharField(max_length=64)),
                ("replacement_plan_sha256", models.CharField(max_length=64)),
                ("governing_terminal_event_sha256", models.CharField(max_length=64)),
                ("governing_operational_evidence_sha256", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "governing_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governing_supersession",
                        to="market.historicaldiscoveryattempt",
                    ),
                ),
                (
                    "replacement_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_for",
                        to="market.historicaldiscoveryplan",
                    ),
                ),
                (
                    "superseded_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersession",
                        to="market.historicaldiscoveryplan",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("superseded_plan", models.F("replacement_plan")), _negated=True
                        ),
                        name="historical_discovery_supersession_distinct_plans",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason_code", "PROVIDER_REQUEST_BOUND_UNSAFE")),
                        name="historical_discovery_supersession_reason",
                    ),
                ],
            },
        ),
        migrations.RunPython(install_supersession_governance, remove_supersession_governance),
    ]
