# Generated by Django 5.2.17 on 2026-08-30 00:26

import django.db.models.deletion
from django.db import migrations, models

PREFLIGHT_TABLES = (
    "market_historicaldiscoveryplan",
    "market_historicaldiscoverychunk",
    "market_historicaldiscoveryattempt",
    "market_historicaldiscoveryproviderevidence",
    "market_historicaldiscoveryapproval",
    "market_historicaldiscoveryregistration",
    "market_historicaltimestampinventory",
    "market_historicaltimestampobservation",
    "market_auditevent",
    "market_ingestionrun",
    "market_instrument",
    "market_sourceregistry",
)
# md5(pg_proc.prosrc) of every governance function migration 0014 depends on,
# captured from a catalog migrated exactly through 0013. prosrc stores the
# dollar-quoted body verbatim, so these values are PostgreSQL-version stable.
PREFLIGHT_FUNCTIONS = {
    "market_canonical_json": "e24510e2dd5b5465b0ae07aa8a90d985",
    "market_discovery_audit_reject_mutation": "f0f3c960291b7dcfaf465056dc3894a7",
    "market_discovery_audit_reject_truncate": "94f9fc7f4dcc59e4b1414a8562c572b9",
    "market_discovery_operational_timestamp": "b961d332514ab6d49cf01a3c6bb82d58",
    "market_discovery_reject_mutation": "c1787d7ad1f6dbb0d7cef179663e5343",
    "market_discovery_reject_sealed_insert": "fedf6a4051801406242b8796ac67aa70",
    "market_discovery_reject_truncate": "42b64f019071b3935e618060c9b8f38e",
    "market_discovery_timestamp": "f50e7d405e5aafa58e498726dc002532",
    "market_sha256": "3a88ffe577d4388b0617670064ec84f2",
    "market_validate_discovery_attempt": "da6b5b5e376f827a239afae9e5426875",
    "market_validate_discovery_audit_insert": "3db14cc7ffbab0ccdf574b77eddc57db",
    "market_validate_discovery_chunk": "18f0003f52549ef2b94fcb28556f8cca",
    "market_validate_discovery_inventory_deferred": "47ee0ece0931d64856ff121a56ea0c5a",
    "market_validate_discovery_observation": "fe53baf1d0ea8851f27ee0f42f1c234b",
    "market_validate_discovery_plan": "e3f9d1be649fb5268160b57d381e7cbc",
    "market_validate_discovery_provider_evidence": "10f68501a5e6d96d38298691d483e666",
    "market_validate_discovery_seal_deferred": "1b89e8783beadd304bbe26bb2f3225a8",
    "market_validate_discovery_terminal_run": "30838c76d6cdc00a1e15cb200d1f756c",
}
PREFLIGHT_TRIGGERS = (
    ("market_discovery_plan_validate", "market_historicaldiscoveryplan"),
    ("market_discovery_chunk_validate", "market_historicaldiscoverychunk"),
    ("market_discovery_attempt_validate", "market_historicaldiscoveryattempt"),
    ("market_discovery_observation_validate", "market_historicaltimestampobservation"),
    ("market_discovery_provider_unsealed", "market_historicaldiscoveryproviderevidence"),
    ("market_discovery_provider_validate", "market_historicaldiscoveryproviderevidence"),
    ("market_discovery_inventory_unsealed", "market_historicaltimestampinventory"),
    ("market_discovery_inventory_reconstruct", "market_historicaltimestampinventory"),
    ("market_discovery_audit_validate", "market_auditevent"),
    ("market_discovery_audit_immutable", "market_auditevent"),
    ("market_discovery_audit_no_truncate", "market_auditevent"),
    ("market_discovery_run_terminal", "market_ingestionrun"),
    ("market_discovery_approval_atomic", "market_historicaldiscoveryapproval"),
    ("market_discovery_registration_atomic", "market_historicaldiscoveryregistration"),
    ("market_discovery_plan_seal_atomic", "market_historicaldiscoveryplan"),
    (
        "market_historicaldiscoveryregistration_append_only",
        "market_historicaldiscoveryregistration",
    ),
    ("market_historicaldiscoveryapproval_append_only", "market_historicaldiscoveryapproval"),
    (
        "market_historicaldiscoveryproviderevidence_append_only",
        "market_historicaldiscoveryproviderevidence",
    ),
    (
        "market_historicaltimestampobservation_append_only",
        "market_historicaltimestampobservation",
    ),
    ("market_historicaltimestampinventory_append_only", "market_historicaltimestampinventory"),
    ("market_historicaldiscoveryattempt_append_only", "market_historicaldiscoveryattempt"),
    ("market_historicaldiscoverychunk_append_only", "market_historicaldiscoverychunk"),
    (
        "market_historicaldiscoveryregistration_reject_truncate",
        "market_historicaldiscoveryregistration",
    ),
    ("market_historicaldiscoveryapproval_reject_truncate", "market_historicaldiscoveryapproval"),
    (
        "market_historicaldiscoveryproviderevidence_reject_truncate",
        "market_historicaldiscoveryproviderevidence",
    ),
    (
        "market_historicaltimestampobservation_reject_truncate",
        "market_historicaltimestampobservation",
    ),
    (
        "market_historicaltimestampinventory_reject_truncate",
        "market_historicaltimestampinventory",
    ),
    ("market_historicaldiscoveryattempt_reject_truncate", "market_historicaldiscoveryattempt"),
    ("market_historicaldiscoverychunk_reject_truncate", "market_historicaldiscoverychunk"),
    ("market_historicaldiscoveryplan_reject_truncate", "market_historicaldiscoveryplan"),
)
SUPERSESSION_TABLE = "market_historicaldiscoverysupersession"
SUPERSESSION_FUNCTIONS = (
    "market_discovery_plan_xact_lock",
    "market_validate_discovery_supersession",
    "market_reject_superseded_discovery_write",
    "market_discovery_supersession_reject_mutation",
    "market_discovery_supersession_reject_truncate",
)
SUPERSESSION_TRIGGERS = (
    "market_discovery_supersession_validate",
    "market_discovery_supersession_immutable",
    "market_discovery_supersession_no_truncate",
    "market_discovery_00_superseded_plan",
    "market_discovery_00_superseded_chunk",
    "market_discovery_00_superseded_attempt",
    "market_discovery_00_superseded_approval",
    "market_discovery_00_superseded_registration",
)


def preflight_supersession_governance(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    problems = []
    with schema_editor.connection.cursor() as cursor:
        for table in PREFLIGHT_TABLES:
            cursor.execute("SELECT to_regclass(%s)", [table])
            if cursor.fetchone()[0] is None:
                problems.append(f"required table {table} is missing")
        cursor.execute(
            """SELECT p.proname, md5(p.prosrc) FROM pg_proc p
               JOIN pg_namespace n ON n.oid = p.pronamespace
               WHERE n.nspname = current_schema() AND p.proname = ANY(%s)""",
            [list(PREFLIGHT_FUNCTIONS)],
        )
        found = dict(cursor.fetchall())
        for name, expected in sorted(PREFLIGHT_FUNCTIONS.items()):
            if name not in found:
                problems.append(f"required function {name} is missing")
            elif found[name] != expected:
                problems.append(f"required function {name} does not match its 0013 definition")
        cursor.execute(
            """SELECT t.tgname, c.relname FROM pg_trigger t
               JOIN pg_class c ON c.oid = t.tgrelid WHERE NOT t.tgisinternal"""
        )
        triggers = set(cursor.fetchall())
        trigger_names = {name for name, _ in triggers}
        for name, table in PREFLIGHT_TRIGGERS:
            if (name, table) not in triggers:
                problems.append(f"required trigger {name} on {table} is missing")
        cursor.execute("SELECT to_regclass(%s)", [SUPERSESSION_TABLE])
        if cursor.fetchone()[0] is not None:
            problems.append(f"unexpected pre-existing table {SUPERSESSION_TABLE}")
        cursor.execute(
            """SELECT p.proname FROM pg_proc p
               JOIN pg_namespace n ON n.oid = p.pronamespace
               WHERE n.nspname = current_schema() AND p.proname = ANY(%s)""",
            [list(SUPERSESSION_FUNCTIONS)],
        )
        for (name,) in cursor.fetchall():
            problems.append(f"unexpected pre-existing supersession function {name}")
        for name in SUPERSESSION_TRIGGERS:
            if name in trigger_names:
                problems.append(f"unexpected pre-existing supersession trigger {name}")
    if problems:
        raise RuntimeError(
            "migration 0014 preflight rejected the current catalog: " + "; ".join(problems)
        )


def install_supersession_governance(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        r"""
        CREATE FUNCTION market_discovery_plan_xact_lock(plan_key bigint) RETURNS void AS $$
          SELECT pg_advisory_xact_lock(
            hashtextextended('market-discovery-plan-governance:'||plan_key::text, 4225531));
        $$ LANGUAGE sql;

        CREATE FUNCTION market_validate_discovery_supersession() RETURNS trigger AS $$
        DECLARE superseded record; replacement record; lineage record;
                superseded_version integer; replacement_version integer;
                audit_count integer; audit_hash text; expected_payload jsonb;
                cycle_exists boolean; invalid_v2_layout boolean;
        BEGIN
          PERFORM market_discovery_plan_xact_lock(
            LEAST(NEW.superseded_plan_id, NEW.replacement_plan_id));
          PERFORM market_discovery_plan_xact_lock(
            GREATEST(NEW.superseded_plan_id, NEW.replacement_plan_id));
          SELECT * INTO STRICT superseded FROM market_historicaldiscoveryplan
            WHERE id=NEW.superseded_plan_id;
          SELECT * INTO STRICT replacement FROM market_historicaldiscoveryplan
            WHERE id=NEW.replacement_plan_id;
          SELECT a.id,a.attempt_number,a.idempotency_key,c.plan_id,c.logical_key,
                 c.canonical_request_sha256,r.request_manifest_hash,r.status,
                 r.failure_reason,e.terminal_event_sha256,e.operational_evidence_sha256
            INTO STRICT lineage FROM market_historicaldiscoveryattempt a
            JOIN market_historicaldiscoverychunk c ON c.id=a.chunk_id
            JOIN market_ingestionrun r ON r.id=a.ingestion_run_id
            JOIN market_historicaldiscoveryproviderevidence e ON e.attempt_id=a.id
            WHERE a.id=NEW.governing_attempt_id;
          SELECT count(*),min(audit.payload->>'event_sha256') INTO audit_count,audit_hash
            FROM market_auditevent audit
            WHERE audit.subject_type='HistoricalDiscoveryAttempt'
              AND audit.subject_id=NEW.governing_attempt_id::text
              AND audit.event_type='market.historical_discovery_failed';
          superseded_version := substring(superseded.version from 'v([1-9][0-9]*)$')::integer;
          replacement_version := substring(replacement.version from 'v([1-9][0-9]*)$')::integer;
          WITH RECURSIVE lineage_path(plan_id) AS (
            SELECT NEW.replacement_plan_id
            UNION
            SELECT s.replacement_plan_id
              FROM market_historicaldiscoverysupersession s
              JOIN lineage_path path ON s.superseded_plan_id=path.plan_id
          ) SELECT EXISTS(SELECT 1 FROM lineage_path
                           WHERE plan_id=NEW.superseded_plan_id) INTO cycle_exists;
          expected_payload := jsonb_build_object(
            'identity','historical-discovery-supersession-v1',
            'reason_code','PROVIDER_REQUEST_BOUND_UNSAFE',
            'superseded_plan_sha256',superseded.sha256,
            'superseded_request_manifest_sha256',
              superseded.canonical_request_manifest_sha256,
            'replacement_plan_sha256',replacement.sha256,
            'replacement_request_manifest_sha256',
              replacement.canonical_request_manifest_sha256,
            'governing_attempt_idempotency_key',lineage.idempotency_key,
            'governing_run_request_manifest_hash',lineage.request_manifest_hash,
            'governing_failure_code',lineage.failure_reason,
            'governing_terminal_event_sha256',lineage.terminal_event_sha256,
            'governing_operational_evidence_sha256',lineage.operational_evidence_sha256,
            'governing_audit_event_sha256',audit_hash);

          invalid_v2_layout := false;
          IF replacement.version='phase-2b1r-discovery-v2' THEN
            invalid_v2_layout :=
              replacement.identity<>'failed-break-phase-2b1r-discovery-plan-v2'
              OR replacement.declared_chunk_count<>132
              OR (SELECT count(*) FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='D')<>6
              OR (SELECT count(*) FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='H1')<>120
              OR (SELECT count(*) FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='W')<>6
              OR EXISTS(SELECT 1 FROM market_historicaldiscoverychunk c
                  WHERE c.plan_id=replacement.id AND c.granularity='H1'
                    AND c.requested_to-c.requested_from>interval '4000 hours')
              OR EXISTS(
                SELECT 1 FROM (
                  SELECT c.instrument_id,c.requested_from,c.requested_to,
                         lag(c.requested_to) OVER (
                           PARTITION BY c.instrument_id ORDER BY c.requested_from) AS prior_to,
                         row_number() OVER (
                           PARTITION BY c.instrument_id ORDER BY c.requested_from) AS position,
                         count(*) OVER (PARTITION BY c.instrument_id) AS series_count
                    FROM market_historicaldiscoverychunk c
                    WHERE c.plan_id=replacement.id AND c.granularity='H1'
                ) ordered
                WHERE ordered.series_count<>20
                   OR (ordered.position=1 AND ordered.requested_from<>
                       timestamptz '2009-12-31 15:00:00+00')
                   OR (ordered.position>1 AND ordered.requested_from<>ordered.prior_to)
                   OR (ordered.position=ordered.series_count AND ordered.requested_to<>
                       timestamptz '2019-01-01 04:00:00+00'))
              OR EXISTS(
                SELECT 1 FROM market_instrument i
                WHERE i.code IN ('AUD_USD','EUR_GBP','EUR_USD','GBP_USD','USD_CAD','USD_JPY')
                  AND (SELECT count(*) FROM market_historicaldiscoverychunk c
                       WHERE c.plan_id=replacement.id AND c.instrument_id=i.id
                         AND c.granularity='D'
                         AND c.requested_from=timestamptz '2009-02-26 22:00:00+00'
                         AND c.requested_to=timestamptz '2018-12-31 22:00:00+00')<>1)
              OR EXISTS(
                SELECT 1 FROM market_instrument i
                WHERE i.code IN ('AUD_USD','EUR_GBP','EUR_USD','GBP_USD','USD_CAD','USD_JPY')
                  AND (SELECT count(*) FROM market_historicaldiscoverychunk c
                       WHERE c.plan_id=replacement.id AND c.instrument_id=i.id
                         AND c.granularity='W'
                         AND c.requested_from=timestamptz '2009-12-18 22:00:00+00'
                         AND c.requested_to=timestamptz '2018-12-28 22:00:00+00')<>1);
          END IF;

          IF NEW.superseded_plan_id=NEW.replacement_plan_id OR cycle_exists
             OR superseded_version IS NULL OR replacement_version IS NULL
             OR replacement_version<=superseded_version
             OR superseded.sealed_at IS NOT NULL OR replacement.sealed_at IS NOT NULL
             OR superseded.version<>'phase-2b1r-discovery-v1'
             OR superseded.identity<>'failed-break-phase-2b1r-discovery-plan-v1'
             OR superseded.sha256<>
                '292556a591024876c7051212d1c6886cd026a097e141295e9b60257fc5402b33'
             OR market_sha256(superseded.payload)<>
                '292556a591024876c7051212d1c6886cd026a097e141295e9b60257fc5402b33'
             OR superseded.canonical_request_manifest_sha256<>
                'a3cf7ef1f484d2379bfd1ef94769216b2ed9b41635cad7cadbd71a8de251bb2e'
             OR market_sha256(superseded.payload->'requests')<>
                'a3cf7ef1f484d2379bfd1ef94769216b2ed9b41635cad7cadbd71a8de251bb2e'
             OR market_sha256(superseded.canonical_request_manifest)<>
                'a3cf7ef1f484d2379bfd1ef94769216b2ed9b41635cad7cadbd71a8de251bb2e'
             OR replacement.version<>'phase-2b1r-discovery-v2'
             OR replacement.identity<>'failed-break-phase-2b1r-discovery-plan-v2'
             OR replacement.sha256<>
                '2a25bbc28fca5d596b26d3d2921fa881e374174fb08cc1dbfb51e47c8b138e3a'
             OR market_sha256(replacement.payload)<>
                '2a25bbc28fca5d596b26d3d2921fa881e374174fb08cc1dbfb51e47c8b138e3a'
             OR replacement.canonical_request_manifest_sha256<>
                '04835164d5c2abe633efd1a8ddc58edcc7c9d5e8347c01425df5049d9b74b427'
             OR market_sha256(replacement.payload->'requests')<>
                '04835164d5c2abe633efd1a8ddc58edcc7c9d5e8347c01425df5049d9b74b427'
             OR market_sha256(replacement.canonical_request_manifest)<>
                '04835164d5c2abe633efd1a8ddc58edcc7c9d5e8347c01425df5049d9b74b427'
             OR superseded.payload->>'discovery_contract' IS DISTINCT FROM
                replacement.payload->>'discovery_contract'
             OR superseded.source_id<>replacement.source_id
             OR superseded.purpose<>replacement.purpose
             OR superseded.environment<>replacement.environment
             OR superseded.phase1_spec_hash<>replacement.phase1_spec_hash
             OR superseded.phase1_manifest_hash<>replacement.phase1_manifest_hash
             OR superseded.superseded_data_identity<>replacement.superseded_data_identity
             OR lineage.plan_id<>superseded.id OR lineage.status<>'failed'
             OR lineage.logical_key<>
                'c8e22e7d02432f7022094152182d39eec6571cdf98700f9272735e52fdf8b827'
             OR lineage.canonical_request_sha256<>
                'beb847b0404bb9facf37ec5354b7bbdfa22335a17d7f9abdcb4178bdf0e8494d'
             OR lineage.attempt_number<>1
             OR lineage.idempotency_key<>'historical-discovery-attempt:'
                ||'c8e22e7d02432f7022094152182d39eec6571cdf98700f9272735e52fdf8b827:1'
             OR lineage.failure_reason<>'DISCOVERY_PROVIDER_HTTP_ERROR'
             OR audit_count<>1 OR audit_hash<>lineage.terminal_event_sha256
             OR EXISTS(SELECT 1 FROM market_historicaldiscoveryattempt a
                JOIN market_historicaldiscoverychunk c ON c.id=a.chunk_id
                JOIN market_ingestionrun r ON r.id=a.ingestion_run_id
                WHERE c.plan_id=superseded.id AND r.status='running')
             OR EXISTS(SELECT 1 FROM market_historicaldiscoveryattempt a
                JOIN market_historicaldiscoverychunk c ON c.id=a.chunk_id
                WHERE c.plan_id=replacement.id)
             OR replacement.version='phase-2b1r-discovery-v2' AND invalid_v2_layout
             OR NEW.reason_code<>'PROVIDER_REQUEST_BOUND_UNSAFE'
             OR NEW.superseded_plan_sha256<>superseded.sha256
             OR NEW.replacement_plan_sha256<>replacement.sha256
             OR NEW.governing_terminal_event_sha256<>lineage.terminal_event_sha256
             OR NEW.governing_operational_evidence_sha256<>
                lineage.operational_evidence_sha256
             OR NEW.payload IS DISTINCT FROM expected_payload
             OR NEW.sha256<>market_sha256(expected_payload)
          THEN RAISE EXCEPTION 'discovery supersession lineage is invalid'; END IF;
          RETURN NEW;
        END $$ LANGUAGE plpgsql;

        CREATE FUNCTION market_reject_superseded_discovery_write() RETURNS trigger AS $$
        DECLARE plan_key bigint;
        BEGIN
          IF TG_TABLE_NAME='market_historicaldiscoveryplan' THEN
            plan_key:=NEW.id;
          ELSIF TG_TABLE_NAME='market_historicaldiscoverychunk' THEN
            plan_key:=NEW.plan_id;
          ELSIF TG_TABLE_NAME='market_historicaldiscoveryattempt' THEN
            SELECT plan_id INTO STRICT plan_key FROM market_historicaldiscoverychunk
              WHERE id=NEW.chunk_id;
          ELSE
            plan_key:=NEW.plan_id;
          END IF;
          PERFORM market_discovery_plan_xact_lock(plan_key);
          IF EXISTS(SELECT 1 FROM market_historicaldiscoverysupersession
                    WHERE superseded_plan_id=plan_key)
          THEN RAISE EXCEPTION 'superseded discovery plans reject new writes'; END IF;
          IF TG_TABLE_NAME='market_historicaldiscoveryattempt'
             AND EXISTS(SELECT 1 FROM market_historicaldiscoverysupersession
                        WHERE replacement_plan_id=plan_key)
          THEN RAISE EXCEPTION
            'supersession replacement plans reject attempts until governed activation';
          END IF;
          RETURN NEW;
        END $$ LANGUAGE plpgsql;

        CREATE FUNCTION market_discovery_supersession_reject_mutation() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'historical discovery supersession is append-only';
        END $$ LANGUAGE plpgsql;

        CREATE FUNCTION market_discovery_supersession_reject_truncate() RETURNS trigger AS $$
        BEGIN
          IF current_database() LIKE 'test\_%%' ESCAPE '\'
             AND EXISTS(SELECT 1 FROM pg_locks locks
               WHERE locks.pid=pg_backend_pid() AND locks.granted
                 AND locks.mode='AccessExclusiveLock'
                 AND locks.relation='auth_permission'::regclass)
          THEN RETURN NULL; END IF;
          RAISE EXCEPTION 'historical discovery supersession cannot be truncated';
        END $$ LANGUAGE plpgsql;

        CREATE TRIGGER market_discovery_supersession_validate BEFORE INSERT
          ON market_historicaldiscoverysupersession FOR EACH ROW
          EXECUTE FUNCTION market_validate_discovery_supersession();
        CREATE TRIGGER market_discovery_supersession_immutable BEFORE UPDATE OR DELETE
          ON market_historicaldiscoverysupersession FOR EACH ROW
          EXECUTE FUNCTION market_discovery_supersession_reject_mutation();
        CREATE TRIGGER market_discovery_supersession_no_truncate BEFORE TRUNCATE
          ON market_historicaldiscoverysupersession FOR EACH STATEMENT
          EXECUTE FUNCTION market_discovery_supersession_reject_truncate();
        CREATE TRIGGER market_discovery_00_superseded_plan BEFORE UPDATE
          ON market_historicaldiscoveryplan FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_chunk BEFORE INSERT
          ON market_historicaldiscoverychunk FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_attempt BEFORE INSERT
          ON market_historicaldiscoveryattempt FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_approval BEFORE INSERT
          ON market_historicaldiscoveryapproval FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        CREATE TRIGGER market_discovery_00_superseded_registration BEFORE INSERT
          ON market_historicaldiscoveryregistration FOR EACH ROW
          EXECUTE FUNCTION market_reject_superseded_discovery_write();
        """
    )


def remove_supersession_governance(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    Supersession = apps.get_model("market", "HistoricalDiscoverySupersession")
    if Supersession.objects.exists():
        raise RuntimeError(
            "historical discovery supersession evidence prohibits migration reversal"
        )
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_registration "
        "ON market_historicaldiscoveryregistration;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_approval "
        "ON market_historicaldiscoveryapproval;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_attempt "
        "ON market_historicaldiscoveryattempt;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_chunk "
        "ON market_historicaldiscoverychunk;"
        "DROP TRIGGER IF EXISTS market_discovery_00_superseded_plan "
        "ON market_historicaldiscoveryplan;"
        "DROP TRIGGER IF EXISTS market_discovery_supersession_no_truncate "
        "ON market_historicaldiscoverysupersession;"
        "DROP TRIGGER IF EXISTS market_discovery_supersession_immutable "
        "ON market_historicaldiscoverysupersession;"
        "DROP TRIGGER IF EXISTS market_discovery_supersession_validate "
        "ON market_historicaldiscoverysupersession;"
        "DROP FUNCTION IF EXISTS market_discovery_supersession_reject_truncate();"
        "DROP FUNCTION IF EXISTS market_discovery_supersession_reject_mutation();"
        "DROP FUNCTION IF EXISTS market_reject_superseded_discovery_write();"
        "DROP FUNCTION IF EXISTS market_validate_discovery_supersession();"
        "DROP FUNCTION IF EXISTS market_discovery_plan_xact_lock(bigint);"
    )


class Migration(migrations.Migration):
    atomic = True

    dependencies = [
        ("market", "0013_provider_observed_inventory"),
    ]

    operations = [
        migrations.RunPython(preflight_supersession_governance, migrations.RunPython.noop),
        migrations.CreateModel(
            name="HistoricalDiscoverySupersession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason_code", models.CharField(max_length=80)),
                ("superseded_plan_sha256", models.CharField(max_length=64)),
                ("replacement_plan_sha256", models.CharField(max_length=64)),
                ("governing_terminal_event_sha256", models.CharField(max_length=64)),
                ("governing_operational_evidence_sha256", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "governing_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="governing_supersession",
                        to="market.historicaldiscoveryattempt",
                    ),
                ),
                (
                    "replacement_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_for",
                        to="market.historicaldiscoveryplan",
                    ),
                ),
                (
                    "superseded_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersession",
                        to="market.historicaldiscoveryplan",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("superseded_plan", models.F("replacement_plan")), _negated=True
                        ),
                        name="historical_discovery_supersession_distinct_plans",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason_code", "PROVIDER_REQUEST_BOUND_UNSAFE")),
                        name="historical_discovery_supersession_reason",
                    ),
                ],
            },
        ),
        migrations.RunPython(install_supersession_governance, remove_supersession_governance),
    ]
