# Generated by Django 5.2.17 on 2026-09-02

from importlib import import_module

from django.db import migrations

gate8b = import_module("market.migrations.0023_gate8b_prime_successor_discovery_activation")
gate8e = import_module("market.migrations.0025_gate8e_successor_contract_materialization")

SUCCESSOR_DATA_IDENTITY = "oanda-ba-ny17-friday-provider-observed-v2"
SUCCESSOR_PLAN_SHA256 = "44dc82b2f20975e34e34e30ca7a709fff059ed14fa7457aaa26da4222d4df4cd"
SUCCESSOR_DATASET_MANIFEST_SHA256 = (
    "11da094fc7ca6a30e946be33523757d7ab559a9ad1951c9142e8969539930014"
)
SUCCESSOR_CANARY_KEY = "7b96484393a7e82eafd3bb5389dbf7f6b5b00ba6c9ed201d81814829b44a6151"

CANARY_VALIDATOR_SIGNATURE = (
    "market_validate_acquisition_canary(attempt_chunk_id bigint, new_attempt_number integer, "
    "new_idempotency_key text, new_run_id bigint)"
)
SUCCESSOR_VERIFIER_SIGNATURE = "market_verify_successor_canary_success()"
PRIOR_CANARY_PROSRC = gate8e.SUCCESSOR_CANARY_PROSRC
_OLD_CALL = "            PERFORM market_verify_replacement_canary_success();\n"
_SUCCESSOR_CALL = r"""            IF contract.identity='oanda-ba-ny17-friday-provider-observed-v2' THEN
              PERFORM market_verify_successor_canary_success();
            ELSE
              PERFORM market_verify_replacement_canary_success();
            END IF;
"""
if PRIOR_CANARY_PROSRC.count(_OLD_CALL) != 1:
    raise RuntimeError("migration 0025 canary body is not the reviewed predecessor")
GATE8G_CANARY_PROSRC = PRIOR_CANARY_PROSRC.replace(_OLD_CALL, _SUCCESSOR_CALL)

# Complete migration-0025 catalog pin.  The immutable 0022 map is reused from
# its defining migration, then every 0023-0025 addition/replacement is pinned
# to the fingerprint captured from research immediately before Gate 8G work.
REQUIRED_0025_FUNCTIONS = dict(gate8b.REQUIRED_0022_FUNCTIONS)
REQUIRED_0025_FUNCTIONS.update(
    {
        "market_validate_discovery_plan": ("", "ef91dbb8aec7b66b921bcc56b95f6e19"),
        "market_validate_discovery_attempt": ("", "7cef7f9faa2359ca875792418afea6b3"),
        "market_validate_successor_plan_complete": (
            "",
            "a2e79074c086af48c961e9be2b60c62b",
        ),
        "market_validate_gate5_registration": (
            "plan_key bigint",
            "c053c1393f5bfe0a52f118d905029789",
        ),
        "market_validate_discovery_seal_deferred": (
            "",
            "7e2c3aa21401b668112023234161ee3b",
        ),
        "market_validate_data_contract": ("", "443e4532bde701af907034d7957d0549"),
        "market_validate_replacement_plan": (
            "plan market_historicaldatasetplan",
            "278dc50beb6b3c22db532e3dc9546cd9",
        ),
        "market_validate_acquisition_canary": (
            "attempt_chunk_id bigint, new_attempt_number integer, new_idempotency_key text, "
            "new_run_id bigint",
            "120f9de1a5378b7bbb509a54259a3cc9",
        ),
    }
)
REQUIRED_0025_TRIGGERS = dict(gate8b.REQUIRED_0022_TRIGGERS)
REQUIRED_0025_TRIGGERS.update(
    {
        (
            "market_historicaldiscoverychunk",
            "market_successor_chunk_complete",
        ): "b5b8ebb10152f7b116210e6448e30c9d",
        (
            "market_historicaldiscoveryplan",
            "market_successor_plan_complete",
        ): "16d4aa8754dc7c9866bad13d59961370",
    }
)
if len(REQUIRED_0025_FUNCTIONS) != 56 or len(REQUIRED_0025_TRIGGERS) != 74:
    raise RuntimeError("migration 0025 governed catalog pin is incomplete")

SUCCESSOR_VERIFY_PROSRC = r"""
        DECLARE chunk record; plan record; contract record; dataset record;
                registration record; inventory record; discovery_chunk record;
                attempt record; run record; manifest record; evidence record;
                attempt_count bigint; manifest_count bigint; candle_count bigint;
                observation_count bigint; matched_count bigint; bad_prices bigint;
                event_count bigint; run_event_count bigint; chunk_count bigint;
                timestamp_hash text; structural_hash text; semantic_hash text;
                key_stream text; payload_stream text; expected_key text;
        BEGIN
          SELECT c.* INTO chunk FROM market_historicalingestionchunk c
            WHERE c.logical_key='7b96484393a7e82eafd3bb5389dbf7f6b5b00ba6c9ed201d81814829b44a6151';
          IF chunk.id IS NULL THEN
            RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;
          SELECT p.* INTO STRICT plan FROM market_historicaldatasetplan p
            WHERE p.id=chunk.plan_id;
          SELECT hc.* INTO STRICT contract FROM market_historicaldatacontract hc
            WHERE hc.id=plan.data_contract_id;
          SELECT d.* INTO STRICT dataset FROM market_datasetversion d
            WHERE d.id=chunk.dataset_version_id;
          SELECT r.*, dp.sha256 AS discovery_plan_sha256,
                 dp.canonical_request_manifest_sha256 AS discovery_manifest_sha256,
                 dp.sealed_at AS discovery_sealed_at
            INTO STRICT registration
            FROM market_historicaldiscoveryregistration r
            JOIN market_historicaldiscoveryplan dp ON dp.id=r.plan_id
            WHERE r.id=contract.discovery_registration_id;
          SELECT i.* INTO STRICT inventory FROM market_historicaltimestampinventory i
            WHERE i.id=chunk.discovery_inventory_id;
          SELECT dc.* INTO STRICT discovery_chunk FROM market_historicaldiscoverychunk dc
            WHERE dc.id=inventory.chunk_id;
          SELECT count(*) INTO chunk_count FROM market_historicalingestionchunk c
            WHERE c.plan_id=plan.id;
          expected_key := market_sha256(jsonb_build_object(
            'canonical_request_sha256',chunk.canonical_request_sha256,
            'replacement_dataset_manifest_sha256',dataset.manifest_sha256,
            'replacement_plan_sha256',plan.sha256,
            'semantic_inventory_sha256',chunk.semantic_inventory_sha256));
          IF contract.identity<>'oanda-ba-ny17-friday-provider-observed-v2'
             OR contract.sha256<>'d630cc100cd06abdaa5d08d88353542999d625dd0c80f43eecbb5f649109f11c'
             OR market_sha256(contract.payload)<>contract.sha256
             OR plan.identity<>contract.identity
             OR plan.sha256<>'44dc82b2f20975e34e34e30ca7a709fff059ed14fa7457aaa26da4222d4df4cd'
             OR market_sha256(plan.payload)<>plan.sha256
             OR plan.data_contract_sha256<>contract.sha256
             OR dataset.name<>'failed-break-provider-observed-historical'
             OR dataset.version<>'phase-2b1r-v2'
             OR dataset.manifest_sha256<>'11da094fc7ca6a30e946be33523757d7ab559a9ad1951c9142e8969539930014'
             OR market_sha256(dataset.manifest)<>dataset.manifest_sha256
             OR dataset.data_contract_sha256<>contract.sha256
             OR registration.discovery_plan_sha256<>'e35d669efa860dd44e5fc145a65aaeabcd0d8745df5718507fa2b1a38abb3f88'
             OR registration.discovery_manifest_sha256<>'6d31a7aee0866c1e4b2479a78816594769005eaa759714c93dea39d55fddbea0'
             OR registration.global_semantic_inventory_sha256<>'f0285221956d4ec2d802eba1dc80f5a6d2a7be6697e62b1b3782705886b69427'
             OR registration.discovery_sealed_at IS NULL
             OR registration.discovery_sealed_at<>registration.registered_at
             OR chunk_count<>132
             OR chunk.logical_key<>expected_key
             OR chunk.canonical_request_sha256<>'9be615659265307cceecee27a19274013c897484613627115d7687558e618f38'
             OR chunk.semantic_inventory_sha256<>'3c7eecdc1842d16d2629a13284ef47d2da4b25a00320e99c80acaff2c98ee923'
             OR chunk.expected_observation_count<>2891
             OR chunk.data_contract_sha256<>contract.sha256
             OR inventory.semantic_inventory_sha256<>chunk.semantic_inventory_sha256
             OR inventory.timestamp_set_sha256<>'9b5dfc0d283aef1031e486f8683d56b6754ef0424942aaef8648735e15eb45b0'
             OR inventory.structural_observation_sha256<>'56f8931d6dae301608e0d01a6378928e30703ba17acf8a6dc7ba3c5188f74be5'
             OR inventory.observation_count<>2891
             OR discovery_chunk.canonical_request_sha256<>chunk.canonical_request_sha256
             OR discovery_chunk.requested_from<>chunk.requested_from
             OR discovery_chunk.requested_to<>chunk.requested_to
          THEN RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;

          SELECT count(*),market_sha256(coalesce(jsonb_agg(
                   market_discovery_timestamp(o.timestamp) ORDER BY o.timestamp),'[]')),
                 market_sha256(coalesce(jsonb_agg(jsonb_build_object(
                   'timestamp',market_discovery_timestamp(o.timestamp),'complete',o.complete,
                   'volume',o.volume,'bid_present',o.bid_present,'ask_present',o.ask_present)
                   ORDER BY o.timestamp),'[]'))
            INTO observation_count,timestamp_hash,structural_hash
            FROM market_historicaltimestampobservation o WHERE o.inventory_id=inventory.id;
          semantic_hash := market_sha256(jsonb_build_object(
            'logical_discovery_key',discovery_chunk.logical_key,
            'canonical_request_sha256',discovery_chunk.canonical_request_sha256,
            'observation_count',observation_count,'timestamp_set_sha256',timestamp_hash,
            'structural_observation_sha256',structural_hash));
          IF observation_count<>2891
             OR timestamp_hash<>'9b5dfc0d283aef1031e486f8683d56b6754ef0424942aaef8648735e15eb45b0'
             OR structural_hash<>'56f8931d6dae301608e0d01a6378928e30703ba17acf8a6dc7ba3c5188f74be5'
             OR semantic_hash<>'3c7eecdc1842d16d2629a13284ef47d2da4b25a00320e99c80acaff2c98ee923'
          THEN RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;

          SELECT count(*) INTO attempt_count FROM market_historicalingestionattempt a
            WHERE a.chunk_id=chunk.id;
          IF attempt_count<>1 THEN
            RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;
          SELECT a.* INTO STRICT attempt FROM market_historicalingestionattempt a
            WHERE a.chunk_id=chunk.id;
          SELECT r.* INTO STRICT run FROM market_ingestionrun r
            WHERE r.id=attempt.ingestion_run_id;
          SELECT count(*) INTO manifest_count FROM market_ingestionmanifest m
            WHERE m.ingestion_run_id=run.id;
          IF attempt.attempt_number<>1
             OR attempt.idempotency_key<>'failed-break-ingestion-attempt:'||chunk.logical_key||':1'
             OR run.status<>'succeeded' OR run.fetched_count<>2891
             OR run.stored_count<>2891 OR run.rejected_count<>0
             OR run.finished_at IS NULL OR manifest_count<>1
          THEN RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;
          SELECT m.* INTO STRICT manifest FROM market_ingestionmanifest m
            WHERE m.ingestion_run_id=run.id;
          IF manifest.dataset_version_id<>dataset.id
             OR manifest.sha256<>'1d3560139fc76de23f6aba31e943b6289e915f937c1d23128aa95b2077692be7'
             OR market_sha256(manifest.payload)<>manifest.sha256
          THEN RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;

          SELECT count(*) INTO candle_count FROM market_candle cd
            WHERE cd.ingestion_run_id=run.id AND cd.dataset_version_id=dataset.id;
          SELECT count(*) INTO matched_count FROM market_candle cd
            JOIN market_historicaltimestampobservation o
              ON o.inventory_id=inventory.id AND o.timestamp=cd.timestamp
             AND o.volume=cd.volume AND o.complete=cd.complete
             AND o.bid_present AND o.ask_present
            WHERE cd.ingestion_run_id=run.id AND cd.dataset_version_id=dataset.id;
          SELECT count(*) INTO bad_prices FROM market_candle cd
            WHERE cd.ingestion_run_id=run.id AND cd.dataset_version_id=dataset.id
              AND (NOT (cd.bid_open > 0 AND cd.bid_open < 1000000)
                OR NOT (cd.bid_high > 0 AND cd.bid_high < 1000000)
                OR NOT (cd.bid_low > 0 AND cd.bid_low < 1000000)
                OR NOT (cd.bid_close > 0 AND cd.bid_close < 1000000)
                OR NOT (cd.ask_open > 0 AND cd.ask_open < 1000000)
                OR NOT (cd.ask_high > 0 AND cd.ask_high < 1000000)
                OR NOT (cd.ask_low > 0 AND cd.ask_low < 1000000)
                OR NOT (cd.ask_close > 0 AND cd.ask_close < 1000000)
                OR cd.bid_low > least(cd.bid_open,cd.bid_close)
                OR cd.bid_high < greatest(cd.bid_open,cd.bid_close)
                OR cd.bid_low > cd.bid_high
                OR cd.ask_low > least(cd.ask_open,cd.ask_close)
                OR cd.ask_high < greatest(cd.ask_open,cd.ask_close)
                OR cd.ask_low > cd.ask_high
                OR cd.bid_open > cd.ask_open OR cd.bid_high > cd.ask_high
                OR cd.bid_low > cd.ask_low OR cd.bid_close > cd.ask_close
                OR NOT cd.complete);
          IF candle_count<>2891 OR matched_count<>2891 OR bad_prices<>0
             OR EXISTS (SELECT 1 FROM market_historicaltimestampobservation o
                  WHERE o.inventory_id=inventory.id AND NOT EXISTS (
                    SELECT 1 FROM market_candle cd WHERE cd.ingestion_run_id=run.id
                      AND cd.dataset_version_id=dataset.id AND cd.timestamp=o.timestamp))
             OR EXISTS (SELECT 1 FROM market_candle cd
                  WHERE cd.ingestion_run_id=run.id AND cd.dataset_version_id=dataset.id
                    AND NOT EXISTS (SELECT 1 FROM market_historicaltimestampobservation o
                      WHERE o.inventory_id=inventory.id AND o.timestamp=cd.timestamp))
          THEN RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;

          SELECT string_agg(fragment.key_json,'' ORDER BY fragment.ts),
                 string_agg(fragment.payload_json,'' ORDER BY fragment.ts)
            INTO key_stream,payload_stream
            FROM (
              SELECT cd.timestamp AS ts,
                '["'||i.code||'","'||cd.granularity||'","'
                  ||to_char(cd.timestamp AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS')
                  ||'+00:00"]' AS key_json,
                '["'||i.code||'","'||cd.granularity||'","'
                  ||to_char(cd.timestamp AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS')
                  ||'+00:00",'||CASE WHEN cd.complete THEN 'true' ELSE 'false' END
                  ||','||cd.volume
                  ||',"'||to_char(cd.bid_open,'FM999999990.000000')
                  ||'","'||to_char(cd.bid_high,'FM999999990.000000')
                  ||'","'||to_char(cd.bid_low,'FM999999990.000000')
                  ||'","'||to_char(cd.bid_close,'FM999999990.000000')
                  ||'","'||to_char(cd.ask_open,'FM999999990.000000')
                  ||'","'||to_char(cd.ask_high,'FM999999990.000000')
                  ||'","'||to_char(cd.ask_low,'FM999999990.000000')
                  ||'","'||to_char(cd.ask_close,'FM999999990.000000')||'"]' AS payload_json
              FROM market_candle cd JOIN market_instrument i ON i.id=cd.instrument_id
              WHERE cd.ingestion_run_id=run.id AND cd.dataset_version_id=dataset.id
            ) AS fragment;
          IF encode(digest(convert_to(key_stream,'UTF8'),'sha256'),'hex')<>
                '4603365940d1c75951f640eca8e36b72cfe5c9456f9d1291b2cb2a065f5ca72d'
             OR encode(digest(convert_to(payload_stream,'UTF8'),'sha256'),'hex')<>
                '2f9ff07b605778de0d9d8926d0ba6e3c60a53d49efd78b8e3ef049223349413c'
          THEN RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;

          SELECT count(*) INTO event_count FROM market_auditevent e
            WHERE e.event_type='market.replacement_acquisition_succeeded'
              AND e.subject_type='HistoricalIngestionAttempt'
              AND e.subject_id=attempt.id::text;
          IF event_count<>1 THEN
            RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;
          SELECT e.* INTO STRICT evidence FROM market_auditevent e
            WHERE e.event_type='market.replacement_acquisition_succeeded'
              AND e.subject_type='HistoricalIngestionAttempt'
              AND e.subject_id=attempt.id::text;
          IF evidence.payload->>'logical_key'<>chunk.logical_key
             OR evidence.payload->>'canonical_request_sha256'<>chunk.canonical_request_sha256
             OR evidence.payload->>'semantic_inventory_sha256'<>chunk.semantic_inventory_sha256
             OR evidence.payload->>'data_contract_sha256'<>contract.sha256
             OR evidence.payload->>'plan_sha256'<>plan.sha256
             OR evidence.payload->>'dataset_manifest_sha256'<>dataset.manifest_sha256
             OR evidence.payload->>'ingestion_manifest_sha256'<>manifest.sha256
             OR (evidence.payload->>'attempt_number')::integer<>1
             OR evidence.payload->>'idempotency_key'<>attempt.idempotency_key
             OR (evidence.payload->>'expected_candle_count')::bigint<>2891
             OR (evidence.payload->>'stored_candle_count')::bigint<>2891
             OR evidence.payload->>'candle_key_hash'<>
                '4603365940d1c75951f640eca8e36b72cfe5c9456f9d1291b2cb2a065f5ca72d'
             OR evidence.payload->>'candle_payload_hash'<>
                '2f9ff07b605778de0d9d8926d0ba6e3c60a53d49efd78b8e3ef049223349413c'
             OR evidence.payload->>'terminal_event_sha256'<>
                'c19ecdb2a260b6339287399e6ea8b85335b39d389ad26f76e602586eeb14d3a2'
             OR evidence.payload->>'operational_evidence_sha256'<>
                '2a329006323c4fc51856aff9fcf97528efcca42b6aa2e75e711865776aeed7fb'
             OR market_sha256(evidence.payload-'schema_version'-'provider_evidence'
                              -'terminal_event_sha256'-'operational_evidence_sha256')
                <>evidence.payload->>'terminal_event_sha256'
             OR market_sha256(jsonb_build_array(
                  evidence.payload->'terminal_event_sha256',
                  evidence.payload->'provider_evidence',to_jsonb(attempt.idempotency_key)))
                <>evidence.payload->>'operational_evidence_sha256'
          THEN RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;
          SELECT count(*) INTO run_event_count FROM market_auditevent e
            WHERE e.event_type='market.ingestion_succeeded'
              AND e.subject_type='IngestionRun' AND e.subject_id=run.id::text;
          IF run_event_count<>1
             OR EXISTS (SELECT 1 FROM market_historicalingestionattempt a
                  JOIN market_historicalingestionchunk c ON c.id=a.chunk_id
                  JOIN market_historicaldatasetplan p ON p.id=c.plan_id
                  JOIN market_ingestionrun r ON r.id=a.ingestion_run_id
                  WHERE p.sha256='44dc82b2f20975e34e34e30ca7a709fff059ed14fa7457aaa26da4222d4df4cd'
                    AND (a.attempt_number<>1 OR r.status IN ('running','failed','quarantined')))
             OR EXISTS (SELECT 1 FROM market_auditevent e
                  JOIN market_historicalingestionattempt a ON a.id::text=e.subject_id
                  JOIN market_historicalingestionchunk c ON c.id=a.chunk_id
                  JOIN market_historicaldatasetplan p ON p.id=c.plan_id
                  WHERE e.subject_type='HistoricalIngestionAttempt'
                    AND e.event_type='market.historical_ingestion_failed'
                    AND p.sha256='44dc82b2f20975e34e34e30ca7a709fff059ed14fa7457aaa26da4222d4df4cd')
             OR EXISTS (SELECT 1 FROM market_datasetregistration dr
                  WHERE dr.dataset_version_id=dataset.id)
          THEN RAISE EXCEPTION 'successor canary success does not reconstruct'; END IF;
        END """


def _execute(cursor, statement):
    cursor.execute(statement.replace("%", "%%"))


def _install(cursor, signature, returns, body):
    _execute(
        cursor,
        f"CREATE OR REPLACE FUNCTION {signature} RETURNS {returns} AS $governed${body}$governed$"
        " LANGUAGE plpgsql",
    )


def _drop_successor_verifier(cursor):
    cursor.execute("DROP FUNCTION market_verify_successor_canary_success()")


def _installed_body(cursor, name):
    cursor.execute(
        "SELECT prosrc FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace"
        " WHERE n.nspname=current_schema() AND p.proname=%s",
        [name],
    )
    rows = cursor.fetchall()
    if len(rows) != 1:
        raise RuntimeError(f"governed function {name} is missing or ambiguous")
    return rows[0][0]


def _catalog(cursor):
    governance = import_module("market.migrations.0014_historical_discovery_supersession")
    cursor.execute(
        r"SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace"
        r" WHERE n.nspname=current_schema() AND p.proname LIKE 'market\_%'"
    )
    names = [row[0] for row in cursor.fetchall()]
    cursor.execute(governance.FUNCTION_FINGERPRINT_SQL, [names])
    functions = {}
    for name, arguments, fingerprint in cursor.fetchall():
        functions.setdefault(name, []).append((arguments, fingerprint))
    cursor.execute(governance.TRIGGER_FINGERPRINT_SQL)
    triggers = {}
    for table, name, fingerprint in cursor.fetchall():
        if name.startswith("market_"):
            triggers.setdefault((table, name), []).append(fingerprint)
    return functions, triggers


def _require_0025_catalog(cursor):
    functions, triggers = _catalog(cursor)
    if set(functions) != set(REQUIRED_0025_FUNCTIONS):
        raise RuntimeError("gate 8G requires the complete migration 0025 function catalog")
    if set(triggers) != set(REQUIRED_0025_TRIGGERS):
        raise RuntimeError("gate 8G requires the complete migration 0025 trigger catalog")
    for name, expected in REQUIRED_0025_FUNCTIONS.items():
        if functions[name] != [expected]:
            raise RuntimeError(f"migration 0025 function {name} does not match its catalog pin")
    for key, expected in REQUIRED_0025_TRIGGERS.items():
        if triggers[key] != [expected]:
            raise RuntimeError(f"migration 0025 trigger {key[1]} does not match its catalog pin")
    if _installed_body(cursor, "market_validate_acquisition_canary") != PRIOR_CANARY_PROSRC:
        raise RuntimeError("installed acquisition canary validator is not the 0025 body")
    return functions, triggers


def _untouched(catalog):
    functions, triggers = catalog
    return (
        {
            name: entries
            for name, entries in functions.items()
            if name
            not in {
                "market_validate_acquisition_canary",
                "market_verify_successor_canary_success",
            }
        },
        triggers,
    )


def _successor_noncanary_evidence(cursor):
    cursor.execute(
        """
        SELECT EXISTS(
          SELECT 1 FROM market_historicalingestionattempt a
          JOIN market_historicalingestionchunk c ON c.id=a.chunk_id
          JOIN market_historicaldatasetplan p ON p.id=c.plan_id
          WHERE p.sha256=%s AND c.logical_key<>%s
        ) OR EXISTS(
          SELECT 1 FROM market_auditevent e
          WHERE e.subject_type='HistoricalIngestionAttempt'
            AND e.event_type IN ('market.replacement_acquisition_succeeded',
                                 'market.historical_ingestion_failed')
            AND e.payload->>'plan_sha256'=%s
            AND e.payload->>'logical_key'<>%s
        )
        """,
        [SUCCESSOR_PLAN_SHA256, SUCCESSOR_CANARY_KEY] * 2,
    )
    return cursor.fetchone()[0]


def forward(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        before = _untouched(_require_0025_catalog(cursor))
        predecessor_verifier = _installed_body(cursor, "market_verify_replacement_canary_success")
        _install(cursor, SUCCESSOR_VERIFIER_SIGNATURE, "void", SUCCESSOR_VERIFY_PROSRC)
        _install(cursor, CANARY_VALIDATOR_SIGNATURE, "void", GATE8G_CANARY_PROSRC)
        functions, triggers = _catalog(cursor)
        if len(functions) != 57 or len(triggers) != 74:
            raise RuntimeError("gate 8G must add exactly one function and no trigger")
        if (
            _installed_body(cursor, "market_verify_successor_canary_success")
            != SUCCESSOR_VERIFY_PROSRC
        ):
            raise RuntimeError("gate 8G successor verifier did not install exactly")
        if _installed_body(cursor, "market_validate_acquisition_canary") != GATE8G_CANARY_PROSRC:
            raise RuntimeError("gate 8G acquisition validator did not install exactly")
        if (
            _installed_body(cursor, "market_verify_replacement_canary_success")
            != predecessor_verifier
        ):
            raise RuntimeError("gate 8G changed the predecessor canary verifier")
        if _untouched((functions, triggers)) != before:
            raise RuntimeError("gate 8G altered a governance object outside its exact delta")


def reverse(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if _successor_noncanary_evidence(cursor):
            raise RuntimeError("successor non-canary acquisition evidence prohibits reversal")
        functions, triggers = _catalog(cursor)
        if len(functions) != 57 or len(triggers) != 74:
            raise RuntimeError("gate 8G reversal requires its exact installed catalog shape")
        before = _untouched((functions, triggers))
        if (
            _installed_body(cursor, "market_verify_successor_canary_success")
            != SUCCESSOR_VERIFY_PROSRC
        ):
            raise RuntimeError("installed successor verifier is not the 0026 body")
        if _installed_body(cursor, "market_validate_acquisition_canary") != GATE8G_CANARY_PROSRC:
            raise RuntimeError("installed acquisition validator is not the 0026 body")
        _install(cursor, CANARY_VALIDATOR_SIGNATURE, "void", PRIOR_CANARY_PROSRC)
        _drop_successor_verifier(cursor)
        restored = _catalog(cursor)
        if _untouched(restored) != before:
            raise RuntimeError("gate 8G reversal altered an unrelated governance object")
        _require_0025_catalog(cursor)


class Migration(migrations.Migration):
    atomic = True

    dependencies = [("market", "0025_gate8e_successor_contract_materialization")]

    operations = [migrations.RunPython(forward, reverse)]
