# Generated by Django 5.2.17 on 2026-09-08 20:27

from django.db import migrations, models


def enable_existing(apps, schema_editor):
    instrument = apps.get_model("market", "Instrument")
    instrument.objects.using(schema_editor.connection.alias).filter(
        models.Q(active=True)
        | models.Q(
            code__in=(
                "EUR_USD",
                "GBP_USD",
                "EUR_GBP",
                "USD_CAD",
                "USD_JPY",
                "AUD_USD",
                "USD_CHF",
                "NZD_USD",
                "EUR_JPY",
                "GBP_JPY",
                "AUD_JPY",
                "AUD_CAD",
            )
        )
    ).update(ingestion_enabled=True)


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0029_candle_observation_lineage"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="ingestion_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(enable_existing, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="instrument",
            name="code",
            field=models.CharField(
                choices=[
                    ("AUD_USD", "AUD/USD"),
                    ("USD_CAD", "USD/CAD"),
                    ("GBP_USD", "GBP/USD"),
                    ("EUR_GBP", "EUR/GBP"),
                    ("EUR_USD", "EUR/USD"),
                    ("USD_JPY", "USD/JPY"),
                    ("USD_CHF", "USD/CHF"),
                    ("NZD_USD", "NZD/USD"),
                    ("EUR_JPY", "EUR/JPY"),
                    ("GBP_JPY", "GBP/JPY"),
                    ("AUD_JPY", "AUD/JPY"),
                    ("AUD_CAD", "AUD/CAD"),
                ],
                max_length=7,
                unique=True,
            ),
        ),
    ]
