# Generated by Django 5.2.17 on 2026-09-09 15:02

import django.db.models.deletion
from django.db import migrations, models

# Database-boundary immutability. The ORM ``ImmutableModel`` blocks mutation
# through Python, but raw SQL reaches past it, so market-state definitions and
# snapshots are also protected at the database: any UPDATE/DELETE, and any
# ordinary TRUNCATE, on these tables raises. This mirrors the existing
# convention (forecasts/migrations/0002 and 0019, market/migrations/0028) and is
# guarded to PostgreSQL.
_TABLES = ("market_marketstatedefinition", "market_marketstatesnapshot")

# The one permitted truncation is Django's test-database flush, detected exactly
# as market/migrations/0028's market_live_evidence_reject_truncate does: only in
# a ``test_*`` database, and only while an AccessExclusiveLock is held on
# auth_permission (a whole-database flush truncates every table at once and so
# holds that lock; an ordinary TRUNCATE of one governed table does not).
_TRUNCATE_GUARD = r"""
CREATE OR REPLACE FUNCTION market_state_reject_truncate() RETURNS trigger AS $$
BEGIN
    IF current_database() LIKE 'test\_%' ESCAPE '\'
       AND EXISTS(
         SELECT 1 FROM pg_locks locks
         WHERE locks.pid = pg_backend_pid() AND locks.granted
           AND locks.mode = 'AccessExclusiveLock'
           AND locks.relation = 'auth_permission'::regclass
       ) THEN RETURN NULL; END IF;
    RAISE EXCEPTION '% must not be truncated', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;
"""

_INSTALL_TRIGGERS = _TRUNCATE_GUARD + "\n".join(
    f"""
CREATE OR REPLACE FUNCTION reject_mutation_{table}()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '{table} is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER {table}_immutable
BEFORE UPDATE OR DELETE ON {table}
FOR EACH ROW EXECUTE FUNCTION reject_mutation_{table}();

CREATE TRIGGER {table}_no_truncate
BEFORE TRUNCATE ON {table}
FOR EACH STATEMENT EXECUTE FUNCTION market_state_reject_truncate();
"""
    for table in _TABLES
)

_DROP_TRIGGERS = (
    "\n".join(
        f"""
DROP TRIGGER IF EXISTS {table}_immutable ON {table};
DROP TRIGGER IF EXISTS {table}_no_truncate ON {table};
DROP FUNCTION IF EXISTS reject_mutation_{table}();
"""
        for table in _TABLES
    )
    + "\nDROP FUNCTION IF EXISTS market_state_reject_truncate();"
)


def install_immutability(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(_INSTALL_TRIGGERS)


def drop_immutability(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(_DROP_TRIGGERS)


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0031_m15_live_granularity"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketStateDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("version", models.CharField(max_length=40)),
                ("definition", models.JSONField()),
                ("definition_sha256", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("key", "version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "version"), name="unique_market_state_definition_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketStateSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("information_cutoff", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("input_manifest", models.JSONField()),
                ("input_manifest_sha256", models.CharField(max_length=64)),
                ("evidence_manifest", models.JSONField(default=dict)),
                ("output_payload", models.JSONField()),
                ("output_sha256", models.CharField(max_length=64)),
                (
                    "data_quality_status",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("degraded", "Degraded"),
                        ],
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="market.marketstatedefinition",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
            ],
            options={
                "ordering": ("instrument", "information_cutoff", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["instrument", "definition", "-information_cutoff"],
                        name="market_mark_instrum_2c08b6_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("data_quality_status__in", ["complete", "partial", "degraded"])
                        ),
                        name="market_state_snapshot_quality_status_valid",
                    )
                ],
            },
        ),
        migrations.RunPython(install_immutability, drop_immutability),
    ]
