# Generated by Django 5.2.17 on 2026-09-10 00:41

from django.db import migrations, models

# jsonb-shape checks that Django's Q-based CheckConstraint cannot express. These
# reject a raw INSERT of a definition/snapshot whose JSON columns have the wrong
# shape (e.g. a definition body of ``[]`` instead of an object), at the database
# boundary — not only through the ORM.
_JSONB_SHAPE = r"""
ALTER TABLE market_marketstatedefinition
  ADD CONSTRAINT market_state_definition_body_is_object
  CHECK (jsonb_typeof(definition) = 'object');
ALTER TABLE market_marketstatesnapshot
  ADD CONSTRAINT market_state_snapshot_payload_is_object
  CHECK (jsonb_typeof(output_payload) = 'object');
ALTER TABLE market_marketstatesnapshot
  ADD CONSTRAINT market_state_snapshot_manifest_is_array
  CHECK (jsonb_typeof(input_manifest) = 'array');
ALTER TABLE market_marketstatesnapshot
  ADD CONSTRAINT market_state_snapshot_evidence_is_object
  CHECK (jsonb_typeof(evidence_manifest) = 'object');
"""

_DROP_JSONB_SHAPE = r"""
ALTER TABLE market_marketstatedefinition DROP CONSTRAINT IF EXISTS market_state_definition_body_is_object;
ALTER TABLE market_marketstatesnapshot DROP CONSTRAINT IF EXISTS market_state_snapshot_payload_is_object;
ALTER TABLE market_marketstatesnapshot DROP CONSTRAINT IF EXISTS market_state_snapshot_manifest_is_array;
ALTER TABLE market_marketstatesnapshot DROP CONSTRAINT IF EXISTS market_state_snapshot_evidence_is_object;
"""


def _install_shape_checks(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(_JSONB_SHAPE)


def _drop_shape_checks(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(_DROP_JSONB_SHAPE)


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0032_market_state_records"),
    ]

    operations = [
        migrations.RunPython(_install_shape_checks, _drop_shape_checks),
        migrations.AddIndex(
            model_name="candleobservation",
            index=models.Index(
                fields=["instrument", "granularity", "-timestamp", "-revision"],
                name="candle_obs_series_rev_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketstatedefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(("definition_sha256__regex", "^[0-9a-f]{64}$")),
                name="market_state_definition_sha256_hex",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketstatesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("output_sha256__regex", "^[0-9a-f]{64}$"),
                    ("input_manifest_sha256__regex", "^[0-9a-f]{64}$"),
                    ("idempotency_key__regex", "^[0-9a-f]{64}$"),
                ),
                name="market_state_snapshot_sha256_hex",
            ),
        ),
    ]
