# Generated by Django 5.2.17 on 2026-09-10 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0037_market_state_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("strategy", models.CharField(max_length=100, unique=True)),
                ("body", models.JSONField()),
                ("body_sha256", models.CharField(max_length=64, unique=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategyEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("evidence", models.JSONField()),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("output", models.JSONField()),
                ("output_sha256", models.CharField(max_length=64)),
                ("identity", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.strategydefinition"
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="market.strategyevaluation",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.marketstatesnapshot"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategySimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_key", models.CharField(max_length=64, unique=True)),
                (
                    "outcome_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.marketstatesnapshot"
                    ),
                ),
                ("intent", models.JSONField()),
                ("outcome_evidence", models.JSONField()),
                ("output", models.JSONField()),
                ("output_sha256", models.CharField(max_length=64)),
                ("identity", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.strategyevaluation"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
