# Generated by Django 5.2.17 on 2026-08-19 04:40

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market", "0003_candle_candle_bid_ohlc_valid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("market_data_cutoff", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "anchor_candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.candle"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
                (
                    "technical_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.technicalsnapshot"
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at",),
            },
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("method", models.CharField(max_length=80)),
                ("method_version", models.PositiveSmallIntegerField(default=1)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("information_cutoff", models.DateTimeField()),
                ("reference_midpoint", models.DecimalField(decimal_places=6, max_digits=12)),
                ("neutral_band", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "direction",
                    models.CharField(
                        choices=[("up", "Up"), ("neutral", "Neutral"), ("down", "Down")],
                        max_length=8,
                    ),
                ),
                ("probability_up", models.DecimalField(decimal_places=4, max_digits=5)),
                ("probability_neutral", models.DecimalField(decimal_places=4, max_digits=5)),
                ("probability_down", models.DecimalField(decimal_places=4, max_digits=5)),
                ("abstained", models.BooleanField(default=True)),
                ("abstention_reason", models.TextField(blank=True)),
                (
                    "entry_condition",
                    models.CharField(
                        choices=[
                            ("none", "No conditional entry"),
                            ("at_or_below", "At or below"),
                            ("at_or_above", "At or above"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                (
                    "entry_level",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "target_level",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "invalidation_level",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ("setup_expires_after_sessions", models.PositiveSmallIntegerField()),
                ("rationale", models.TextField()),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                (
                    "evidence_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="forecasts.evidencesnapshot"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="forecasts.forecast",
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ForecastResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("up", "Up"),
                            ("neutral", "Neutral"),
                            ("down", "Down"),
                            ("cancelled", "Cancelled"),
                            ("missing", "Missing data"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "endpoint_midpoint",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "midpoint_change",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "setup_outcome",
                    models.CharField(
                        choices=[
                            ("not_offered", "No setup offered"),
                            ("not_activated", "Entry not activated"),
                            ("activated", "Entry activated; paper resolution deferred"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "brier_score",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
                ),
                ("details", models.JSONField(default=dict)),
                ("resolved_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "forecast",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolution",
                        to="forecasts.forecast",
                    ),
                ),
                (
                    "horizon_candle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="market.candle",
                    ),
                ),
            ],
            options={
                "ordering": ("-resolved_at",),
            },
        ),
        migrations.CreateModel(
            name="TargetContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("version", models.PositiveSmallIntegerField()),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("macro", "20-session macro outlook"),
                            ("tactical", "Five-session tactical outlook"),
                        ],
                        max_length=12,
                    ),
                ),
                ("horizon_sessions", models.PositiveSmallIntegerField()),
                ("neutral_atr_multiplier", models.DecimalField(decimal_places=3, max_digits=5)),
                ("spread_multiplier", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scoring_rule", models.CharField(max_length=80)),
                ("definition", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("product", "-version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "version"), name="unique_target_contract_version"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="forecast",
            name="target_contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="forecasts.targetcontract"
            ),
        ),
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.CheckConstraint(
                condition=models.Q(("probability_up__gte", 0), ("probability_up__lte", 1)),
                name="forecast_probability_up_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("probability_neutral__gte", 0), ("probability_neutral__lte", 1)
                ),
                name="forecast_probability_neutral_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.CheckConstraint(
                condition=models.Q(("probability_down__gte", 0), ("probability_down__lte", 1)),
                name="forecast_probability_down_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "probability_up",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.Value(1), "-", models.F("probability_neutral")
                            ),
                            "-",
                            models.F("probability_down"),
                        ),
                    )
                ),
                name="forecast_probabilities_sum_one",
            ),
        ),
    ]
