# Generated by Django 5.2.17 on 2026-08-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0002_immutable_forecast_records"),
        ("market", "0003_candle_candle_bid_ohlc_valid_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.CheckConstraint(
                condition=models.Q(("information_cutoff__lte", models.F("issued_at"))),
                name="forecast_cutoff_not_after_issuance",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("abstained", True),
                        ("entry_condition", "none"),
                        ("entry_level__isnull", True),
                        ("invalidation_level__isnull", True),
                        ("target_level__isnull", True),
                    ),
                    models.Q(
                        ("abstained", False),
                        ("entry_condition__in", ("at_or_below", "at_or_above")),
                        ("entry_level__isnull", False),
                        ("invalidation_level__isnull", False),
                        ("target_level__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="forecast_setup_shape_valid",
            ),
        ),
    ]
