# Generated by Django 5.2.17 on 2026-08-20 02:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION reject_mutation_forecasts_recommendation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'forecasts_recommendation is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER forecasts_recommendation_immutable
BEFORE UPDATE OR DELETE ON forecasts_recommendation
FOR EACH ROW EXECUTE FUNCTION reject_mutation_forecasts_recommendation();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS forecasts_recommendation_immutable ON forecasts_recommendation;
DROP FUNCTION IF EXISTS reject_mutation_forecasts_recommendation();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0003_forecast_forecast_cutoff_not_after_issuance_and_more"),
        ("market", "0003_candle_candle_bid_ohlc_valid_and_more"),
        ("research", "0008_pair_evidence_intermarket"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("model", models.CharField(max_length=100)),
                ("contract_version", models.PositiveSmallIntegerField(default=1)),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("information_cutoff", models.DateTimeField()),
                (
                    "action",
                    models.CharField(
                        choices=[("abstain", "Abstain"), ("buy", "Buy"), ("sell", "Sell")],
                        max_length=8,
                    ),
                ),
                ("confidence_percent", models.PositiveSmallIntegerField()),
                (
                    "entry_condition",
                    models.CharField(
                        choices=[
                            ("none", "No conditional entry"),
                            ("at_or_below", "At or below"),
                            ("at_or_above", "At or above"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "entry_level",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "target_level",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "invalidation_level",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ("expires_after_sessions", models.PositiveSmallIntegerField(default=5)),
                ("output", models.JSONField()),
                ("input_payload", models.JSONField()),
                ("request_sha256", models.CharField(max_length=64)),
                ("provider_response_id", models.CharField(blank=True, max_length=120)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("idempotency_key", models.CharField(max_length=240, unique=True)),
                (
                    "control_forecast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="forecasts.forecast",
                    ),
                ),
                (
                    "evidence_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="research.pairevidencesnapshot",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="market.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ("-generated_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence_percent__gte", 0), ("confidence_percent__lte", 100)
                        ),
                        name="recommendation_confidence_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("action", "abstain"),
                                ("entry_condition", "none"),
                                ("entry_level__isnull", True),
                                ("invalidation_level__isnull", True),
                                ("target_level__isnull", True),
                            ),
                            models.Q(
                                ("action__in", ("buy", "sell")),
                                ("entry_condition__in", ("at_or_below", "at_or_above")),
                                ("entry_level__isnull", False),
                                ("invalidation_level__isnull", False),
                                ("target_level__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="recommendation_setup_shape_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("information_cutoff__lte", models.F("generated_at"))),
                        name="recommendation_cutoff_not_after_generation",
                    ),
                ],
            },
        ),
        migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER),
    ]
