# Generated by Django 5.2.17 on 2026-08-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0004_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="cost_usd",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
