# Generated by Django 5.2.17 on 2026-08-20 04:08

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models

CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION reject_mutation_forecasts_recommendationresolution()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'forecasts_recommendationresolution is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER forecasts_recommendationresolution_immutable
BEFORE UPDATE OR DELETE ON forecasts_recommendationresolution
FOR EACH ROW EXECUTE FUNCTION reject_mutation_forecasts_recommendationresolution();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS forecasts_recommendationresolution_immutable
ON forecasts_recommendationresolution;
DROP FUNCTION IF EXISTS reject_mutation_forecasts_recommendationresolution();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0005_recommendation_cost_usd"),
        ("market", "0003_candle_candle_bid_ohlc_valid_and_more"),
        ("research", "0008_pair_evidence_intermarket"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("up", "Up"), ("neutral", "Neutral"), ("down", "Down")],
                        max_length=8,
                    ),
                ),
                ("endpoint_midpoint", models.DecimalField(decimal_places=6, max_digits=12)),
                ("midpoint_change", models.DecimalField(decimal_places=6, max_digits=12)),
                ("directional_hit", models.BooleanField(blank=True, null=True)),
                ("brier_score", models.DecimalField(decimal_places=6, max_digits=8)),
                ("details", models.JSONField(default=dict)),
                ("resolved_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-resolved_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="recommendation",
            name="neutral_band",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="probability_down",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="probability_neutral",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="probability_up",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="reference_candle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="model_recommendations",
                to="market.candle",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="reference_midpoint",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contract_version__lt", 2),
                    models.Q(
                        ("neutral_band__isnull", False),
                        ("probability_down__gte", 0),
                        ("probability_down__isnull", False),
                        ("probability_down__lte", 1),
                        ("probability_neutral__gte", 0),
                        ("probability_neutral__isnull", False),
                        ("probability_neutral__lte", 1),
                        (
                            "probability_up",
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.Value(1), "-", models.F("probability_neutral")
                                ),
                                "-",
                                models.F("probability_down"),
                            ),
                        ),
                        ("probability_up__gte", 0),
                        ("probability_up__isnull", False),
                        ("probability_up__lte", 1),
                        ("reference_candle__isnull", False),
                        ("reference_midpoint__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="recommendation_v2_outcome_contract_valid",
            ),
        ),
        migrations.AddField(
            model_name="recommendationresolution",
            name="horizon_candle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="market.candle"
            ),
        ),
        migrations.AddField(
            model_name="recommendationresolution",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolution",
                to="forecasts.recommendation",
            ),
        ),
        migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER),
    ]
