# Generated by Django 5.2.17 on 2026-08-20 04:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

CREATE_TRIGGERS = """
CREATE OR REPLACE FUNCTION reject_mutation_forecasts_papertradeentry()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'forecasts_papertradeentry is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER forecasts_papertradeentry_immutable
BEFORE UPDATE OR DELETE ON forecasts_papertradeentry
FOR EACH ROW EXECUTE FUNCTION reject_mutation_forecasts_papertradeentry();

CREATE OR REPLACE FUNCTION reject_mutation_forecasts_papertraderesult()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'forecasts_papertraderesult is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER forecasts_papertraderesult_immutable
BEFORE UPDATE OR DELETE ON forecasts_papertraderesult
FOR EACH ROW EXECUTE FUNCTION reject_mutation_forecasts_papertraderesult();
"""

DROP_TRIGGERS = """
DROP TRIGGER IF EXISTS forecasts_papertradeentry_immutable ON forecasts_papertradeentry;
DROP FUNCTION IF EXISTS reject_mutation_forecasts_papertradeentry();
DROP TRIGGER IF EXISTS forecasts_papertraderesult_immutable ON forecasts_papertraderesult;
DROP FUNCTION IF EXISTS reject_mutation_forecasts_papertraderesult();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0006_recommendationresolution_recommendation_neutral_band_and_more"),
        ("market", "0004_alter_candle_granularity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperTradeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "execution_side",
                    models.CharField(choices=[("ask", "Ask"), ("bid", "Bid")], max_length=3),
                ),
                ("fill_price", models.DecimalField(decimal_places=6, max_digits=12)),
                ("observed_open_spread", models.DecimalField(decimal_places=6, max_digits=12)),
                ("details", models.JSONField(default=dict)),
                ("entered_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.candle"
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_entry",
                        to="forecasts.recommendation",
                    ),
                ),
            ],
            options={
                "ordering": ("-entered_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PaperTradeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("target", "Target hit"),
                            ("invalidated", "Invalidated"),
                            ("expired", "Entered; expired at session close"),
                            ("not_activated", "Entry not activated"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "gross_pips",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
                ),
                (
                    "r_multiple",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                ("details", models.JSONField(default=dict)),
                ("resolved_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result",
                        to="forecasts.papertradeentry",
                    ),
                ),
                (
                    "exit_candle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_exit_results",
                        to="market.candle",
                    ),
                ),
                (
                    "horizon_candle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_horizon_results",
                        to="market.candle",
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paper_result",
                        to="forecasts.recommendation",
                    ),
                ),
            ],
            options={
                "ordering": ("-resolved_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="papertradeentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("observed_open_spread__gte", 0)),
                name="paper_entry_spread_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="papertraderesult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("entry__isnull", True),
                        ("exit_candle__isnull", True),
                        ("exit_price__isnull", True),
                        ("gross_pips__isnull", True),
                        ("horizon_candle__isnull", False),
                        ("outcome", "not_activated"),
                        ("r_multiple__isnull", True),
                    ),
                    models.Q(
                        ("entry__isnull", False),
                        ("exit_candle__isnull", False),
                        ("exit_price__isnull", False),
                        ("gross_pips__isnull", False),
                        ("outcome__in", ("target", "invalidated")),
                        ("r_multiple__isnull", False),
                    ),
                    models.Q(
                        ("entry__isnull", False),
                        ("exit_candle__isnull", False),
                        ("exit_price__isnull", False),
                        ("gross_pips__isnull", False),
                        ("horizon_candle__isnull", False),
                        ("outcome", "expired"),
                        ("r_multiple__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="paper_result_shape_valid",
            ),
        ),
        migrations.RunSQL(CREATE_TRIGGERS, DROP_TRIGGERS),
    ]
