# Generated by Django 5.2.17 on 2026-08-20 07:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION reject_mutation_forecasts_papertradecostassessment()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'forecasts_papertradecostassessment is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER forecasts_papertradecostassessment_immutable
BEFORE UPDATE OR DELETE ON forecasts_papertradecostassessment
FOR EACH ROW EXECUTE FUNCTION reject_mutation_forecasts_papertradecostassessment();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS forecasts_papertradecostassessment_immutable
ON forecasts_papertradecostassessment;
DROP FUNCTION IF EXISTS reject_mutation_forecasts_papertradecostassessment();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0007_papertradeentry_papertraderesult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperTradeCostAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policy_version", models.CharField(max_length=80)),
                ("minimum_financing_days", models.PositiveSmallIntegerField()),
                ("maximum_financing_days", models.PositiveSmallIntegerField()),
                ("optimistic_net_pips", models.DecimalField(decimal_places=3, max_digits=12)),
                ("base_net_pips", models.DecimalField(decimal_places=3, max_digits=12)),
                ("conservative_net_pips", models.DecimalField(decimal_places=3, max_digits=12)),
                ("optimistic_net_r", models.DecimalField(decimal_places=4, max_digits=12)),
                ("base_net_r", models.DecimalField(decimal_places=4, max_digits=12)),
                ("conservative_net_r", models.DecimalField(decimal_places=4, max_digits=12)),
                ("details", models.JSONField()),
                ("assessed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_assessment",
                        to="forecasts.papertraderesult",
                    ),
                ),
            ],
            options={
                "ordering": ("-assessed_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("minimum_financing_days__lte", models.F("maximum_financing_days"))
                        ),
                        name="paper_cost_financing_day_range_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("optimistic_net_pips__gte", models.F("base_net_pips")),
                            ("base_net_pips__gte", models.F("conservative_net_pips")),
                        ),
                        name="paper_cost_net_pip_scenarios_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("optimistic_net_r__gte", models.F("base_net_r")),
                            ("base_net_r__gte", models.F("conservative_net_r")),
                        ),
                        name="paper_cost_net_r_scenarios_ordered",
                    ),
                ],
            },
        ),
        migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER),
    ]
