# Generated by Django 5.2.17 on 2026-08-20 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION reject_mutation_forecasts_positionsizeadvice()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'forecasts_positionsizeadvice is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER forecasts_positionsizeadvice_immutable
BEFORE UPDATE OR DELETE ON forecasts_positionsizeadvice
FOR EACH ROW EXECUTE FUNCTION reject_mutation_forecasts_positionsizeadvice();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS forecasts_positionsizeadvice_immutable
ON forecasts_positionsizeadvice;
DROP FUNCTION IF EXISTS reject_mutation_forecasts_positionsizeadvice();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0008_papertradecostassessment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionSizeAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policy_key", models.CharField(max_length=80)),
                ("policy_version", models.PositiveSmallIntegerField()),
                ("account_currency", models.CharField(default="CAD", max_length=3)),
                ("model_equity_cad", models.DecimalField(decimal_places=2, max_digits=14)),
                ("risk_fraction", models.DecimalField(decimal_places=6, max_digits=7)),
                ("setup_risk_cap_cad", models.DecimalField(decimal_places=2, max_digits=12)),
                ("aggregate_risk_cap_cad", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency_direction_risk_cap_cad",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("stop_distance_quote", models.DecimalField(decimal_places=6, max_digits=12)),
                ("quote_to_cad_rate", models.DecimalField(decimal_places=8, max_digits=18)),
                ("recommended_units", models.PositiveBigIntegerField()),
                ("projected_risk_cad", models.DecimalField(decimal_places=2, max_digits=12)),
                ("conversion_path", models.JSONField()),
                ("sized_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position_size",
                        to="forecasts.recommendation",
                    ),
                ),
            ],
            options={
                "ordering": ("-sized_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("model_equity_cad__gt", 0)),
                        name="position_size_model_equity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("risk_fraction__gt", 0), ("risk_fraction__lte", 1)),
                        name="position_size_risk_fraction_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("aggregate_risk_cap_cad__gte", models.F("setup_risk_cap_cad")),
                            (
                                "currency_direction_risk_cap_cad__gte",
                                models.F("setup_risk_cap_cad"),
                            ),
                            ("setup_risk_cap_cad__gt", 0),
                        ),
                        name="position_size_caps_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quote_to_cad_rate__gt", 0), ("stop_distance_quote__gt", 0)
                        ),
                        name="position_size_conversion_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("recommended_units__gt", 0)),
                        name="position_size_units_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("projected_risk_cad__gt", 0),
                            ("projected_risk_cad__lte", models.F("setup_risk_cap_cad")),
                        ),
                        name="position_size_projected_risk_within_cap",
                    ),
                ],
            },
        ),
        migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER),
    ]
