# Generated by Django 5.2.17 on 2026-08-20 22:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION reject_mutation_forecasts_paperlifecycleevent()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'forecasts_paperlifecycleevent is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER forecasts_paperlifecycleevent_immutable
BEFORE UPDATE OR DELETE ON forecasts_paperlifecycleevent
FOR EACH ROW EXECUTE FUNCTION reject_mutation_forecasts_paperlifecycleevent();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS forecasts_paperlifecycleevent_immutable
ON forecasts_paperlifecycleevent;
DROP FUNCTION IF EXISTS reject_mutation_forecasts_paperlifecycleevent();
"""


def classify_existing_recommendations(apps, schema_editor):
    Recommendation = apps.get_model("forecasts", "Recommendation")
    PaperLifecycleEvent = apps.get_model("forecasts", "PaperLifecycleEvent")
    PortfolioGuard = apps.get_model("forecasts", "PortfolioGuard")
    PortfolioGuard.objects.get_or_create(key="paper-portfolio")
    for recommendation in Recommendation.objects.all().iterator():
        if hasattr(recommendation, "paper_result"):
            state = "closed"
            reason = "existing_paper_result"
        elif hasattr(recommendation, "paper_entry"):
            state = "entered"
            reason = "existing_paper_entry"
        else:
            state = "legacy_unadjudicated"
            reason = "predates_prospective_admission"
        PaperLifecycleEvent.objects.create(
            recommendation_id=recommendation.pk,
            state=state,
            reason_code=reason,
            details={"backfilled_by": "forecasts.0010"},
            occurred_at=recommendation.generated_at,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0009_positionsizeadvice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("legacy_unadjudicated", "Legacy; not adjudicated"),
                            ("pending", "Waiting for entry"),
                            ("entered", "Entered"),
                            ("closed", "Closed"),
                            ("expired_unobserved", "Expired; coverage unavailable"),
                            ("cancelled", "Cancelled"),
                            ("missing_data", "Missing data"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=80)),
                ("details", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PortfolioGuard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
        migrations.AlterField(
            model_name="papertradecostassessment",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_assessments",
                to="forecasts.papertraderesult",
            ),
        ),
        migrations.AlterField(
            model_name="positionsizeadvice",
            name="recommendation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="position_sizes",
                to="forecasts.recommendation",
            ),
        ),
        migrations.AddConstraint(
            model_name="papertradecostassessment",
            constraint=models.UniqueConstraint(
                fields=("result", "policy_version"), name="unique_paper_cost_policy_assessment"
            ),
        ),
        migrations.AddConstraint(
            model_name="positionsizeadvice",
            constraint=models.UniqueConstraint(
                fields=("recommendation", "policy_key", "policy_version"),
                name="unique_position_size_policy_assessment",
            ),
        ),
        migrations.AddField(
            model_name="paperlifecycleevent",
            name="recommendation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paper_lifecycle_events",
                to="forecasts.recommendation",
            ),
        ),
        migrations.AddConstraint(
            model_name="paperlifecycleevent",
            constraint=models.UniqueConstraint(
                fields=("recommendation", "state"), name="unique_paper_lifecycle_state"
            ),
        ),
        migrations.RunPython(classify_existing_recommendations, migrations.RunPython.noop),
        migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER),
    ]
