# Generated by Django 5.2.17 on 2026-08-20 23:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

IMMUTABLE_TABLES = (
    "forecasts_portfoliocohort",
    "forecasts_portfoliocohortmember",
    "forecasts_portfolioselection",
    "forecasts_portfolioselectionmember",
    "forecasts_portfolioadmissionevent",
)


def classify_pre_admission_recommendations(apps, schema_editor):
    Recommendation = apps.get_model("forecasts", "Recommendation")
    PaperLifecycleEvent = apps.get_model("forecasts", "PaperLifecycleEvent")
    now = django.utils.timezone.now()
    for recommendation in Recommendation.objects.filter(
        contract_version=3,
        action__in=("buy", "sell"),
        portfolio_membership__isnull=True,
    ).iterator():
        PaperLifecycleEvent.objects.get_or_create(
            recommendation_id=recommendation.pk,
            state="cancelled",
            defaults={
                "reason_code": "predates_portfolio_admission_v1",
                "details": {"research_only": True, "backfilled_by": "forecasts.0011"},
                "occurred_at": max(now, recommendation.generated_at),
            },
        )


def create_immutability_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in IMMUTABLE_TABLES:
            function = f"reject_mutation_{table}"
            cursor.execute(
                f"""
                CREATE OR REPLACE FUNCTION {function}() RETURNS trigger AS $$
                BEGIN RAISE EXCEPTION '{table} is immutable'; END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table}
                FOR EACH ROW EXECUTE FUNCTION {function}();
                """
            )


def drop_immutability_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in IMMUTABLE_TABLES:
            cursor.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
            cursor.execute(f"DROP FUNCTION IF EXISTS reject_mutation_{table}()")


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0010_paperlifecycleevent_portfolioguard_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=240, unique=True)),
                ("policy_key", models.CharField(max_length=80)),
                ("policy_version", models.PositiveSmallIntegerField()),
                ("generated_at", models.DateTimeField()),
                ("capacity_snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-generated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PortfolioSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("automatic", "Automatic; all fit"), ("owner", "Owner selection")],
                        max_length=12,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=240, unique=True)),
                ("selected_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selections",
                        to="forecasts.portfoliocohort",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="forecasts.portfolioselection",
                    ),
                ),
            ],
            options={
                "ordering": ("-selected_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PortfolioAdmissionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("admitted", "Admitted to paper portfolio"),
                            ("revoked", "Admission revoked while pending"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason_code", models.CharField(max_length=80)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_admission_events",
                        to="forecasts.recommendation",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission_events",
                        to="forecasts.portfoliocohort",
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admission_events",
                        to="forecasts.portfolioselection",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="PortfolioCohortMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("projected_risk_cad", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency_legs", models.JSONField()),
                ("eligible", models.BooleanField(default=True)),
                ("reason_code", models.CharField(blank=True, max_length=80)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="forecasts.portfoliocohort",
                    ),
                ),
                (
                    "position_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forecasts.positionsizeadvice",
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_membership",
                        to="forecasts.recommendation",
                    ),
                ),
            ],
            options={
                "ordering": ("recommendation__instrument__display_order", "recommendation_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cohort", "recommendation"), name="unique_portfolio_cohort_member"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PortfolioSelectionMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="forecasts.recommendation"
                    ),
                ),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selected_members",
                        to="forecasts.portfolioselection",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("selection", "recommendation"),
                        name="unique_portfolio_selection_member",
                    )
                ],
            },
        ),
        migrations.RunPython(
            classify_pre_admission_recommendations,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(create_immutability_triggers, drop_immutability_triggers),
    ]
