# Generated by Django 5.2.17 on 2026-08-20 23:32

import django.utils.timezone
from django.db import migrations, models


def activate_policy(apps, schema_editor):
    PortfolioPolicyActivation = apps.get_model("forecasts", "PortfolioPolicyActivation")
    PortfolioPolicyActivation.objects.create(
        policy_key="fixed-cad-risk",
        policy_version=1,
        effective_at=django.utils.timezone.now(),
    )


CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION reject_mutation_forecasts_portfoliopolicyactivation()
RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'forecasts_portfoliopolicyactivation is immutable'; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER forecasts_portfoliopolicyactivation_immutable
BEFORE UPDATE OR DELETE ON forecasts_portfoliopolicyactivation
FOR EACH ROW EXECUTE FUNCTION reject_mutation_forecasts_portfoliopolicyactivation();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS forecasts_portfoliopolicyactivation_immutable
ON forecasts_portfoliopolicyactivation;
DROP FUNCTION IF EXISTS reject_mutation_forecasts_portfoliopolicyactivation();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0011_portfoliocohort_portfolioselection_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioPolicyActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policy_key", models.CharField(max_length=80)),
                ("policy_version", models.PositiveSmallIntegerField()),
                ("effective_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_key", "policy_version"),
                        name="unique_portfolio_policy_activation",
                    )
                ],
            },
        ),
        migrations.RunPython(activate_policy, migrations.RunPython.noop),
        migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER),
    ]
