# Generated by Django 5.2.17 on 2026-08-20 23:34

from django.db import migrations

IMMUTABLE_TABLES = (
    "forecasts_portfoliocohort",
    "forecasts_portfoliocohortmember",
    "forecasts_portfolioselection",
    "forecasts_portfolioselectionmember",
    "forecasts_portfolioadmissionevent",
    "forecasts_portfoliopolicyactivation",
)


def ensure_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in IMMUTABLE_TABLES:
            function = f"reject_mutation_{table}"
            cursor.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
            cursor.execute(
                f"""
                CREATE OR REPLACE FUNCTION {function}() RETURNS trigger AS $$
                BEGIN RAISE EXCEPTION '{table} is immutable'; END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table}
                FOR EACH ROW EXECUTE FUNCTION {function}();
                """
            )


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0012_portfoliopolicyactivation"),
    ]

    operations = [migrations.RunPython(ensure_triggers, migrations.RunPython.noop)]
