# Generated by Django 5.2.17 on 2026-08-21 04:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

IMMUTABLE_TABLES = (
    "forecasts_reviewcohort",
    "forecasts_reviewcohortmember",
    "forecasts_deterministicreview",
)


def create_immutability_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in IMMUTABLE_TABLES:
            function = f"reject_mutation_{table}"
            cursor.execute(
                f"""
                CREATE OR REPLACE FUNCTION {function}() RETURNS trigger AS $$
                BEGIN RAISE EXCEPTION '{table} is immutable'; END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table}
                FOR EACH ROW EXECUTE FUNCTION {function}();
                """
            )


def drop_immutability_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in IMMUTABLE_TABLES:
            cursor.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
            cursor.execute(f"DROP FUNCTION IF EXISTS reject_mutation_{table}()")


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0013_ensure_portfolio_immutability"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=240, unique=True)),
                ("method_key", models.CharField(max_length=80)),
                ("method_version", models.PositiveSmallIntegerField()),
                ("cutoff_at", models.DateTimeField()),
                ("membership_sha256", models.CharField(max_length=64, unique=True)),
                ("initial_coverage", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-cutoff_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ReviewCohortMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("inclusion_reason", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="forecasts.reviewcohort",
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_membership",
                        to="forecasts.recommendation",
                    ),
                ),
            ],
            options={
                "ordering": ("recommendation__instrument__display_order", "recommendation_id"),
            },
        ),
        migrations.CreateModel(
            name="DeterministicReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("thesis", "Thesis review"),
                            ("execution", "Execution review"),
                            ("reconciliation", "Combined reconciliation"),
                        ],
                        max_length=16,
                    ),
                ),
                ("method_key", models.CharField(max_length=80)),
                ("method_version", models.PositiveSmallIntegerField()),
                ("input_sha256", models.CharField(max_length=64)),
                (
                    "coverage",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("not_applicable", "Not applicable"),
                            ("missing", "Missing data"),
                        ],
                        max_length=16,
                    ),
                ),
                ("facts", models.JSONField()),
                ("source_lineage", models.JSONField()),
                ("assessed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="forecasts.deterministicreview",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="forecasts.reviewcohortmember",
                    ),
                ),
            ],
            options={
                "ordering": ("-assessed_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "kind", "input_sha256"),
                        name="unique_deterministic_review_input",
                    )
                ],
            },
        ),
        migrations.RunPython(create_immutability_triggers, drop_immutability_triggers),
    ]
