# Generated by Django 5.2.17 on 2026-08-21 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

IMMUTABLE_TABLES = (
    "forecasts_candidatehypothesis",
    "forecasts_learningobservation",
    "forecasts_challengerauthorization",
    "forecasts_interpretationmethod",
    "forecasts_interpretationattempt",
    "forecasts_candidatehypothesisobservation",
    "forecasts_reviewinterpretation",
    "forecasts_sourceproposal",
)


def create_immutability_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in IMMUTABLE_TABLES:
            function = f"reject_mutation_{table}"
            cursor.execute(
                f"""
                CREATE OR REPLACE FUNCTION {function}() RETURNS trigger AS $$
                BEGIN RAISE EXCEPTION '{table} is immutable'; END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table}
                FOR EACH ROW EXECUTE FUNCTION {function}();
                """
            )


def drop_immutability_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in IMMUTABLE_TABLES:
            cursor.execute(f"DROP TRIGGER IF EXISTS {table}_immutable ON {table}")
            cursor.execute(f"DROP FUNCTION IF EXISTS reject_mutation_{table}()")


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0014_deterministic_reviews"),
        ("operations", "0005_ownernotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateHypothesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pattern_key", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("statement", models.TextField()),
                ("proposed_change", models.TextField()),
                ("evaluation_plan", models.TextField()),
                ("issuance_cluster_keys", models.JSONField()),
                ("evidence_sha256", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="LearningObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("issuance_cluster_key", models.CharField(max_length=120)),
                ("pattern_key", models.SlugField(max_length=120)),
                ("title", models.CharField(max_length=200)),
                ("statement", models.TextField()),
                ("evidence_ids", models.JSONField(default=list)),
                ("proposed_change", models.TextField()),
                ("evaluation_plan", models.TextField()),
                ("non_actionable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ChallengerAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("authorized_not_started", "Authorized; not started")],
                        default="authorized_not_started",
                        max_length=24,
                    ),
                ),
                ("authorized_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challenger_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hypothesis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authorization",
                        to="forecasts.candidatehypothesis",
                    ),
                ),
            ],
            options={
                "ordering": ("-authorized_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="InterpretationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("method_key", models.CharField(max_length=80)),
                ("method_version", models.PositiveSmallIntegerField()),
                ("provider", models.CharField(max_length=80)),
                ("requested_model", models.CharField(max_length=120)),
                ("system_prompt_sha256", models.CharField(max_length=64)),
                ("output_schema_sha256", models.CharField(max_length=64)),
                ("pricing_version", models.CharField(max_length=80)),
                ("input_usd_per_mtok", models.DecimalField(decimal_places=4, max_digits=12)),
                ("output_usd_per_mtok", models.DecimalField(decimal_places=4, max_digits=12)),
                ("max_output_tokens", models.PositiveIntegerField()),
                ("rights_manifest", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("method_key", "method_version"),
                        name="unique_interpretation_method_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InterpretationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("packet_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected output"),
                            ("provider_failed", "Provider failed"),
                            ("budget_blocked", "Budget blocked"),
                            ("rights_blocked", "Rights blocked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("provider_response_id", models.CharField(blank=True, max_length=160)),
                ("returned_model", models.CharField(blank=True, max_length=120)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cost_usd", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("attempted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "budget_reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interpretation_attempts",
                        to="operations.providerbudgetreservation",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interpretation_attempts",
                        to="forecasts.reviewcohortmember",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="forecasts.interpretationmethod",
                    ),
                ),
            ],
            options={
                "ordering": ("-attempted_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CandidateHypothesisObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hypothesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observation_links",
                        to="forecasts.candidatehypothesis",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hypothesis_links",
                        to="forecasts.learningobservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidatehypothesis",
            name="observations",
            field=models.ManyToManyField(
                related_name="candidate_hypotheses",
                through="forecasts.CandidateHypothesisObservation",
                to="forecasts.learningobservation",
            ),
        ),
        migrations.CreateModel(
            name="ReviewInterpretation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_sha256", models.CharField(max_length=64, unique=True)),
                ("output", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interpretation",
                        to="forecasts.interpretationattempt",
                    ),
                ),
                (
                    "execution_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_interpretations",
                        to="forecasts.deterministicreview",
                    ),
                ),
                (
                    "reconciliation_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliation_interpretations",
                        to="forecasts.deterministicreview",
                    ),
                ),
                (
                    "thesis_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thesis_interpretations",
                        to="forecasts.deterministicreview",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="learningobservation",
            name="interpretation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observation",
                to="forecasts.reviewinterpretation",
            ),
        ),
        migrations.CreateModel(
            name="SourceProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(max_length=120)),
                ("use_case", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[("quarantined", "Quarantined")],
                        default="quarantined",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "interpretation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_proposals",
                        to="forecasts.reviewinterpretation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="interpretationattempt",
            constraint=models.UniqueConstraint(
                fields=("member", "method", "packet_sha256"), name="unique_interpretation_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidatehypothesisobservation",
            constraint=models.UniqueConstraint(
                fields=("hypothesis", "observation"), name="unique_candidate_hypothesis_observation"
            ),
        ),
        migrations.AddConstraint(
            model_name="learningobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("non_actionable", True)),
                name="learning_observation_non_actionable",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceproposal",
            constraint=models.UniqueConstraint(
                fields=("interpretation", "name", "category"),
                name="unique_interpretation_source_proposal",
            ),
        ),
        migrations.RunPython(create_immutability_triggers, drop_immutability_triggers),
    ]
