# Generated by Django 5.2.17 on 2026-09-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0016_reproducible_experiment_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="pricing_version",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="returned_model",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
