# Generated by Django 5.2.17 on 2026-09-09 00:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0017_recommendation_model_identity"),
        ("market", "0030_ingestion_eligibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliocohort",
            name="decision_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recommendationresolution",
            name="brier_score",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="recommendationresolution",
            name="endpoint_midpoint",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="recommendationresolution",
            name="horizon_candle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="market.candle",
            ),
        ),
        migrations.AlterField(
            model_name="recommendationresolution",
            name="midpoint_change",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="recommendationresolution",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("up", "Up"),
                    ("neutral", "Neutral"),
                    ("down", "Down"),
                    ("cancelled", "Cancelled"),
                    ("missing", "Missing data"),
                ],
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="CohortClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reason_code", models.CharField(max_length=80)),
                ("closed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cohort",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closure",
                        to="forecasts.portfoliocohort",
                    ),
                ),
                (
                    "superseding_cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_closures",
                        to="forecasts.portfoliocohort",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortfolioDisposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("reason_code", models.CharField(max_length=80)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_disposition",
                        to="forecasts.recommendation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TargetOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reference_content_sha256", models.CharField(max_length=64)),
                ("information_cutoff", models.DateTimeField()),
                ("reference_midpoint", models.DecimalField(decimal_places=6, max_digits=12)),
                ("neutral_band", models.DecimalField(decimal_places=6, max_digits=12)),
                ("horizon_sessions", models.PositiveSmallIntegerField()),
                ("resolution_method", models.CharField(max_length=80)),
                ("neutral_rule", models.CharField(max_length=80)),
                ("definition_sha256", models.CharField(max_length=64)),
                ("identity_sha256", models.CharField(max_length=64, unique=True)),
                ("registered_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
                (
                    "reference_candle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.candle"
                    ),
                ),
                (
                    "target_contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="forecasts.targetcontract"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="forecast",
            name="target_occurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="controls",
                to="forecasts.targetoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="target_occurrence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recommendations",
                to="forecasts.targetoccurrence",
            ),
        ),
        migrations.CreateModel(
            name="TargetResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("outcome", models.CharField(max_length=12)),
                ("horizon_content_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "endpoint_midpoint",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                (
                    "midpoint_change",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ("resolution_method", models.CharField(max_length=80)),
                ("details", models.JSONField(default=dict)),
                ("resolved_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("idempotency_key", models.CharField(max_length=100, unique=True)),
                (
                    "horizon_candle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="market.candle",
                    ),
                ),
                (
                    "target",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolution",
                        to="forecasts.targetoccurrence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="forecastresolution",
            name="target_resolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="forecasts.targetresolution",
            ),
        ),
        migrations.AddField(
            model_name="recommendationresolution",
            name="target_resolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="forecasts.targetresolution",
            ),
        ),
        migrations.CreateModel(
            name="RecommendationLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("state", models.CharField(max_length=40)),
                ("reason_code", models.CharField(max_length=80)),
                ("source_type", models.CharField(max_length=80)),
                ("source_id", models.PositiveBigIntegerField()),
                ("details", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successor",
                        to="forecasts.recommendationlifecycleevent",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_events",
                        to="forecasts.recommendation",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("predecessor__isnull", True)),
                        fields=("recommendation",),
                        name="unique_lifecycle_root",
                    )
                ],
            },
        ),
    ]
