# Generated by Django 5.2.17 on 2026-08-19 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("market", "0003_candle_candle_bid_ohlc_valid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawRetrieval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("fetched_at", models.DateTimeField()),
                ("http_status", models.PositiveSmallIntegerField()),
                ("content_type", models.CharField(max_length=120)),
                ("byte_count", models.PositiveIntegerField()),
                ("body_sha256", models.CharField(max_length=64)),
                ("body", models.BinaryField()),
                ("etag", models.CharField(blank=True, max_length=500)),
                ("last_modified", models.CharField(blank=True, max_length=200)),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("quarantined", "Quarantined"),
                            ("rejected", "Rejected"),
                        ],
                        default="accepted",
                        max_length=16,
                    ),
                ),
                ("quality_reason", models.TextField(blank=True)),
                ("retention_decision", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-fetched_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ResearchDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("canonical_url", models.URLField(max_length=1000)),
                ("canonical_hash", models.CharField(max_length=64, unique=True)),
                ("title", models.TextField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("first_observed_at", models.DateTimeField()),
                ("language", models.CharField(default="en", max_length=12)),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("verified", "Verified timestamp"),
                            ("quarantined", "Quarantined"),
                            ("conflict", "Conflict"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quality_reason", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("-published_at", "-first_observed_at"),
            },
        ),
        migrations.CreateModel(
            name="ResearchDiscrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("duplicate", "Duplicate"),
                            ("conflict", "Conflict"),
                            ("revision", "Revision"),
                        ],
                        max_length=12,
                    ),
                ),
                ("entity_key", models.CharField(max_length=240)),
                ("detail", models.JSONField(default=dict)),
                ("observed_at", models.DateTimeField()),
                (
                    "earlier_retrieval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earlier_discrepancies",
                        to="research.rawretrieval",
                    ),
                ),
                (
                    "later_retrieval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="later_discrepancies",
                        to="research.rawretrieval",
                    ),
                ),
            ],
            options={
                "ordering": ("-observed_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentRepresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_item_id", models.TextField()),
                ("dedup_key", models.CharField(max_length=64, unique=True)),
                ("source_title", models.TextField()),
                ("source_published_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "retrieval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_representations",
                        to="research.rawretrieval",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="representations",
                        to="research.researchdocument",
                    ),
                ),
            ],
            options={
                "ordering": ("-source_published_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="SourcePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("jurisdiction", models.CharField(max_length=2)),
                ("currency", models.CharField(max_length=3)),
                ("allowed_hosts", models.JSONField(default=list)),
                ("allowed_content_types", models.JSONField(default=list)),
                ("max_response_bytes", models.PositiveIntegerField(default=2000000)),
                ("rights_url", models.URLField()),
                ("rights_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "retention_class",
                    models.CharField(default="official-public-record", max_length=40),
                ),
                ("full_text_allowed", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("quarantined", "Quarantined"),
                            ("disabled", "Disabled"),
                        ],
                        default="quarantined",
                        max_length=16,
                    ),
                ),
                ("quality_note", models.TextField(blank=True)),
                (
                    "source",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy",
                        to="market.sourceregistry",
                    ),
                ),
            ],
            options={
                "ordering": ("jurisdiction", "source__name"),
            },
        ),
        migrations.AddField(
            model_name="rawretrieval",
            name="source_policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="research.sourcepolicy"
            ),
        ),
        migrations.CreateModel(
            name="MacroSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=80, unique=True)),
                ("provider_series_id", models.CharField(max_length=160)),
                ("label", models.CharField(max_length=240)),
                ("unit", models.CharField(max_length=40)),
                ("frequency", models.CharField(max_length=40)),
                (
                    "parser",
                    models.CharField(
                        choices=[
                            ("boc_valet", "Bank of Canada Valet JSON"),
                            ("fred_csv", "FRED CSV"),
                            ("ecb_csv", "ECB Data API CSV"),
                            ("boe_csv", "Bank of England IADB CSV"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("enabled", models.BooleanField(default=True)),
                ("point_in_time_note", models.TextField()),
                (
                    "source_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.sourcepolicy"
                    ),
                ),
            ],
            options={
                "ordering": ("source_policy__jurisdiction", "label"),
            },
        ),
        migrations.CreateModel(
            name="MacroObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("observation_period", models.DateField()),
                ("value", models.DecimalField(decimal_places=8, max_digits=24)),
                ("normalized_value", models.CharField(max_length=80)),
                ("available_at", models.DateTimeField()),
                ("vintage_at", models.DateTimeField()),
                ("revision_sequence", models.PositiveIntegerField(default=0)),
                (
                    "availability_precision",
                    models.CharField(
                        choices=[
                            ("provider", "Provider timestamp"),
                            ("retrieval", "First known at retrieval"),
                        ],
                        default="retrieval",
                        max_length=12,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="research.macroseries",
                    ),
                ),
                (
                    "retrieval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.rawretrieval"
                    ),
                ),
            ],
            options={
                "ordering": ("-observation_period", "-revision_sequence"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("series", "observation_period", "normalized_value"),
                        name="unique_macro_series_period_value",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="rawretrieval",
            index=models.Index(
                fields=["source_policy", "-fetched_at"], name="research_ra_source__783e0b_idx"
            ),
        ),
    ]
