# Generated by Django 5.2.17 on 2026-08-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0002_immutable_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category", models.CharField(max_length=80)),
                ("provider", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("testing", "Testing"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                        ],
                        default="candidate",
                        max_length=12,
                    ),
                ),
                ("evidence_url", models.URLField()),
                ("pricing_status", models.CharField(max_length=120)),
                ("timestamp_semantics", models.CharField(max_length=240)),
                ("revision_support", models.CharField(max_length=240)),
                ("retention_rights", models.CharField(max_length=240)),
                ("reliability_result", models.CharField(max_length=240)),
                ("next_check", models.TextField()),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("category", "provider"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "provider"), name="unique_research_provider_evaluation"
                    )
                ],
            },
        ),
    ]
