# Generated by Django 5.2.17 on 2026-08-19 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0003_providerevaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="macroobservation",
            name="provider_status",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="macroseries",
            name="indicator",
            field=models.CharField(
                choices=[
                    ("policy_rate", "Policy rate"),
                    ("cpi", "Inflation"),
                    ("unemployment", "Unemployment"),
                    ("gdp", "GDP growth"),
                    ("housing", "Housing"),
                ],
                default="policy_rate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="macroseries",
            name="request_method",
            field=models.CharField(
                choices=[("GET", "GET"), ("POST", "POST")], default="GET", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="macroseries",
            name="request_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="macroseries",
            name="transformation",
            field=models.CharField(
                choices=[("none", "None"), ("year_over_year", "Year-over-year percent change")],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="macroseries",
            name="parser",
            field=models.CharField(
                choices=[
                    ("boc_valet", "Bank of Canada Valet JSON"),
                    ("fred_csv", "FRED CSV"),
                    ("ecb_csv", "ECB Data API CSV"),
                    ("boe_csv", "Bank of England IADB CSV"),
                    ("statcan_wds", "Statistics Canada WDS JSON"),
                    ("bls_json", "US BLS JSON"),
                    ("ons_csv", "UK ONS generator CSV"),
                    ("eurostat_json", "Eurostat JSON-stat"),
                    ("land_registry_csv", "UK HPI linked-data CSV"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EconomicEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider_event_key", models.CharField(max_length=64)),
                ("event_at", models.DateTimeField()),
                ("country", models.CharField(max_length=2)),
                ("event_type", models.CharField(max_length=240)),
                ("comparison", models.CharField(blank=True, max_length=12)),
                ("period", models.CharField(blank=True, max_length=40)),
                ("actual", models.DecimalField(decimal_places=8, max_digits=24, null=True)),
                ("estimate", models.DecimalField(decimal_places=8, max_digits=24, null=True)),
                ("previous", models.DecimalField(decimal_places=8, max_digits=24, null=True)),
                ("payload_fingerprint", models.CharField(max_length=64)),
                ("first_observed_at", models.DateTimeField()),
                (
                    "retrieval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.rawretrieval"
                    ),
                ),
            ],
            options={
                "ordering": ("-event_at", "country", "event_type"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_event_key", "payload_fingerprint"),
                        name="unique_economic_event_vintage",
                    )
                ],
            },
        ),
    ]
