# Generated by Django 5.2.17 on 2026-08-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0005_immutable_economic_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="macroseries",
            name="parser",
            field=models.CharField(
                choices=[
                    ("boc_valet", "Bank of Canada Valet JSON"),
                    ("fred_csv", "FRED CSV"),
                    ("ecb_csv", "ECB Data API CSV"),
                    ("boe_csv", "Bank of England IADB CSV"),
                    ("statcan_wds", "Statistics Canada WDS JSON"),
                    ("bls_json", "US BLS JSON"),
                    ("ons_csv", "UK ONS generator CSV"),
                    ("eurostat_json", "Eurostat JSON-stat"),
                    ("land_registry_csv", "UK HPI linked-data CSV"),
                    ("statcan_zip", "Statistics Canada bounded table ZIP"),
                ],
                max_length=20,
            ),
        ),
    ]
