# Generated by Django 5.2.17 on 2026-08-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0006_alter_macroseries_parser"),
    ]

    operations = [
        migrations.AddField(
            model_name="economicevent",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="release_events",
                to="research.macroseries",
            ),
        ),
        migrations.AddField(
            model_name="economicevent",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="economicevent",
            name="status",
            field=models.CharField(default="scheduled", max_length=24),
        ),
        migrations.AddField(
            model_name="economicevent",
            name="time_precision",
            field=models.CharField(
                choices=[("exact", "Exact time"), ("date", "Date only")],
                default="exact",
                max_length=8,
            ),
        ),
    ]
