# Generated by Django 5.2.17 on 2026-08-20 02:03

import django.db.models.deletion
from django.db import migrations, models

CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION reject_mutation_research_pairevidencesnapshot()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'research_pairevidencesnapshot is immutable';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER research_pairevidencesnapshot_immutable
BEFORE UPDATE OR DELETE ON research_pairevidencesnapshot
FOR EACH ROW EXECUTE FUNCTION reject_mutation_research_pairevidencesnapshot();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS research_pairevidencesnapshot_immutable
ON research_pairevidencesnapshot;
DROP FUNCTION IF EXISTS reject_mutation_research_pairevidencesnapshot();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_candle_candle_bid_ohlc_valid_and_more"),
        ("research", "0007_economicevent_series_economicevent_source_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="macroseries",
            name="indicator",
            field=models.CharField(
                choices=[
                    ("policy_rate", "Policy rate"),
                    ("cpi", "Inflation"),
                    ("unemployment", "Unemployment"),
                    ("gdp", "GDP growth"),
                    ("housing", "Housing"),
                    ("equity", "Equity market"),
                    ("volatility", "Market volatility"),
                    ("crypto", "Cryptoasset"),
                    ("commodity", "Commodity"),
                    ("yield", "Government yield"),
                    ("dollar", "US dollar index"),
                ],
                default="policy_rate",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="macroseries",
            name="parser",
            field=models.CharField(
                choices=[
                    ("boc_valet", "Bank of Canada Valet JSON"),
                    ("fred_csv", "FRED CSV"),
                    ("ecb_csv", "ECB Data API CSV"),
                    ("boe_csv", "Bank of England IADB CSV"),
                    ("statcan_wds", "Statistics Canada WDS JSON"),
                    ("bls_json", "US BLS JSON"),
                    ("ons_csv", "UK ONS generator CSV"),
                    ("eurostat_json", "Eurostat JSON-stat"),
                    ("land_registry_csv", "UK HPI linked-data CSV"),
                    ("statcan_zip", "Statistics Canada bounded table ZIP"),
                    ("date_value_csv", "Date/value CSV"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PairEvidenceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("information_cutoff", models.DateTimeField()),
                ("payload", models.JSONField()),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("captured_at", models.DateTimeField()),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_evidence_snapshots",
                        to="market.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ("-captured_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["instrument", "-captured_at"], name="research_pa_instrum_322848_idx"
                    )
                ],
            },
        ),
        migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER),
    ]
