# Generated by Django 5.2.17 on 2026-08-27 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0007_phase_2a_append_only_triggers"),
        ("operations", "0005_ownernotification"),
        ("research", "0008_pair_evidence_intermarket"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.CharField(max_length=80)),
                ("detector_version", models.CharField(max_length=80)),
                ("data_identity", models.CharField(max_length=160)),
                ("event_identity", models.CharField(max_length=160)),
                ("execution_identity", models.CharField(max_length=160)),
                ("cost_identity", models.CharField(max_length=160)),
                ("portfolio_identity", models.CharField(max_length=160)),
                ("pair_metadata", models.JSONField(default=dict)),
                ("timeframe_metadata", models.JSONField(default=dict)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research.strategydefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrategyParameterManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("payload", models.JSONField()),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("phase1_spec_hash", models.CharField(max_length=64)),
                ("phase1_manifest_hash", models.CharField(max_length=64)),
                (
                    "strategy_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="research.strategyversion"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SetupEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(choices=[("long", "Long"), ("short", "Short")], max_length=5),
                ),
                ("sweep_h1_timestamp", models.DateTimeField()),
                ("detector_version", models.CharField(max_length=80)),
                ("sweep_evidence", models.JSONField()),
                ("bias_evidence", models.JSONField()),
                ("provisional_swing_evidence", models.JSONField()),
                ("threshold_evidence", models.JSONField()),
                ("evidence_hash", models.CharField(max_length=64)),
                (
                    "initial_state",
                    models.CharField(
                        choices=[("TRIGGER_PENDING", "Trigger pending")],
                        default="TRIGGER_PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "dataset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.datasetversion"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.strategyversion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "family",
                    models.CharField(
                        choices=[
                            ("PREVIOUS_WEEKLY_EXTREME", "Previous weekly extreme"),
                            ("CONFIRMED_DAILY_SWING", "Confirmed daily swing"),
                            ("TWENTY_SESSION_BREAKOUT_FLIP", "Twenty-session breakout flip"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("support", "Support"), ("resistance", "Resistance")],
                        max_length=12,
                    ),
                ),
                ("source_timeframe", models.CharField(max_length=8)),
                ("source_candle_timestamp", models.DateTimeField()),
                ("central_price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("zone_lower", models.DecimalField(decimal_places=10, max_digits=20)),
                ("zone_upper", models.DecimalField(decimal_places=10, max_digits=20)),
                ("atr_at_activation", models.DecimalField(decimal_places=10, max_digits=20)),
                ("activated_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("stable_key", models.CharField(max_length=64, unique=True)),
                (
                    "dataset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.datasetversion"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.strategyversion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("job_name", models.CharField(max_length=120)),
                ("config_hash", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("as_of", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("data_incomplete", "Data incomplete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                (
                    "dataset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.datasetversion"
                    ),
                ),
                (
                    "occurrence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.joboccurrence",
                    ),
                ),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.strategyversion"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("completed_h1_timestamp", models.DateTimeField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("NO_SETUP", "No setup"),
                            ("LEVEL_ACTIVE", "Level active"),
                            ("CANDIDATE_CREATED", "Candidate created"),
                            ("DATA_INCOMPLETE", "Data incomplete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evidence_hash", models.CharField(max_length=64)),
                (
                    "dataset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.datasetversion"
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
                (
                    "strategy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.strategyversion"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LevelLifecycleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("invalidated", "Invalidated"),
                            ("expired", "Expired"),
                            ("superseded", "Superseded"),
                            ("superseded_by_flip", "Superseded by flip"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effective_at", models.DateTimeField()),
                ("evidence", models.JSONField(default=dict)),
                ("evidence_hash", models.CharField(max_length=64)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.level"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level", "state", "effective_at", "evidence_hash"),
                        name="unique_level_lifecycle_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LevelProximityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("approaching", "Approaching"), ("touched", "Touched")],
                        max_length=12,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("observation_bucket", models.DateTimeField()),
                ("evidence_hash", models.CharField(max_length=64)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.level"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level", "kind", "observation_bucket"),
                        name="unique_level_proximity_bucket",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntryEligibilityEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("book_identity", models.CharField(max_length=160)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("ENTRY_PENDING", "Entry pending"),
                            ("MISSED_FILL", "Missed fill"),
                            ("BLOCKED_SESSION", "Blocked session"),
                            ("BLOCKED_SPREAD", "Blocked spread"),
                            ("NO_TARGET", "No target"),
                            ("INSUFFICIENT_REWARD", "Insufficient reward"),
                            ("CANCELLED_DATA_QUALITY", "Cancelled data quality"),
                        ],
                        max_length=24,
                    ),
                ),
                ("terminal_reason", models.CharField(blank=True, max_length=240)),
                ("entry_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "entry_price",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "stop_price",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "target_price",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
                ),
                (
                    "reward_risk",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("evidence_hash", models.CharField(max_length=64)),
                (
                    "target_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entry_evaluations",
                        to="research.level",
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.setupevent"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("setup", "book_identity"), name="unique_setup_book_eligibility"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("decision", "ENTRY_PENDING"),
                                ("entry_price__isnull", False),
                                ("entry_timestamp__isnull", False),
                                ("reward_risk__isnull", False),
                                ("stop_price__isnull", False),
                                ("target_level__isnull", False),
                                ("target_price__isnull", False),
                                ("terminal_reason", ""),
                            ),
                            models.Q(
                                (
                                    "decision__in",
                                    (
                                        "MISSED_FILL",
                                        "BLOCKED_SESSION",
                                        "BLOCKED_SPREAD",
                                        "NO_TARGET",
                                        "INSUFFICIENT_REWARD",
                                        "CANCELLED_DATA_QUALITY",
                                    ),
                                ),
                                ("entry_price__isnull", True),
                                ("entry_timestamp__isnull", True),
                                ("reward_risk__isnull", True),
                                ("stop_price__isnull", True),
                                ("target_level__isnull", True),
                                ("target_price__isnull", True),
                                ("terminal_reason__gt", ""),
                            ),
                            _connector="OR",
                        ),
                        name="eligibility_fields_match_decision",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SetupLevelAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.level"
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.setupevent"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("setup", "level"), name="unique_setup_level_attribution"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SetupTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("TRIGGER_PENDING", "Trigger pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("ENTRY_PENDING", "Entry pending"),
                            ("INVALIDATED", "Invalidated"),
                            ("EXPIRED", "Expired"),
                            ("MISSED_FILL", "Missed fill"),
                            ("BLOCKED_SESSION", "Blocked session"),
                            ("BLOCKED_SPREAD", "Blocked spread"),
                            ("NO_TARGET", "No target"),
                            ("INSUFFICIENT_REWARD", "Insufficient reward"),
                            ("CANCELLED_DATA_QUALITY", "Cancelled data quality"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("TRIGGER_PENDING", "Trigger pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("ENTRY_PENDING", "Entry pending"),
                            ("INVALIDATED", "Invalidated"),
                            ("EXPIRED", "Expired"),
                            ("MISSED_FILL", "Missed fill"),
                            ("BLOCKED_SESSION", "Blocked session"),
                            ("BLOCKED_SPREAD", "Blocked spread"),
                            ("NO_TARGET", "No target"),
                            ("INSUFFICIENT_REWARD", "Insufficient reward"),
                            ("CANCELLED_DATA_QUALITY", "Cancelled data quality"),
                        ],
                        max_length=24,
                    ),
                ),
                ("effective_at", models.DateTimeField()),
                ("evidence", models.JSONField(default=dict)),
                ("evidence_hash", models.CharField(max_length=64)),
                ("reason", models.CharField(blank=True, max_length=240)),
                (
                    "job_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research.jobrun",
                    ),
                ),
                (
                    "setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.setupevent"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("setup", "from_state", "to_state", "effective_at"),
                        name="unique_setup_transition",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("from_state", "TRIGGER_PENDING"),
                                (
                                    "to_state__in",
                                    (
                                        "CONFIRMED",
                                        "INVALIDATED",
                                        "EXPIRED",
                                        "CANCELLED_DATA_QUALITY",
                                    ),
                                ),
                            ),
                            models.Q(
                                ("from_state", "CONFIRMED"),
                                (
                                    "to_state__in",
                                    (
                                        "ENTRY_PENDING",
                                        "MISSED_FILL",
                                        "BLOCKED_SESSION",
                                        "BLOCKED_SPREAD",
                                        "NO_TARGET",
                                        "INSUFFICIENT_REWARD",
                                        "CANCELLED_DATA_QUALITY",
                                    ),
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="valid_phase2a_setup_transition",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="strategyversion",
            constraint=models.UniqueConstraint(
                fields=("definition", "version"), name="unique_strategy_definition_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="setupevent",
            constraint=models.UniqueConstraint(
                fields=(
                    "instrument",
                    "direction",
                    "sweep_h1_timestamp",
                    "detector_version",
                    "dataset_version",
                ),
                name="unique_physical_setup_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.CheckConstraint(
                condition=models.Q(("zone_lower__lte", models.F("central_price"))),
                name="level_low_lte_central",
            ),
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.CheckConstraint(
                condition=models.Q(("central_price__lte", models.F("zone_upper"))),
                name="level_central_lte_high",
            ),
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.CheckConstraint(
                condition=models.Q(("atr_at_activation__gt", 0)), name="level_atr_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.UniqueConstraint(
                fields=(
                    "instrument",
                    "completed_h1_timestamp",
                    "strategy_version",
                    "dataset_version",
                ),
                name="unique_analysis_instrument_h1_strategy_dataset",
            ),
        ),
    ]
