# Generated by Django 5.2.17 on 2026-08-27 15:20

from importlib import import_module

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

_migration_helpers = import_module("research.migrations.0011_phase_2a_review_corrections")
create_migration_write_guard = _migration_helpers.create_migration_write_guard
drop_migration_write_guard = _migration_helpers.drop_migration_write_guard


def assert_migrated_lineage(apps, schema_editor):
    Transition = apps.get_model("research", "SetupTransition")
    for transition in Transition.objects.select_related("setup__strategy_version", "job_run"):
        setup = transition.setup
        if (
            transition.strategy_version_id != setup.strategy_version_id
            or transition.dataset_version_id != setup.dataset_version_id
            or transition.execution_identity != setup.strategy_version.execution_identity
            or (
                transition.job_run_id
                and (
                    transition.job_run.strategy_version_id != setup.strategy_version_id
                    or transition.job_run.dataset_version_id != setup.dataset_version_id
                )
            )
        ):
            raise RuntimeError("migrated transition lineage conflicts with setup")


def create_lineage_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE FUNCTION research_validate_setup_transition() RETURNS trigger AS $$
        DECLARE
            setup_strategy bigint;
            setup_dataset bigint;
            setup_execution text;
            job_strategy bigint;
            job_dataset bigint;
        BEGIN
            SELECT setup.strategy_version_id, setup.dataset_version_id,
                   strategy.execution_identity
              INTO setup_strategy, setup_dataset, setup_execution
              FROM research_setupevent setup
              JOIN research_strategyversion strategy
                ON strategy.id = setup.strategy_version_id
             WHERE setup.id = NEW.setup_id;
            IF NEW.strategy_version_id <> setup_strategy
               OR NEW.dataset_version_id <> setup_dataset
               OR NEW.execution_identity <> setup_execution THEN
                RAISE EXCEPTION 'setup transition lineage conflicts with setup';
            END IF;
            IF NEW.job_run_id IS NOT NULL THEN
                SELECT strategy_version_id, dataset_version_id
                  INTO job_strategy, job_dataset
                  FROM research_jobrun WHERE id = NEW.job_run_id;
                IF job_strategy <> setup_strategy OR job_dataset <> setup_dataset THEN
                    RAISE EXCEPTION 'setup transition job lineage conflicts with setup';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER research_setup_transition_validate
        BEFORE INSERT ON research_setuptransition
        FOR EACH ROW EXECUTE FUNCTION research_validate_setup_transition();

        CREATE FUNCTION research_validate_entry_target() RETURNS trigger AS $$
        DECLARE
            level_key text;
            level_lower numeric;
            level_upper numeric;
            level_instrument bigint;
            level_strategy bigint;
            level_dataset bigint;
            level_role text;
            setup_direction text;
            setup_instrument bigint;
            setup_strategy bigint;
            setup_dataset bigint;
        BEGIN
            IF NEW.decision = 'ENTRY_PENDING' THEN
                SELECT stable_key, zone_lower, zone_upper, instrument_id,
                       strategy_version_id, dataset_version_id, role
                  INTO level_key, level_lower, level_upper, level_instrument,
                       level_strategy, level_dataset, level_role
                  FROM research_level WHERE id = NEW.target_level_id;
                SELECT direction, instrument_id, strategy_version_id, dataset_version_id
                  INTO setup_direction, setup_instrument, setup_strategy, setup_dataset
                  FROM research_setupevent WHERE id = NEW.setup_id;
                IF NEW.target_stable_key <> level_key
                   OR level_instrument <> setup_instrument
                   OR level_strategy <> setup_strategy
                   OR level_dataset <> setup_dataset
                   OR (setup_direction = 'long' AND level_role <> 'resistance')
                   OR (setup_direction = 'short' AND level_role <> 'support')
                   OR (setup_direction = 'long' AND NEW.target_price <> level_lower)
                   OR (setup_direction = 'short' AND NEW.target_price <> level_upper) THEN
                    RAISE EXCEPTION 'entry target conflicts with frozen level boundary or lineage';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER research_entry_target_validate
        BEFORE INSERT ON research_entryeligibilityevaluation
        FOR EACH ROW EXECUTE FUNCTION research_validate_entry_target();
        """
    )


def drop_lineage_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS research_setup_transition_validate
          ON research_setuptransition;
        DROP FUNCTION IF EXISTS research_validate_setup_transition();
        DROP TRIGGER IF EXISTS research_entry_target_validate
          ON research_entryeligibilityevaluation;
        DROP FUNCTION IF EXISTS research_validate_entry_target();
        """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0008_reject_governed_candle_promotion"),
        ("research", "0012_enforce_phase_2a_lineage"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryeligibilityevaluation",
            name="target_stable_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="analysisrun",
            name="detector_version",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="setuptransition",
            name="dataset_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="market.datasetversion"
            ),
        ),
        migrations.AlterField(
            model_name="setuptransition",
            name="decision_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="setuptransition",
            name="execution_identity",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="setuptransition",
            name="strategy_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="research.strategyversion"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisrun",
            constraint=models.UniqueConstraint(
                fields=(
                    "instrument",
                    "completed_h1_timestamp",
                    "detector_version",
                    "dataset_version",
                ),
                name="unique_analysis_instrument_h1_detector_dataset",
            ),
        ),
        migrations.AddConstraint(
            model_name="entryeligibilityevaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("conversion_effective_at__isnull", False),
                        ("conversion_identity__gt", ""),
                        ("conversion_rate_to_cad__isnull", False),
                        ("decision", "ENTRY_PENDING"),
                        ("entry_price__isnull", False),
                        ("entry_timestamp__isnull", False),
                        ("reward_risk__isnull", False),
                        ("risk_per_unit_cad__isnull", False),
                        ("risk_per_unit_quote__isnull", False),
                        ("stop_price__isnull", False),
                        ("target_level__isnull", False),
                        ("target_price__isnull", False),
                        ("target_stable_key__gt", ""),
                        ("terminal_reason", ""),
                    ),
                    models.Q(
                        ("conversion_effective_at__isnull", True),
                        ("conversion_identity", ""),
                        ("conversion_rate_to_cad__isnull", True),
                        (
                            "decision__in",
                            (
                                "MISSED_FILL",
                                "BLOCKED_SESSION",
                                "BLOCKED_SPREAD",
                                "NO_TARGET",
                                "INSUFFICIENT_REWARD",
                                "CANCELLED_DATA_QUALITY",
                            ),
                        ),
                        ("entry_price__isnull", True),
                        ("entry_timestamp__isnull", True),
                        ("reward_risk__isnull", True),
                        ("risk_per_unit_cad__isnull", True),
                        ("risk_per_unit_quote__isnull", True),
                        ("stop_price__isnull", True),
                        ("target_level__isnull", True),
                        ("target_price__isnull", True),
                        ("target_stable_key", ""),
                        ("terminal_reason__gt", ""),
                    ),
                    _connector="OR",
                ),
                name="eligibility_fields_match_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="setuptransition",
            constraint=models.UniqueConstraint(
                fields=("setup", "from_state", "book_identity"),
                name="unique_setup_outgoing_transition",
            ),
        ),
        migrations.AddConstraint(
            model_name="setuptransition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("book_identity", ""),
                        ("from_state", "TRIGGER_PENDING"),
                        (
                            "to_state__in",
                            ("CONFIRMED", "INVALIDATED", "EXPIRED", "CANCELLED_DATA_QUALITY"),
                        ),
                    ),
                    models.Q(
                        ("book_identity__gt", ""),
                        ("from_state", "CONFIRMED"),
                        (
                            "to_state__in",
                            (
                                "ENTRY_PENDING",
                                "MISSED_FILL",
                                "BLOCKED_SESSION",
                                "BLOCKED_SPREAD",
                                "NO_TARGET",
                                "INSUFFICIENT_REWARD",
                                "CANCELLED_DATA_QUALITY",
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="valid_phase2a_setup_transition",
            ),
        ),
        migrations.RunPython(assert_migrated_lineage, migrations.RunPython.noop),
        migrations.RunPython(create_lineage_triggers, drop_lineage_triggers),
        migrations.RunPython(drop_migration_write_guard, create_migration_write_guard),
    ]
