# Generated by Django 5.2.17 on 2026-09-11 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0041_simulation_evidence_admission"),
        ("research", "0015_pre_s1_inventory_entry_boundary"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvidenceIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                (
                    "conflict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.evidenceconflict"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvidenceRightsReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.sourceregistry"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExactEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                (
                    "document",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research.researchdocument",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research.macroobservation",
                    ),
                ),
                (
                    "retrieval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="research.rawretrieval"
                    ),
                ),
                (
                    "storage_review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research.evidencerightsreview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="evidenceconflict",
            name="earlier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="later_changes",
                to="research.exactevidence",
            ),
        ),
        migrations.AddField(
            model_name="evidenceconflict",
            name="later",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="earlier_changes",
                to="research.exactevidence",
            ),
        ),
        migrations.CreateModel(
            name="FrozenEvidencePacket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cutoff", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="market.instrument"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
