# Generated by Django 5.2.17 on 2026-09-11 16:29

from importlib import import_module

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

METHOD_SHA256 = "806b8ed616ae3e0d2758e38758e34539b4c5a266439dae09e5bc9b59a7e226b0"
PRIOR_CONTEXT = import_module("research.migrations.0021_phase7_context_guards")
OLD_CONTEXT = PRIOR_CONTEXT.SQL.split("CREATE TRIGGER", 1)[0].replace(
    "CREATE FUNCTION", "CREATE OR REPLACE FUNCTION"
)
OLD_CONFLICTS = import_module(
    "research.migrations.0019_phase7_legacy_conflict_coverage"
).SQL.replace("CREATE FUNCTION", "CREATE OR REPLACE FUNCTION")

SQL = r"""
CREATE FUNCTION phase7_source_provenance() RETURNS trigger LANGUAGE plpgsql
SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE o research_macroobservation; expected text;
BEGIN
 NEW.admitted_macro_label := NULL;
 IF NEW.observation_id IS NOT NULL THEN
  SELECT * INTO STRICT o FROM research_macroobservation WHERE id=NEW.observation_id;
  SELECT label INTO STRICT NEW.admitted_macro_label FROM research_macroseries WHERE id=o.series_id;
  expected := CASE o.availability_precision WHEN 'provider' THEN 'provider_exact'
   WHEN 'retrieval' THEN 'retrieval_only' ELSE 'unknown' END;
  PERFORM phase7_assert(NEW.payload->>'headline'=NEW.admitted_macro_label
   AND NEW.payload->>'supplied_summary'=''
   AND NEW.payload->'quality'->>'timestamp_precision' IN (expected,'unknown'));
 END IF;
 RETURN NEW;
END; $$;
CREATE TRIGGER phase7_source_provenance BEFORE INSERT ON research_exactevidence
FOR EACH ROW EXECUTE FUNCTION phase7_source_provenance();

CREATE FUNCTION phase7_legacy_insert() RETURNS trigger LANGUAGE plpgsql
SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE d research_researchdiscrepancy; p jsonb:=NEW.payload;
BEGIN
 SELECT * INTO STRICT d FROM research_researchdiscrepancy WHERE id=NEW.discrepancy_id;
 NEW.recorded_at := clock_timestamp();
 PERFORM phase7_assert(NEW.digest=market_state_digest(p)
  AND phase7_keys(p,ARRAY['version','discrepancy_id','document','legacy_observed_at','historical_arrival'])
  AND p->>'version'='evidence-quality-v1' AND (p->>'discrepancy_id')::bigint=d.id
  AND d.kind='conflict' AND d.entity_key='document:'||(p->>'document')
  AND p->>'document' ~ '^[a-f0-9]{64}$'
  AND (p->>'legacy_observed_at')::timestamptz=d.observed_at
  AND p->>'historical_arrival'='unknown');
 RETURN NEW;
END; $$;
CREATE TRIGGER phase7_a_lock BEFORE INSERT ON research_evidencelegacyadmission FOR EACH ROW EXECUTE FUNCTION phase7_lock();
CREATE TRIGGER phase7_legacy_insert BEFORE INSERT ON research_evidencelegacyadmission FOR EACH ROW EXECUTE FUNCTION phase7_legacy_insert();
CREATE TRIGGER phase7_immutable BEFORE UPDATE OR DELETE ON research_evidencelegacyadmission FOR EACH ROW EXECUTE FUNCTION phase7_immutable();
CREATE TRIGGER phase7_no_truncate BEFORE TRUNCATE ON research_evidencelegacyadmission FOR EACH STATEMENT EXECUTE FUNCTION market_state_reject_truncate();

CREATE OR REPLACE FUNCTION phase7_conflicts(identity text, cutoff timestamptz) RETURNS jsonb
LANGUAGE sql STABLE SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT coalesce(jsonb_agg(jsonb_build_object('digest',d,'known_at',t,'class',c,'changed_fields',f) ORDER BY d),'[]'::jsonb)
 FROM (
  SELECT x.digest d,x.recorded_at t,x.payload->>'class' c,x.payload->'changed_fields' f
  FROM research_evidenceconflict x JOIN research_exactevidence earlier ON earlier.id=x.earlier_id
  WHERE earlier.payload->>'canonical_hash'=identity AND x.recorded_at<=cutoff
  UNION ALL
  SELECT digest,recorded_at,'unclassified_change','[]'::jsonb
  FROM research_evidencelegacyadmission
  WHERE payload->>'document'=identity AND recorded_at<=cutoff
 ) facts
$$;
"""


def refuse_populated_reverse(apps, schema_editor):
    PRIOR_CONTEXT.refuse_populated_reverse(apps, schema_editor)
    schema_editor.execute("LOCK TABLE research_evidencelegacyadmission IN ACCESS EXCLUSIVE MODE")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT EXISTS(SELECT 1 FROM research_evidencelegacyadmission)")
        if cursor.fetchone()[0]:
            raise RuntimeError("Phase7 populated evidence reversal refused")


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0021_phase7_context_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="exactevidence",
            name="admitted_macro_label",
            field=models.TextField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name="EvidenceLegacyAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField()),
                (
                    "discrepancy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="research.researchdiscrepancy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunSQL(
            SQL + OLD_CONTEXT.replace(PRIOR_CONTEXT.METHOD_SHA256, METHOD_SHA256),
            OLD_CONTEXT
            + OLD_CONFLICTS
            + """
            DROP TRIGGER phase7_source_provenance ON research_exactevidence;
            DROP FUNCTION phase7_source_provenance();
            DROP TRIGGER phase7_legacy_insert ON research_evidencelegacyadmission;
            DROP FUNCTION phase7_legacy_insert();
            """,
        ),
        migrations.RunPython(migrations.RunPython.noop, refuse_populated_reverse),
    ]
