# Generated by Django 5.2.17 on 2026-08-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("task_name", models.CharField(max_length=120)),
                ("parameters", models.JSONField(default=dict)),
                ("interval_seconds", models.PositiveIntegerField()),
                ("next_run_at", models.DateTimeField()),
                ("enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("next_run_at",),
            },
        ),
        migrations.CreateModel(
            name="JobOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("task_name", models.CharField(max_length=120)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("scheduled_for", models.DateTimeField()),
                ("available_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scheduled_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="occurrences",
                        to="operations.scheduledjob",
                    ),
                ),
            ],
            options={
                "ordering": ("-scheduled_for",),
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"], name="operations__status_1fc4b3_idx"
                    )
                ],
            },
        ),
    ]
