# Generated by Django 5.2.17 on 2026-08-20 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboccurrence",
            name="error_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="joboccurrence",
            name="error_summary",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="joboccurrence",
            name="execution_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joboccurrence",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joboccurrence",
            name="lateness_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="joboccurrence",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joboccurrence",
            name="lease_owner",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="joboccurrence",
            name="skipped_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="joboccurrence",
            name="timeout_seconds",
            field=models.PositiveIntegerField(default=900),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="local_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="missed_run_policy",
            field=models.CharField(
                choices=[("latest", "Latest"), ("all", "All"), ("skip", "Skip")],
                default="latest",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="schedule_type",
            field=models.CharField(
                choices=[("interval", "Interval"), ("daily", "Daily wall clock")],
                default="interval",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="timezone_name",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.AlterField(
            model_name="scheduledjob",
            name="interval_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("channel", models.CharField(max_length=40)),
                ("template", models.CharField(max_length=120)),
                ("payload", models.JSONField(default=dict)),
                ("not_before", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("lease_owner", models.CharField(blank=True, max_length=200)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "not_before"], name="operations__status_dbf6f8_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(max_length=80)),
                ("purpose", models.CharField(max_length=80)),
                ("daily_cap_usd", models.DecimalField(decimal_places=4, max_digits=12)),
                ("monthly_cap_usd", models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "purpose"), name="unique_provider_budget"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderBudgetReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("estimated_usd", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "actual_usd",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("settled", "Settled"),
                            ("released", "Released"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="reserved",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="operations.providerbudget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("worker_id", models.CharField(max_length=200)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="started",
                        max_length=12,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("summary", models.CharField(blank=True, max_length=240)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_attempts",
                        to="operations.outboxmessage",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "attempt_number"), name="unique_delivery_attempt"
                    )
                ],
            },
        ),
    ]
