# Generated by Django 5.2.17 on 2026-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_joboccurrence_error_code_joboccurrence_error_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerbudgetreservation",
            name="actual_usd",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="providerbudgetreservation",
            name="estimated_usd",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
