# Generated by Django 5.2.17 on 2026-08-20 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0003_alter_providerbudgetreservation_actual_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerbudgetreservation",
            name="budget_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
