# Generated by Django 5.2.17 on 2026-08-20 23:26

import django.utils.timezone
from django.db import migrations, models

CREATE_TRIGGER = """
CREATE OR REPLACE FUNCTION reject_mutation_operations_ownernotification()
RETURNS trigger AS $$
BEGIN RAISE EXCEPTION 'operations_ownernotification is immutable'; END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER operations_ownernotification_immutable
BEFORE UPDATE OR DELETE ON operations_ownernotification
FOR EACH ROW EXECUTE FUNCTION reject_mutation_operations_ownernotification();
"""

DROP_TRIGGER = """
DROP TRIGGER IF EXISTS operations_ownernotification_immutable ON operations_ownernotification;
DROP FUNCTION IF EXISTS reject_mutation_operations_ownernotification();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_providerbudgetreservation_budget_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("kind", models.CharField(max_length=80)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("action", "Action required"),
                            ("warning", "Warning"),
                        ],
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField()),
                ("action_path", models.CharField(blank=True, max_length=240)),
                ("subject_type", models.CharField(max_length=80)),
                ("subject_id", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.RunSQL(CREATE_TRIGGER, DROP_TRIGGER),
    ]
