# Generated by Django 5.2.17 on 2026-09-07 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0005_ownernotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerbudgetreservation",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending validation"),
                    ("validated", "Validated"),
                    ("rejected", "Rejected response"),
                    ("cap_exceeded", "Per-run cap exceeded"),
                    ("provider_failed", "Provider failed"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="providerbudgetreservation",
            name="pricing_version",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="providerbudgetreservation",
            name="requested_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="providerbudgetreservation",
            name="returned_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="providerbudgetreservation",
            name="usage_identity",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name="TaskFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("task_name", models.CharField(max_length=120)),
                ("error_code", models.CharField(max_length=80)),
                ("category", models.CharField(max_length=40)),
                ("stage", models.CharField(blank=True, max_length=80)),
                ("exception_type", models.CharField(blank=True, max_length=120)),
                ("summary", models.CharField(blank=True, max_length=240)),
                ("terminal", models.BooleanField()),
                ("occurred_at", models.DateTimeField()),
                (
                    "occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="failures",
                        to="operations.joboccurrence",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at", "-id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("occurrence", "attempt_number"), name="unique_task_failure_attempt"
                    )
                ],
            },
        ),
    ]
