"""Gate 8E: successor contract and acquisition-plan materialization (code only).

This module composes the existing provider-observed generators to produce, in one
atomic transaction, the four pieces of successor acquisition metadata:

    one data contract, one dataset version, one acquisition plan, 132 chunks

and nothing else. It creates no acquisition attempt, run, candle, manifest,
provider evidence, dataset registration or strategy output, and it contacts no
provider. Materialization against a persistent database is a separately
authorized gate; this module only makes the transition expressible.

Semantic note on ``discovery_version``
--------------------------------------
The contract payload retains ``discovery_version = "phase-2b1r-discovery-v1"``
for the successor, exactly as the predecessor contract carries it. That field
names the discovery *contract/schema generation*, which is unchanged, not the
particular discovery *plan generation*. The predecessor is the governing
precedent: its contract already carries ``phase-2b1r-discovery-v1`` while its
discovery plan is v2. Introducing ``phase-2b1r-discovery-v3`` here would invent a
contract identity with no governed precedent and conflate two distinct concepts.

The successor is instead distinguished and bound entirely through already
accepted evidence: its discovery plan SHA, request-manifest SHA, registration
report SHA, approval SHA, semantic inventory SHA, operational-evidence-set SHA,
restricted-overlap SHA and the accepted Gate 8D3 artifact digest, together with
the successor data identity and the deterministic identities derived from them.
Because the successor's semantic inventory and data identity differ, its contract
payload and every downstream identity necessarily differ from the predecessor's;
it can neither collide with nor masquerade as the predecessor.
"""

from django.db import transaction

from market.historical_acquisition import (
    PHASE1_MANIFEST_SHA256,
    PHASE1_SPEC_SHA256,
)
from market.historical_discovery import (
    DISCOVERY_CONTRACT,
    DISCOVERY_VERSION,
    SUPERSEDED_DATA_IDENTITY,
    canonical_hash,
)
from market.historical_discovery import (
    SOURCE_IDENTITY as DISCOVERY_SOURCE_IDENTITY,
)
from market.models import (
    DatasetVersion,
    HistoricalDataContract,
    HistoricalDatasetPlan,
    HistoricalDiscoveryRegistration,
    SourceRegistry,
)
from market.provider_observed_acquisition import (
    REPLACEMENT_ACQUISITION_CONTRACT,
    REPLACEMENT_DATA_IDENTITY,
    REPLACEMENT_DATASET_NAME,
    _build_replacement_payloads,
    _replacement_chunk_rows,
    acquisition_identities,
    materialize_replacement_chunks,
)
from market.provider_observed_outcome import accepted_successor_registration
from market.services import DatasetQualityError

# The successor's own governed identities. The data identity advances because the
# dataset it describes is a different accepted acquisition generation; the
# acquisition contract and dataset name are unchanged because neither the
# contract nor the dataset's meaning changed.
SUCCESSOR_DATA_IDENTITY = "oanda-ba-ny17-friday-provider-observed-v2"
SUCCESSOR_ACQUISITION_VERSION = "phase-2b1r-v2"
SUCCESSOR_DATASET_VERSION = "phase-2b1r-v2"
SUCCESSOR_DATASET_DESCRIPTION = (
    "Provider-observed failed-break historical dataset acquired against the"
    " sealed Gate 8D4 successor timestamp inventory"
)
SUCCESSOR_GRANULARITY_CHUNKS = {"D": 6, "H1": 120, "W": 6}
SUCCESSOR_CHUNK_COUNT = 132
SUCCESSOR_INSTRUMENT_CHUNKS = {"D": 1, "H1": 20, "W": 1}
SOURCE_REGISTRY_NAME = "OANDA v20"

# Deterministic successor identities, regenerated by
# successor_materialization_identities() and pinned by migration 0025. They are
# recorded here so a drift in any generator is a test failure rather than a
# silently different governed identity.
SUCCESSOR_CONTRACT_SHA256 = "d630cc100cd06abdaa5d08d88353542999d625dd0c80f43eecbb5f649109f11c"
SUCCESSOR_ACQUISITION_PLAN_SHA256 = (
    "44dc82b2f20975e34e34e30ca7a709fff059ed14fa7457aaa26da4222d4df4cd"
)
SUCCESSOR_DATASET_MANIFEST_SHA256 = (
    "11da094fc7ca6a30e946be33523757d7ab559a9ad1951c9142e8969539930014"
)
SUCCESSOR_ACQUISITION_CANARY_LOGICAL_KEY = (
    "7b96484393a7e82eafd3bb5389dbf7f6b5b00ba6c9ed201d81814829b44a6151"
)


def successor_identities():
    """The successor acquisition identity bundle, bound to accepted evidence."""
    accepted = accepted_successor_registration()
    return acquisition_identities(
        acquisition_contract=REPLACEMENT_ACQUISITION_CONTRACT,
        acquisition_version=SUCCESSOR_ACQUISITION_VERSION,
        data_identity=SUCCESSOR_DATA_IDENTITY,
        discovery_plan_sha256=accepted["plan_sha256"],
        dataset_name=REPLACEMENT_DATASET_NAME,
        dataset_version=SUCCESSOR_DATASET_VERSION,
        dataset_description=SUCCESSOR_DATASET_DESCRIPTION,
    )


def build_successor_data_contract_payload(global_semantic_inventory_sha256):
    """The successor contract's semantic body.

    Identical in shape to the predecessor's, and deliberately identical in
    ``discovery_contract``, ``discovery_version``, ``source_identity``, the two
    Phase 1 hashes and ``superseded_semantic_identity``. Exactly two fields
    differ, and both are accepted successor evidence: the data identity and the
    successor global semantic inventory hash. That is what makes the successor
    contract a distinct governed identity without inventing a new schema
    generation.
    """
    return {
        "discovery_contract": DISCOVERY_CONTRACT,
        # Unchanged on purpose: names the discovery contract generation, not the
        # discovery plan generation. See the module docstring.
        "discovery_version": DISCOVERY_VERSION,
        "source_identity": DISCOVERY_SOURCE_IDENTITY,
        "phase1_spec_hash": PHASE1_SPEC_SHA256,
        "phase1_manifest_hash": PHASE1_MANIFEST_SHA256,
        "replacement_data_identity": SUCCESSOR_DATA_IDENTITY,
        "superseded_semantic_identity": SUPERSEDED_DATA_IDENTITY,
        "global_semantic_inventory_sha256": global_semantic_inventory_sha256,
    }


def successor_data_contract_semantic_hash(*, global_semantic_inventory_sha256):
    """Portable successor contract identity: canonical inputs only, never ids."""
    return canonical_hash(build_successor_data_contract_payload(global_semantic_inventory_sha256))


def sealed_successor_registration():
    """The accepted Gate 8D4 registration, resolved only by governed evidence.

    Every comparison is against an independently accepted digest. No row-declared
    count or identity is trusted: the registration must reconstruct the accepted
    plan, manifest, semantic, operational and cross-series report hashes, and its
    plan must be sealed at exactly the registration instant.
    """
    accepted = accepted_successor_registration()
    registration = (
        HistoricalDiscoveryRegistration.objects.select_related("plan", "approval")
        .filter(plan__sha256=accepted["plan_sha256"])
        .first()
    )
    if (
        registration is None
        or registration.plan.sealed_at is None
        or registration.plan.sealed_at != registration.registered_at
        or registration.ordered_chunk_manifest_sha256 != accepted["request_manifest_sha256"]
        or registration.global_semantic_inventory_sha256
        != accepted["global_semantic_inventory_sha256"]
        or registration.accepted_operational_evidence_set_sha256
        != accepted["accepted_operational_evidence_set_sha256"]
        or registration.cross_series_report_sha256 != accepted["outcome_artifact_sha256"]
        or registration.global_semantic_inventory_sha256
        != registration.approval.global_semantic_inventory_sha256
    ):
        raise DatasetQualityError(
            "gate 8E requires the accepted sealed successor discovery registration"
        )
    return registration


def _successor_strategy_is_unchanged(strategy_version):
    return (
        strategy_version.content_hash == PHASE1_MANIFEST_SHA256
        and strategy_version.data_identity == SUPERSEDED_DATA_IDENTITY
    )


def build_successor_acquisition_payloads(contract):
    """Deterministically generate the successor plan, dataset manifest and chunks.

    Composed from the same generators the predecessor used; only the identity
    bundle differs. Coverage is checked against accepted evidence rather than
    against anything the rows declare about themselves.
    """
    accepted = accepted_successor_registration()
    registration = sealed_successor_registration()
    if (
        contract.discovery_registration_id != registration.pk
        or contract.identity != SUCCESSOR_DATA_IDENTITY
        or contract.global_semantic_inventory_sha256 != accepted["global_semantic_inventory_sha256"]
        or contract.approval_sha256 != registration.approval.sha256
        or contract.registration_report_sha256 != registration.report_sha256
        or contract.sha256
        != successor_data_contract_semantic_hash(
            global_semantic_inventory_sha256=accepted["global_semantic_inventory_sha256"]
        )
    ):
        raise DatasetQualityError("gate 8E plan requires the governed successor data contract")
    chunk_rows = _replacement_chunk_rows(registration.plan)
    grouped = {}
    per_instrument = {}
    for row in chunk_rows:
        grouped[row["granularity"]] = grouped.get(row["granularity"], 0) + 1
        key = (row["instrument"], row["granularity"])
        per_instrument[key] = per_instrument.get(key, 0) + 1
    instruments = sorted({row["instrument"] for row in chunk_rows})
    expected_per_instrument = {
        (instrument, granularity): count
        for instrument in instruments
        for granularity, count in SUCCESSOR_INSTRUMENT_CHUNKS.items()
    }
    total = sum(row["expected_observation_count"] for row in chunk_rows)
    if (
        len(chunk_rows) != SUCCESSOR_CHUNK_COUNT
        or grouped != SUCCESSOR_GRANULARITY_CHUNKS
        or per_instrument != expected_per_instrument
        or total != accepted["observation_count"]
    ):
        raise DatasetQualityError("gate 8E plan requires the exact accepted successor coverage")
    strategy = contract.strategy_version
    return _build_replacement_payloads(
        contract_sha256=contract.sha256,
        global_semantic_inventory_sha256=contract.global_semantic_inventory_sha256,
        strategy={
            "definition_key": strategy.definition.key,
            "version": strategy.version,
            "content_hash": strategy.content_hash,
        },
        chunk_rows=chunk_rows,
        identities=successor_identities(),
    )


def successor_acquisition_canary_logical_key(payloads):
    """The one chunk the governed acquisition canary admits first.

    Selection is deterministic and portable: the lowest ordinal, which is the
    same rule the predecessor generation used. The resulting key is pinned as a
    literal by the governing migration; this helper exists so the pin can be
    regenerated and compared, never so a caller can choose a different canary.
    """
    ordered = sorted(payloads["chunks"], key=lambda row: row["ordinal"])
    return ordered[0]["logical_key"]


@transaction.atomic
def materialize_gate8e_successor_metadata(strategy_version, *, parent_dataset=None):
    """Create the successor contract, dataset, acquisition plan and 132 chunks.

    One atomic transaction. This is the governed materialization service the
    provider-observed path previously lacked: the predecessor's contract, plan,
    dataset and chunks were produced by three separate pieces with no single
    atomic entry point. Any failure rolls the whole transition back.

    ``parent_dataset`` is operational lineage metadata only. It is stored on the
    DatasetVersion row and never enters the dataset manifest, the plan payload,
    any chunk logical key or any portable identity, so changing or omitting it
    cannot change a single governed hash.
    """
    if not _successor_strategy_is_unchanged(strategy_version):
        raise DatasetQualityError("gate 8E requires the unchanged approved strategy version")
    registration = sealed_successor_registration()
    accepted = accepted_successor_registration()
    semantic = accepted["global_semantic_inventory_sha256"]
    contract = HistoricalDataContract.objects.create(
        identity=SUCCESSOR_DATA_IDENTITY,
        strategy_version=strategy_version,
        discovery_registration=registration,
        superseded_data_identity=SUPERSEDED_DATA_IDENTITY,
        phase1_spec_hash=PHASE1_SPEC_SHA256,
        phase1_manifest_hash=PHASE1_MANIFEST_SHA256,
        global_semantic_inventory_sha256=semantic,
        approval_sha256=registration.approval.sha256,
        registration_report_sha256=registration.report_sha256,
        payload=build_successor_data_contract_payload(semantic),
        sha256=successor_data_contract_semantic_hash(global_semantic_inventory_sha256=semantic),
    )
    payloads = build_successor_acquisition_payloads(contract)
    # The governed source is selected exactly as the predecessor path selects it:
    # by registry name, with the governed identity asserted in the plan payload.
    if payloads["plan"]["source"] != {
        "name": SOURCE_REGISTRY_NAME,
        "governed_identity": DISCOVERY_SOURCE_IDENTITY,
    }:
        raise DatasetQualityError("gate 8E requires the governed provider source selector")
    source = SourceRegistry.objects.get(name=SOURCE_REGISTRY_NAME)
    plan = HistoricalDatasetPlan.objects.create(
        identity=SUCCESSOR_DATA_IDENTITY,
        source=source,
        strategy_version=strategy_version,
        instruments=payloads["plan"]["instruments"],
        granularities=payloads["plan"]["granularities"],
        ranges=payloads["plan"]["ranges"],
        alignment=payloads["plan"]["alignment"],
        chunk_size=payloads["plan"]["chunk_size"],
        phase1_spec_hash=PHASE1_SPEC_SHA256,
        phase1_manifest_hash=PHASE1_MANIFEST_SHA256,
        payload=payloads["plan"],
        sha256=payloads["plan_sha256"],
        data_contract=contract,
        data_contract_sha256=contract.sha256,
    )
    dataset = DatasetVersion.objects.create(
        name=REPLACEMENT_DATASET_NAME,
        version=SUCCESSOR_DATASET_VERSION,
        description=SUCCESSOR_DATASET_DESCRIPTION,
        source=source,
        parent=parent_dataset,
        manifest=payloads["dataset_manifest"],
        data_contract_sha256=contract.sha256,
    )
    chunks = materialize_replacement_chunks(plan, dataset, payloads)
    if len(chunks) != SUCCESSOR_CHUNK_COUNT:
        raise DatasetQualityError("gate 8E must materialize exactly 132 acquisition chunks")
    return {
        "contract": contract,
        "plan": plan,
        "dataset": dataset,
        "chunks": chunks,
        "payloads": payloads,
    }


def successor_materialization_identities(payloads, contract):
    """Portable identities the governed migration pins. No ids, no timestamps."""
    return {
        "data_identity": SUCCESSOR_DATA_IDENTITY,
        "data_contract_sha256": contract.sha256,
        "acquisition_plan_sha256": payloads["plan_sha256"],
        "dataset_manifest_sha256": payloads["dataset_manifest_sha256"],
        "acquisition_canary_logical_key": successor_acquisition_canary_logical_key(payloads),
        "chunk_count": len(payloads["chunks"]),
    }


__all__ = [
    "SUCCESSOR_ACQUISITION_VERSION",
    "SUCCESSOR_CHUNK_COUNT",
    "SUCCESSOR_DATASET_DESCRIPTION",
    "SUCCESSOR_DATASET_VERSION",
    "SUCCESSOR_DATA_IDENTITY",
    "SUCCESSOR_GRANULARITY_CHUNKS",
    "SUCCESSOR_INSTRUMENT_CHUNKS",
    "build_successor_acquisition_payloads",
    "build_successor_data_contract_payload",
    "materialize_gate8e_successor_metadata",
    "sealed_successor_registration",
    "successor_acquisition_canary_logical_key",
    "successor_data_contract_semantic_hash",
    "successor_identities",
    "successor_materialization_identities",
    "REPLACEMENT_DATA_IDENTITY",
]
